// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type InterviewAssignment struct {
	ID                    uuid.UUID          `json:"id"`
	InterviewSlotID       uuid.UUID          `json:"interview_slot_id"`
	CourseParticipationID uuid.UUID          `json:"course_participation_id"`
	AssignedAt            pgtype.Timestamptz `json:"assigned_at"`
}

type InterviewSlot struct {
	ID            uuid.UUID          `json:"id"`
	CoursePhaseID uuid.UUID          `json:"course_phase_id"`
	StartTime     pgtype.Timestamptz `json:"start_time"`
	EndTime       pgtype.Timestamptz `json:"end_time"`
	Location      pgtype.Text        `json:"location"`
	Capacity      int32              `json:"capacity"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
