// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: privacy.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteInterviewAssignmentsByParticipationIDs = `-- name: DeleteInterviewAssignmentsByParticipationIDs :exec
DELETE FROM interview_assignment
WHERE course_participation_id = ANY($1::uuid[])
`

func (q *Queries) DeleteInterviewAssignmentsByParticipationIDs(ctx context.Context, courseParticipationIds []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInterviewAssignmentsByParticipationIDs, courseParticipationIds)
	return err
}

const getInterviewAssignmentsByParticipationIDs = `-- name: GetInterviewAssignmentsByParticipationIDs :many
SELECT
    ia.id,
    ia.course_participation_id,
    ia.assigned_at,
    s.course_phase_id,
    s.start_time,
    s.end_time,
    s.location
FROM interview_assignment ia
JOIN interview_slot s ON ia.interview_slot_id = s.id
WHERE ia.course_participation_id = ANY($1::uuid[])
ORDER BY s.start_time ASC
`

type GetInterviewAssignmentsByParticipationIDsRow struct {
	ID                    uuid.UUID          `json:"id"`
	CourseParticipationID uuid.UUID          `json:"course_participation_id"`
	AssignedAt            pgtype.Timestamptz `json:"assigned_at"`
	CoursePhaseID         uuid.UUID          `json:"course_phase_id"`
	StartTime             pgtype.Timestamptz `json:"start_time"`
	EndTime               pgtype.Timestamptz `json:"end_time"`
	Location              pgtype.Text        `json:"location"`
}

func (q *Queries) GetInterviewAssignmentsByParticipationIDs(ctx context.Context, courseParticipationIds []uuid.UUID) ([]GetInterviewAssignmentsByParticipationIDsRow, error) {
	rows, err := q.db.Query(ctx, getInterviewAssignmentsByParticipationIDs, courseParticipationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInterviewAssignmentsByParticipationIDsRow
	for rows.Next() {
		var i GetInterviewAssignmentsByParticipationIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseParticipationID,
			&i.AssignedAt,
			&i.CoursePhaseID,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
