// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: name.sql

package db

import (
	"context"
)

const getName = `-- name: GetName :many
SELECT course_phase_id, name
FROM template_table
`

func (q *Queries) GetName(ctx context.Context) ([]TemplateTable, error) {
	rows, err := q.db.Query(ctx, getName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TemplateTable
	for rows.Next() {
		var i TemplateTable
		if err := rows.Scan(&i.CoursePhaseID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
