// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: category_assessment.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createOrUpdateCategoryAssessment = `-- name: CreateOrUpdateCategoryAssessment :exec
INSERT INTO category_assessment (id, category_id, course_phase_id, course_participation_id,
                                 comment, author, author_id, created_at, updated_at)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, now(), now())
ON CONFLICT (category_id, course_phase_id, course_participation_id)
    DO UPDATE
    SET comment    = EXCLUDED.comment,
        author     = EXCLUDED.author,
        author_id  = EXCLUDED.author_id,
        updated_at = now()
`

type CreateOrUpdateCategoryAssessmentParams struct {
	CategoryID            uuid.UUID `json:"category_id"`
	CoursePhaseID         uuid.UUID `json:"course_phase_id"`
	CourseParticipationID uuid.UUID `json:"course_participation_id"`
	Comment               string    `json:"comment"`
	Author                string    `json:"author"`
	AuthorID              string    `json:"author_id"`
}

func (q *Queries) CreateOrUpdateCategoryAssessment(ctx context.Context, arg CreateOrUpdateCategoryAssessmentParams) error {
	_, err := q.db.Exec(ctx, createOrUpdateCategoryAssessment,
		arg.CategoryID,
		arg.CoursePhaseID,
		arg.CourseParticipationID,
		arg.Comment,
		arg.Author,
		arg.AuthorID,
	)
	return err
}

const listCategoryAssessmentsByStudentInPhase = `-- name: ListCategoryAssessmentsByStudentInPhase :many
SELECT id, category_id, course_phase_id, course_participation_id, comment, author, author_id, created_at, updated_at
FROM category_assessment
WHERE course_participation_id = $1
  AND course_phase_id = $2
`

type ListCategoryAssessmentsByStudentInPhaseParams struct {
	CourseParticipationID uuid.UUID `json:"course_participation_id"`
	CoursePhaseID         uuid.UUID `json:"course_phase_id"`
}

func (q *Queries) ListCategoryAssessmentsByStudentInPhase(ctx context.Context, arg ListCategoryAssessmentsByStudentInPhaseParams) ([]CategoryAssessment, error) {
	rows, err := q.db.Query(ctx, listCategoryAssessmentsByStudentInPhase, arg.CourseParticipationID, arg.CoursePhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoryAssessment
	for rows.Next() {
		var i CategoryAssessment
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.CoursePhaseID,
			&i.CourseParticipationID,
			&i.Comment,
			&i.Author,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
