// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: course_phase_config.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkAssessmentSchemaUsageInOtherPhases = `-- name: CheckAssessmentSchemaUsageInOtherPhases :one
SELECT EXISTS(
    SELECT 1
    FROM course_phase_config cpc
    WHERE (
        cpc.assessment_schema_id = $1
        OR cpc.self_evaluation_schema = $1
        OR cpc.peer_evaluation_schema = $1
        OR cpc.tutor_evaluation_schema = $1
    )
    AND cpc.course_phase_id != $2
    AND EXISTS(
        SELECT 1
        FROM assessment a
        WHERE a.course_phase_id = cpc.course_phase_id
        AND a.competency_id IN (
            SELECT co.id
            FROM competency co
            INNER JOIN category cat ON co.category_id = cat.id
            WHERE cat.assessment_schema_id = $1
        )
        UNION
        SELECT 1
        FROM evaluation e
        WHERE e.course_phase_id = cpc.course_phase_id
        AND e.competency_id IN (
            SELECT co.id
            FROM competency co
            INNER JOIN category cat ON co.category_id = cat.id
            WHERE cat.assessment_schema_id = $1
        )
    )
) AS schema_used_in_other_phases
`

type CheckAssessmentSchemaUsageInOtherPhasesParams struct {
	AssessmentSchemaID uuid.UUID `json:"assessment_schema_id"`
	CoursePhaseID      uuid.UUID `json:"course_phase_id"`
}

func (q *Queries) CheckAssessmentSchemaUsageInOtherPhases(ctx context.Context, arg CheckAssessmentSchemaUsageInOtherPhasesParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkAssessmentSchemaUsageInOtherPhases, arg.AssessmentSchemaID, arg.CoursePhaseID)
	var schema_used_in_other_phases bool
	err := row.Scan(&schema_used_in_other_phases)
	return schema_used_in_other_phases, err
}

const createDefaultCoursePhaseConfig = `-- name: CreateDefaultCoursePhaseConfig :exec
INSERT INTO course_phase_config (course_phase_id)
VALUES ($1)
`

func (q *Queries) CreateDefaultCoursePhaseConfig(ctx context.Context, coursePhaseID uuid.UUID) error {
	_, err := q.db.Exec(ctx, createDefaultCoursePhaseConfig, coursePhaseID)
	return err
}

const createOrUpdateCoursePhaseConfig = `-- name: CreateOrUpdateCoursePhaseConfig :exec
INSERT INTO course_phase_config (assessment_schema_id,
                                 course_phase_id,
                                 start,
                                 deadline,
                                 self_evaluation_enabled,
                                 self_evaluation_schema,
                                 self_evaluation_start,
                                 self_evaluation_deadline,
                                 peer_evaluation_enabled,
                                 peer_evaluation_schema,
                                 peer_evaluation_start,
                                 peer_evaluation_deadline,
                                 tutor_evaluation_enabled,
                                 tutor_evaluation_schema,
                                 tutor_evaluation_start,
                                 tutor_evaluation_deadline,
                                 evaluation_results_visible,
                                 grade_suggestion_visible,
                                 action_items_visible,
                                 results_released,
                                 grading_sheet_visible)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, 
        COALESCE($18::boolean, TRUE), 
        COALESCE($19::boolean, TRUE),
        COALESCE($20::boolean, FALSE),
        COALESCE($21::boolean, FALSE))
ON CONFLICT (course_phase_id)
    DO UPDATE SET assessment_schema_id      = EXCLUDED.assessment_schema_id,
                  start                     = EXCLUDED.start,
                  deadline                  = EXCLUDED.deadline,
                  self_evaluation_enabled   = EXCLUDED.self_evaluation_enabled,
                  self_evaluation_schema    = EXCLUDED.self_evaluation_schema,
                  self_evaluation_start     = EXCLUDED.self_evaluation_start,
                  self_evaluation_deadline  = EXCLUDED.self_evaluation_deadline,
                  peer_evaluation_enabled   = EXCLUDED.peer_evaluation_enabled,
                  peer_evaluation_schema    = EXCLUDED.peer_evaluation_schema,
                  peer_evaluation_start     = EXCLUDED.peer_evaluation_start,
                  peer_evaluation_deadline  = EXCLUDED.peer_evaluation_deadline,
                  tutor_evaluation_enabled  = EXCLUDED.tutor_evaluation_enabled,
                  tutor_evaluation_schema   = EXCLUDED.tutor_evaluation_schema,
                  tutor_evaluation_start    = EXCLUDED.tutor_evaluation_start,
                  tutor_evaluation_deadline = EXCLUDED.tutor_evaluation_deadline,
                  evaluation_results_visible = EXCLUDED.evaluation_results_visible,
                  grade_suggestion_visible  = COALESCE(EXCLUDED.grade_suggestion_visible, TRUE),
                  action_items_visible      = COALESCE(EXCLUDED.action_items_visible, TRUE),
                  results_released          = COALESCE(EXCLUDED.results_released, FALSE),
                  grading_sheet_visible     = COALESCE(EXCLUDED.grading_sheet_visible, FALSE)
`

type CreateOrUpdateCoursePhaseConfigParams struct {
	AssessmentSchemaID       uuid.UUID          `json:"assessment_schema_id"`
	CoursePhaseID            uuid.UUID          `json:"course_phase_id"`
	Start                    pgtype.Timestamptz `json:"start"`
	Deadline                 pgtype.Timestamptz `json:"deadline"`
	SelfEvaluationEnabled    bool               `json:"self_evaluation_enabled"`
	SelfEvaluationSchema     uuid.UUID          `json:"self_evaluation_schema"`
	SelfEvaluationStart      pgtype.Timestamptz `json:"self_evaluation_start"`
	SelfEvaluationDeadline   pgtype.Timestamptz `json:"self_evaluation_deadline"`
	PeerEvaluationEnabled    bool               `json:"peer_evaluation_enabled"`
	PeerEvaluationSchema     uuid.UUID          `json:"peer_evaluation_schema"`
	PeerEvaluationStart      pgtype.Timestamptz `json:"peer_evaluation_start"`
	PeerEvaluationDeadline   pgtype.Timestamptz `json:"peer_evaluation_deadline"`
	TutorEvaluationEnabled   bool               `json:"tutor_evaluation_enabled"`
	TutorEvaluationSchema    uuid.UUID          `json:"tutor_evaluation_schema"`
	TutorEvaluationStart     pgtype.Timestamptz `json:"tutor_evaluation_start"`
	TutorEvaluationDeadline  pgtype.Timestamptz `json:"tutor_evaluation_deadline"`
	EvaluationResultsVisible bool               `json:"evaluation_results_visible"`
	GradeSuggestionVisible   pgtype.Bool        `json:"grade_suggestion_visible"`
	ActionItemsVisible       pgtype.Bool        `json:"action_items_visible"`
	ResultsReleased          pgtype.Bool        `json:"results_released"`
	GradingSheetVisible      pgtype.Bool        `json:"grading_sheet_visible"`
}

func (q *Queries) CreateOrUpdateCoursePhaseConfig(ctx context.Context, arg CreateOrUpdateCoursePhaseConfigParams) error {
	_, err := q.db.Exec(ctx, createOrUpdateCoursePhaseConfig,
		arg.AssessmentSchemaID,
		arg.CoursePhaseID,
		arg.Start,
		arg.Deadline,
		arg.SelfEvaluationEnabled,
		arg.SelfEvaluationSchema,
		arg.SelfEvaluationStart,
		arg.SelfEvaluationDeadline,
		arg.PeerEvaluationEnabled,
		arg.PeerEvaluationSchema,
		arg.PeerEvaluationStart,
		arg.PeerEvaluationDeadline,
		arg.TutorEvaluationEnabled,
		arg.TutorEvaluationSchema,
		arg.TutorEvaluationStart,
		arg.TutorEvaluationDeadline,
		arg.EvaluationResultsVisible,
		arg.GradeSuggestionVisible,
		arg.ActionItemsVisible,
		arg.ResultsReleased,
		arg.GradingSheetVisible,
	)
	return err
}

const getCoursePhaseConfig = `-- name: GetCoursePhaseConfig :one
SELECT assessment_schema_id, course_phase_id, deadline, self_evaluation_enabled, self_evaluation_schema, self_evaluation_deadline, peer_evaluation_enabled, peer_evaluation_schema, peer_evaluation_deadline, start, self_evaluation_start, peer_evaluation_start, tutor_evaluation_enabled, tutor_evaluation_start, tutor_evaluation_deadline, tutor_evaluation_schema, evaluation_results_visible, grade_suggestion_visible, action_items_visible, results_released, grading_sheet_visible
FROM course_phase_config
WHERE course_phase_id = $1
`

func (q *Queries) GetCoursePhaseConfig(ctx context.Context, coursePhaseID uuid.UUID) (CoursePhaseConfig, error) {
	row := q.db.QueryRow(ctx, getCoursePhaseConfig, coursePhaseID)
	var i CoursePhaseConfig
	err := row.Scan(
		&i.AssessmentSchemaID,
		&i.CoursePhaseID,
		&i.Deadline,
		&i.SelfEvaluationEnabled,
		&i.SelfEvaluationSchema,
		&i.SelfEvaluationDeadline,
		&i.PeerEvaluationEnabled,
		&i.PeerEvaluationSchema,
		&i.PeerEvaluationDeadline,
		&i.Start,
		&i.SelfEvaluationStart,
		&i.PeerEvaluationStart,
		&i.TutorEvaluationEnabled,
		&i.TutorEvaluationStart,
		&i.TutorEvaluationDeadline,
		&i.TutorEvaluationSchema,
		&i.EvaluationResultsVisible,
		&i.GradeSuggestionVisible,
		&i.ActionItemsVisible,
		&i.ResultsReleased,
		&i.GradingSheetVisible,
	)
	return i, err
}

const getCoursePhasesByAssessmentSchema = `-- name: GetCoursePhasesByAssessmentSchema :many
SELECT course_phase_id
FROM course_phase_config
WHERE assessment_schema_id = $1
`

func (q *Queries) GetCoursePhasesByAssessmentSchema(ctx context.Context, assessmentSchemaID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getCoursePhasesByAssessmentSchema, assessmentSchemaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var course_phase_id uuid.UUID
		if err := rows.Scan(&course_phase_id); err != nil {
			return nil, err
		}
		items = append(items, course_phase_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPeerEvaluationTimeframe = `-- name: GetPeerEvaluationTimeframe :one
SELECT peer_evaluation_start, peer_evaluation_deadline
FROM course_phase_config
WHERE course_phase_id = $1
`

type GetPeerEvaluationTimeframeRow struct {
	PeerEvaluationStart    pgtype.Timestamptz `json:"peer_evaluation_start"`
	PeerEvaluationDeadline pgtype.Timestamptz `json:"peer_evaluation_deadline"`
}

func (q *Queries) GetPeerEvaluationTimeframe(ctx context.Context, coursePhaseID uuid.UUID) (GetPeerEvaluationTimeframeRow, error) {
	row := q.db.QueryRow(ctx, getPeerEvaluationTimeframe, coursePhaseID)
	var i GetPeerEvaluationTimeframeRow
	err := row.Scan(&i.PeerEvaluationStart, &i.PeerEvaluationDeadline)
	return i, err
}

const getSelfEvaluationTimeframe = `-- name: GetSelfEvaluationTimeframe :one
SELECT self_evaluation_start, self_evaluation_deadline
FROM course_phase_config
WHERE course_phase_id = $1
`

type GetSelfEvaluationTimeframeRow struct {
	SelfEvaluationStart    pgtype.Timestamptz `json:"self_evaluation_start"`
	SelfEvaluationDeadline pgtype.Timestamptz `json:"self_evaluation_deadline"`
}

func (q *Queries) GetSelfEvaluationTimeframe(ctx context.Context, coursePhaseID uuid.UUID) (GetSelfEvaluationTimeframeRow, error) {
	row := q.db.QueryRow(ctx, getSelfEvaluationTimeframe, coursePhaseID)
	var i GetSelfEvaluationTimeframeRow
	err := row.Scan(&i.SelfEvaluationStart, &i.SelfEvaluationDeadline)
	return i, err
}

const getTutorEvaluationTimeframe = `-- name: GetTutorEvaluationTimeframe :one
SELECT tutor_evaluation_start, tutor_evaluation_deadline
FROM course_phase_config
WHERE course_phase_id = $1
`

type GetTutorEvaluationTimeframeRow struct {
	TutorEvaluationStart    pgtype.Timestamptz `json:"tutor_evaluation_start"`
	TutorEvaluationDeadline pgtype.Timestamptz `json:"tutor_evaluation_deadline"`
}

func (q *Queries) GetTutorEvaluationTimeframe(ctx context.Context, coursePhaseID uuid.UUID) (GetTutorEvaluationTimeframeRow, error) {
	row := q.db.QueryRow(ctx, getTutorEvaluationTimeframe, coursePhaseID)
	var i GetTutorEvaluationTimeframeRow
	err := row.Scan(&i.TutorEvaluationStart, &i.TutorEvaluationDeadline)
	return i, err
}

const isAssessmentDeadlinePassed = `-- name: IsAssessmentDeadlinePassed :one
SELECT CASE
           WHEN deadline < NOW() THEN true
           ELSE false
           END AS is_deadline_passed
FROM course_phase_config
WHERE course_phase_id = $1
`

func (q *Queries) IsAssessmentDeadlinePassed(ctx context.Context, coursePhaseID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isAssessmentDeadlinePassed, coursePhaseID)
	var is_deadline_passed bool
	err := row.Scan(&is_deadline_passed)
	return is_deadline_passed, err
}

const isAssessmentOpen = `-- name: IsAssessmentOpen :one
SELECT CASE
           WHEN start <= NOW() THEN true
           ELSE false
           END AS has_started
FROM course_phase_config
WHERE course_phase_id = $1
`

func (q *Queries) IsAssessmentOpen(ctx context.Context, coursePhaseID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isAssessmentOpen, coursePhaseID)
	var has_started bool
	err := row.Scan(&has_started)
	return has_started, err
}

const isPeerEvaluationDeadlinePassed = `-- name: IsPeerEvaluationDeadlinePassed :one
SELECT CASE
           WHEN peer_evaluation_deadline < NOW() THEN true
           ELSE false
           END AS is_peer_evaluation_deadline_passed
FROM course_phase_config
WHERE course_phase_id = $1
`

func (q *Queries) IsPeerEvaluationDeadlinePassed(ctx context.Context, coursePhaseID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isPeerEvaluationDeadlinePassed, coursePhaseID)
	var is_peer_evaluation_deadline_passed bool
	err := row.Scan(&is_peer_evaluation_deadline_passed)
	return is_peer_evaluation_deadline_passed, err
}

const isPeerEvaluationOpen = `-- name: IsPeerEvaluationOpen :one
SELECT CASE
           WHEN peer_evaluation_enabled AND peer_evaluation_start <= NOW() THEN true
           ELSE false
           END AS has_peer_evaluation_started
FROM course_phase_config
WHERE course_phase_id = $1
`

func (q *Queries) IsPeerEvaluationOpen(ctx context.Context, coursePhaseID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isPeerEvaluationOpen, coursePhaseID)
	var has_peer_evaluation_started bool
	err := row.Scan(&has_peer_evaluation_started)
	return has_peer_evaluation_started, err
}

const isSelfEvaluationDeadlinePassed = `-- name: IsSelfEvaluationDeadlinePassed :one
SELECT CASE
           WHEN self_evaluation_enabled AND self_evaluation_deadline < NOW() THEN true
           ELSE false
           END AS is_self_evaluation_deadline_passed
FROM course_phase_config
WHERE course_phase_id = $1
`

func (q *Queries) IsSelfEvaluationDeadlinePassed(ctx context.Context, coursePhaseID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isSelfEvaluationDeadlinePassed, coursePhaseID)
	var is_self_evaluation_deadline_passed bool
	err := row.Scan(&is_self_evaluation_deadline_passed)
	return is_self_evaluation_deadline_passed, err
}

const isSelfEvaluationOpen = `-- name: IsSelfEvaluationOpen :one
SELECT CASE
           WHEN self_evaluation_enabled AND self_evaluation_start <= NOW() THEN true
           ELSE false
           END AS has_self_evaluation_started
FROM course_phase_config
WHERE course_phase_id = $1
`

func (q *Queries) IsSelfEvaluationOpen(ctx context.Context, coursePhaseID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isSelfEvaluationOpen, coursePhaseID)
	var has_self_evaluation_started bool
	err := row.Scan(&has_self_evaluation_started)
	return has_self_evaluation_started, err
}

const isTutorEvaluationDeadlinePassed = `-- name: IsTutorEvaluationDeadlinePassed :one
SELECT CASE
           WHEN tutor_evaluation_deadline < NOW() THEN true
           ELSE false
           END AS is_tutor_evaluation_deadline_passed
FROM course_phase_config
WHERE course_phase_id = $1
`

func (q *Queries) IsTutorEvaluationDeadlinePassed(ctx context.Context, coursePhaseID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isTutorEvaluationDeadlinePassed, coursePhaseID)
	var is_tutor_evaluation_deadline_passed bool
	err := row.Scan(&is_tutor_evaluation_deadline_passed)
	return is_tutor_evaluation_deadline_passed, err
}

const isTutorEvaluationOpen = `-- name: IsTutorEvaluationOpen :one
SELECT CASE
           WHEN tutor_evaluation_enabled AND tutor_evaluation_start <= NOW() THEN true
           ELSE false
           END AS has_tutor_evaluation_started
FROM course_phase_config
WHERE course_phase_id = $1
`

func (q *Queries) IsTutorEvaluationOpen(ctx context.Context, coursePhaseID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isTutorEvaluationOpen, coursePhaseID)
	var has_tutor_evaluation_started bool
	err := row.Scan(&has_tutor_evaluation_started)
	return has_tutor_evaluation_started, err
}

const listAssessmentSchemaCoursePhaseMappings = `-- name: ListAssessmentSchemaCoursePhaseMappings :many
SELECT assessment_schema_id, course_phase_id, deadline, self_evaluation_enabled, self_evaluation_schema, self_evaluation_deadline, peer_evaluation_enabled, peer_evaluation_schema, peer_evaluation_deadline, start, self_evaluation_start, peer_evaluation_start, tutor_evaluation_enabled, tutor_evaluation_start, tutor_evaluation_deadline, tutor_evaluation_schema, evaluation_results_visible, grade_suggestion_visible, action_items_visible, results_released, grading_sheet_visible
FROM course_phase_config
ORDER BY assessment_schema_id, course_phase_id
`

func (q *Queries) ListAssessmentSchemaCoursePhaseMappings(ctx context.Context) ([]CoursePhaseConfig, error) {
	rows, err := q.db.Query(ctx, listAssessmentSchemaCoursePhaseMappings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoursePhaseConfig
	for rows.Next() {
		var i CoursePhaseConfig
		if err := rows.Scan(
			&i.AssessmentSchemaID,
			&i.CoursePhaseID,
			&i.Deadline,
			&i.SelfEvaluationEnabled,
			&i.SelfEvaluationSchema,
			&i.SelfEvaluationDeadline,
			&i.PeerEvaluationEnabled,
			&i.PeerEvaluationSchema,
			&i.PeerEvaluationDeadline,
			&i.Start,
			&i.SelfEvaluationStart,
			&i.PeerEvaluationStart,
			&i.TutorEvaluationEnabled,
			&i.TutorEvaluationStart,
			&i.TutorEvaluationDeadline,
			&i.TutorEvaluationSchema,
			&i.EvaluationResultsVisible,
			&i.GradeSuggestionVisible,
			&i.ActionItemsVisible,
			&i.ResultsReleased,
			&i.GradingSheetVisible,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCoursePhaseConfigAssessmentSchema = `-- name: UpdateCoursePhaseConfigAssessmentSchema :exec
UPDATE course_phase_config
SET assessment_schema_id = $2
WHERE course_phase_id = $1
`

type UpdateCoursePhaseConfigAssessmentSchemaParams struct {
	CoursePhaseID      uuid.UUID `json:"course_phase_id"`
	AssessmentSchemaID uuid.UUID `json:"assessment_schema_id"`
}

func (q *Queries) UpdateCoursePhaseConfigAssessmentSchema(ctx context.Context, arg UpdateCoursePhaseConfigAssessmentSchemaParams) error {
	_, err := q.db.Exec(ctx, updateCoursePhaseConfigAssessmentSchema, arg.CoursePhaseID, arg.AssessmentSchemaID)
	return err
}

const updateCoursePhaseConfigPeerEvaluationSchema = `-- name: UpdateCoursePhaseConfigPeerEvaluationSchema :exec
UPDATE course_phase_config
SET peer_evaluation_schema = $2
WHERE course_phase_id = $1
`

type UpdateCoursePhaseConfigPeerEvaluationSchemaParams struct {
	CoursePhaseID        uuid.UUID `json:"course_phase_id"`
	PeerEvaluationSchema uuid.UUID `json:"peer_evaluation_schema"`
}

func (q *Queries) UpdateCoursePhaseConfigPeerEvaluationSchema(ctx context.Context, arg UpdateCoursePhaseConfigPeerEvaluationSchemaParams) error {
	_, err := q.db.Exec(ctx, updateCoursePhaseConfigPeerEvaluationSchema, arg.CoursePhaseID, arg.PeerEvaluationSchema)
	return err
}

const updateCoursePhaseConfigResultsReleased = `-- name: UpdateCoursePhaseConfigResultsReleased :exec
UPDATE course_phase_config
SET results_released = $2
WHERE course_phase_id = $1
`

type UpdateCoursePhaseConfigResultsReleasedParams struct {
	CoursePhaseID   uuid.UUID `json:"course_phase_id"`
	ResultsReleased bool      `json:"results_released"`
}

func (q *Queries) UpdateCoursePhaseConfigResultsReleased(ctx context.Context, arg UpdateCoursePhaseConfigResultsReleasedParams) error {
	_, err := q.db.Exec(ctx, updateCoursePhaseConfigResultsReleased, arg.CoursePhaseID, arg.ResultsReleased)
	return err
}

const updateCoursePhaseConfigSelfEvaluationSchema = `-- name: UpdateCoursePhaseConfigSelfEvaluationSchema :exec
UPDATE course_phase_config
SET self_evaluation_schema = $2
WHERE course_phase_id = $1
`

type UpdateCoursePhaseConfigSelfEvaluationSchemaParams struct {
	CoursePhaseID        uuid.UUID `json:"course_phase_id"`
	SelfEvaluationSchema uuid.UUID `json:"self_evaluation_schema"`
}

func (q *Queries) UpdateCoursePhaseConfigSelfEvaluationSchema(ctx context.Context, arg UpdateCoursePhaseConfigSelfEvaluationSchemaParams) error {
	_, err := q.db.Exec(ctx, updateCoursePhaseConfigSelfEvaluationSchema, arg.CoursePhaseID, arg.SelfEvaluationSchema)
	return err
}

const updateCoursePhaseConfigTutorEvaluationSchema = `-- name: UpdateCoursePhaseConfigTutorEvaluationSchema :exec
UPDATE course_phase_config
SET tutor_evaluation_schema = $2
WHERE course_phase_id = $1
`

type UpdateCoursePhaseConfigTutorEvaluationSchemaParams struct {
	CoursePhaseID         uuid.UUID `json:"course_phase_id"`
	TutorEvaluationSchema uuid.UUID `json:"tutor_evaluation_schema"`
}

func (q *Queries) UpdateCoursePhaseConfigTutorEvaluationSchema(ctx context.Context, arg UpdateCoursePhaseConfigTutorEvaluationSchemaParams) error {
	_, err := q.db.Exec(ctx, updateCoursePhaseConfigTutorEvaluationSchema, arg.CoursePhaseID, arg.TutorEvaluationSchema)
	return err
}
