// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: independent_assessment.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createOrUpdateIndependentAssessment = `-- name: CreateOrUpdateIndependentAssessment :exec
INSERT INTO independent_assessment (course_participation_id,
                                    course_phase_id,
                                    competency_id,
                                    score_level,
                                    author,
                                    author_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (course_participation_id, course_phase_id, competency_id, author_id)
    DO UPDATE
    SET score_level = EXCLUDED.score_level,
        assessed_at = CURRENT_TIMESTAMP,
        author      = EXCLUDED.author
`

type CreateOrUpdateIndependentAssessmentParams struct {
	CourseParticipationID uuid.UUID  `json:"course_participation_id"`
	CoursePhaseID         uuid.UUID  `json:"course_phase_id"`
	CompetencyID          uuid.UUID  `json:"competency_id"`
	ScoreLevel            ScoreLevel `json:"score_level"`
	Author                string     `json:"author"`
	AuthorID              string     `json:"author_id"`
}

func (q *Queries) CreateOrUpdateIndependentAssessment(ctx context.Context, arg CreateOrUpdateIndependentAssessmentParams) error {
	_, err := q.db.Exec(ctx, createOrUpdateIndependentAssessment,
		arg.CourseParticipationID,
		arg.CoursePhaseID,
		arg.CompetencyID,
		arg.ScoreLevel,
		arg.Author,
		arg.AuthorID,
	)
	return err
}

const listIndependentAssessmentsByStudentInPhase = `-- name: ListIndependentAssessmentsByStudentInPhase :many
SELECT id, course_participation_id, course_phase_id, competency_id, score_level, author, author_id, assessed_at
FROM independent_assessment
WHERE course_participation_id = $1
  AND course_phase_id = $2
`

type ListIndependentAssessmentsByStudentInPhaseParams struct {
	CourseParticipationID uuid.UUID `json:"course_participation_id"`
	CoursePhaseID         uuid.UUID `json:"course_phase_id"`
}

func (q *Queries) ListIndependentAssessmentsByStudentInPhase(ctx context.Context, arg ListIndependentAssessmentsByStudentInPhaseParams) ([]IndependentAssessment, error) {
	rows, err := q.db.Query(ctx, listIndependentAssessmentsByStudentInPhase, arg.CourseParticipationID, arg.CoursePhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IndependentAssessment
	for rows.Next() {
		var i IndependentAssessment
		if err := rows.Scan(
			&i.ID,
			&i.CourseParticipationID,
			&i.CoursePhaseID,
			&i.CompetencyID,
			&i.ScoreLevel,
			&i.Author,
			&i.AuthorID,
			&i.AssessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
