// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AssessmentType string

const (
	AssessmentTypeSelf       AssessmentType = "self"
	AssessmentTypePeer       AssessmentType = "peer"
	AssessmentTypeTutor      AssessmentType = "tutor"
	AssessmentTypeAssessment AssessmentType = "assessment"
)

func (e *AssessmentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssessmentType(s)
	case string:
		*e = AssessmentType(s)
	default:
		return fmt.Errorf("unsupported scan type for AssessmentType: %T", src)
	}
	return nil
}

type NullAssessmentType struct {
	AssessmentType AssessmentType `json:"assessment_type"`
	Valid          bool           `json:"valid"` // Valid is true if AssessmentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssessmentType) Scan(value interface{}) error {
	if value == nil {
		ns.AssessmentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssessmentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssessmentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssessmentType), nil
}

type FeedbackType string

const (
	FeedbackTypePositive FeedbackType = "positive"
	FeedbackTypeNegative FeedbackType = "negative"
)

func (e *FeedbackType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FeedbackType(s)
	case string:
		*e = FeedbackType(s)
	default:
		return fmt.Errorf("unsupported scan type for FeedbackType: %T", src)
	}
	return nil
}

type NullFeedbackType struct {
	FeedbackType FeedbackType `json:"feedback_type"`
	Valid        bool         `json:"valid"` // Valid is true if FeedbackType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFeedbackType) Scan(value interface{}) error {
	if value == nil {
		ns.FeedbackType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FeedbackType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFeedbackType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FeedbackType), nil
}

type ScoreLevel string

const (
	ScoreLevelVeryBad  ScoreLevel = "very_bad"
	ScoreLevelBad      ScoreLevel = "bad"
	ScoreLevelOk       ScoreLevel = "ok"
	ScoreLevelGood     ScoreLevel = "good"
	ScoreLevelVeryGood ScoreLevel = "very_good"
)

func (e *ScoreLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScoreLevel(s)
	case string:
		*e = ScoreLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for ScoreLevel: %T", src)
	}
	return nil
}

type NullScoreLevel struct {
	ScoreLevel ScoreLevel `json:"score_level"`
	Valid      bool       `json:"valid"` // Valid is true if ScoreLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScoreLevel) Scan(value interface{}) error {
	if value == nil {
		ns.ScoreLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScoreLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScoreLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScoreLevel), nil
}

type ActionItem struct {
	ID                    uuid.UUID        `json:"id"`
	CoursePhaseID         uuid.UUID        `json:"course_phase_id"`
	CourseParticipationID uuid.UUID        `json:"course_participation_id"`
	Action                string           `json:"action"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	Author                string           `json:"author"`
}

type Assessment struct {
	ID                    uuid.UUID          `json:"id"`
	CourseParticipationID uuid.UUID          `json:"course_participation_id"`
	CoursePhaseID         uuid.UUID          `json:"course_phase_id"`
	CompetencyID          uuid.UUID          `json:"competency_id"`
	Comment               pgtype.Text        `json:"comment"`
	AssessedAt            pgtype.Timestamptz `json:"assessed_at"`
	Author                string             `json:"author"`
	ScoreLevel            ScoreLevel         `json:"score_level"`
	Examples              string             `json:"examples"`
}

type AssessmentCompletion struct {
	CourseParticipationID uuid.UUID          `json:"course_participation_id"`
	CoursePhaseID         uuid.UUID          `json:"course_phase_id"`
	CompletedAt           pgtype.Timestamptz `json:"completed_at"`
	Author                string             `json:"author"`
	Comment               string             `json:"comment"`
	GradeSuggestion       pgtype.Numeric     `json:"grade_suggestion"`
	Completed             bool               `json:"completed"`
}

type AssessmentSchema struct {
	ID            uuid.UUID        `json:"id"`
	Name          string           `json:"name"`
	Description   pgtype.Text      `json:"description"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	SourcePhaseID pgtype.UUID      `json:"source_phase_id"`
}

type Category struct {
	ID                 uuid.UUID   `json:"id"`
	Name               string      `json:"name"`
	Description        pgtype.Text `json:"description"`
	Weight             int32       `json:"weight"`
	ShortName          pgtype.Text `json:"short_name"`
	AssessmentSchemaID uuid.UUID   `json:"assessment_schema_id"`
}

type CategoryCoursePhase struct {
	CategoryID    uuid.UUID `json:"category_id"`
	CoursePhaseID uuid.UUID `json:"course_phase_id"`
}

type Competency struct {
	ID                  uuid.UUID   `json:"id"`
	CategoryID          uuid.UUID   `json:"category_id"`
	Name                string      `json:"name"`
	Description         pgtype.Text `json:"description"`
	Weight              int32       `json:"weight"`
	ShortName           pgtype.Text `json:"short_name"`
	DescriptionVeryBad  string      `json:"description_very_bad"`
	DescriptionBad      string      `json:"description_bad"`
	DescriptionOk       string      `json:"description_ok"`
	DescriptionGood     string      `json:"description_good"`
	DescriptionVeryGood string      `json:"description_very_good"`
}

type CompetencyMap struct {
	FromCompetencyID uuid.UUID `json:"from_competency_id"`
	ToCompetencyID   uuid.UUID `json:"to_competency_id"`
}

type CompletedScoreLevel struct {
	CoursePhaseID         uuid.UUID `json:"course_phase_id"`
	CourseParticipationID uuid.UUID `json:"course_participation_id"`
	ScoreLevel            string    `json:"score_level"`
}

type CoursePhaseConfig struct {
	AssessmentSchemaID       uuid.UUID          `json:"assessment_schema_id"`
	CoursePhaseID            uuid.UUID          `json:"course_phase_id"`
	Deadline                 pgtype.Timestamptz `json:"deadline"`
	SelfEvaluationEnabled    bool               `json:"self_evaluation_enabled"`
	SelfEvaluationSchema     uuid.UUID          `json:"self_evaluation_schema"`
	SelfEvaluationDeadline   pgtype.Timestamptz `json:"self_evaluation_deadline"`
	PeerEvaluationEnabled    bool               `json:"peer_evaluation_enabled"`
	PeerEvaluationSchema     uuid.UUID          `json:"peer_evaluation_schema"`
	PeerEvaluationDeadline   pgtype.Timestamptz `json:"peer_evaluation_deadline"`
	Start                    pgtype.Timestamptz `json:"start"`
	SelfEvaluationStart      pgtype.Timestamptz `json:"self_evaluation_start"`
	PeerEvaluationStart      pgtype.Timestamptz `json:"peer_evaluation_start"`
	TutorEvaluationEnabled   bool               `json:"tutor_evaluation_enabled"`
	TutorEvaluationStart     pgtype.Timestamptz `json:"tutor_evaluation_start"`
	TutorEvaluationDeadline  pgtype.Timestamptz `json:"tutor_evaluation_deadline"`
	TutorEvaluationSchema    uuid.UUID          `json:"tutor_evaluation_schema"`
	EvaluationResultsVisible bool               `json:"evaluation_results_visible"`
	GradeSuggestionVisible   bool               `json:"grade_suggestion_visible"`
	ActionItemsVisible       bool               `json:"action_items_visible"`
	ResultsReleased          bool               `json:"results_released"`
	GradingSheetVisible      bool               `json:"grading_sheet_visible"`
}

type Evaluation struct {
	ID                          uuid.UUID          `json:"id"`
	CourseParticipationID       uuid.UUID          `json:"course_participation_id"`
	CoursePhaseID               uuid.UUID          `json:"course_phase_id"`
	CompetencyID                uuid.UUID          `json:"competency_id"`
	ScoreLevel                  ScoreLevel         `json:"score_level"`
	AuthorCourseParticipationID uuid.UUID          `json:"author_course_participation_id"`
	EvaluatedAt                 pgtype.Timestamptz `json:"evaluated_at"`
	Type                        AssessmentType     `json:"type"`
}

type EvaluationCompletion struct {
	ID                          uuid.UUID          `json:"id"`
	CourseParticipationID       uuid.UUID          `json:"course_participation_id"`
	CoursePhaseID               uuid.UUID          `json:"course_phase_id"`
	AuthorCourseParticipationID uuid.UUID          `json:"author_course_participation_id"`
	CompletedAt                 pgtype.Timestamptz `json:"completed_at"`
	Completed                   bool               `json:"completed"`
	Type                        AssessmentType     `json:"type"`
}

type FeedbackItem struct {
	ID                          uuid.UUID          `json:"id"`
	FeedbackType                FeedbackType       `json:"feedback_type"`
	FeedbackText                string             `json:"feedback_text"`
	CourseParticipationID       uuid.UUID          `json:"course_participation_id"`
	CoursePhaseID               uuid.UUID          `json:"course_phase_id"`
	AuthorCourseParticipationID uuid.UUID          `json:"author_course_participation_id"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
	Type                        AssessmentType     `json:"type"`
}

type WeightedParticipantScore struct {
	CoursePhaseID         uuid.UUID      `json:"course_phase_id"`
	CourseParticipationID uuid.UUID      `json:"course_participation_id"`
	ScoreNumeric          pgtype.Numeric `json:"score_numeric"`
	ScoreLevel            string         `json:"score_level"`
}
