// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: privacy.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteActionItemsByCourseParticipationIDs = `-- name: DeleteActionItemsByCourseParticipationIDs :exec
DELETE FROM action_item
WHERE course_participation_id = ANY($1::uuid[])
`

func (q *Queries) DeleteActionItemsByCourseParticipationIDs(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteActionItemsByCourseParticipationIDs, dollar_1)
	return err
}

const deleteAssessmentCompletionsByCourseParticipationIDs = `-- name: DeleteAssessmentCompletionsByCourseParticipationIDs :exec
DELETE FROM assessment_completion
WHERE course_participation_id = ANY($1::uuid[])
`

func (q *Queries) DeleteAssessmentCompletionsByCourseParticipationIDs(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAssessmentCompletionsByCourseParticipationIDs, dollar_1)
	return err
}

const deleteAssessmentsByCourseParticipationIDs = `-- name: DeleteAssessmentsByCourseParticipationIDs :exec
DELETE FROM assessment
WHERE course_participation_id = ANY($1::uuid[])
`

func (q *Queries) DeleteAssessmentsByCourseParticipationIDs(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAssessmentsByCourseParticipationIDs, dollar_1)
	return err
}

const deleteCategoryAssessmentsByCourseParticipationIDs = `-- name: DeleteCategoryAssessmentsByCourseParticipationIDs :exec
DELETE FROM category_assessment
WHERE course_participation_id = ANY($1::uuid[])
`

func (q *Queries) DeleteCategoryAssessmentsByCourseParticipationIDs(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategoryAssessmentsByCourseParticipationIDs, dollar_1)
	return err
}

const deleteEvaluationCompletionsByRecipientOrAuthorIDs = `-- name: DeleteEvaluationCompletionsByRecipientOrAuthorIDs :exec
DELETE FROM evaluation_completion
WHERE course_participation_id = ANY($1::uuid[])
   OR author_course_participation_id = ANY($1::uuid[])
`

func (q *Queries) DeleteEvaluationCompletionsByRecipientOrAuthorIDs(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvaluationCompletionsByRecipientOrAuthorIDs, dollar_1)
	return err
}

const deleteEvaluationsByRecipientOrAuthorIDs = `-- name: DeleteEvaluationsByRecipientOrAuthorIDs :exec
DELETE FROM evaluation
WHERE course_participation_id = ANY($1::uuid[])
   OR author_course_participation_id = ANY($1::uuid[])
`

func (q *Queries) DeleteEvaluationsByRecipientOrAuthorIDs(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvaluationsByRecipientOrAuthorIDs, dollar_1)
	return err
}

const deleteFeedbackItemsByRecipientOrAuthorIDs = `-- name: DeleteFeedbackItemsByRecipientOrAuthorIDs :exec
DELETE FROM feedback_items
WHERE course_participation_id = ANY($1::uuid[])
   OR author_course_participation_id = ANY($1::uuid[])
`

func (q *Queries) DeleteFeedbackItemsByRecipientOrAuthorIDs(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFeedbackItemsByRecipientOrAuthorIDs, dollar_1)
	return err
}

const getAllActionItemsByCourseParticipationIDs = `-- name: GetAllActionItemsByCourseParticipationIDs :many
SELECT id, course_phase_id, course_participation_id, action, created_at
FROM action_item
WHERE course_participation_id = ANY($1::uuid[])
`

type GetAllActionItemsByCourseParticipationIDsRow struct {
	ID                    uuid.UUID        `json:"id"`
	CoursePhaseID         uuid.UUID        `json:"course_phase_id"`
	CourseParticipationID uuid.UUID        `json:"course_participation_id"`
	Action                string           `json:"action"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetAllActionItemsByCourseParticipationIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetAllActionItemsByCourseParticipationIDsRow, error) {
	rows, err := q.db.Query(ctx, getAllActionItemsByCourseParticipationIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllActionItemsByCourseParticipationIDsRow
	for rows.Next() {
		var i GetAllActionItemsByCourseParticipationIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.CoursePhaseID,
			&i.CourseParticipationID,
			&i.Action,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllAssessmentCompletionsByCourseParticipationIDs = `-- name: GetAllAssessmentCompletionsByCourseParticipationIDs :many
SELECT course_participation_id, course_phase_id, completed_at, comment, grade_suggestion, completed
FROM assessment_completion
WHERE course_participation_id = ANY($1::uuid[])
`

type GetAllAssessmentCompletionsByCourseParticipationIDsRow struct {
	CourseParticipationID uuid.UUID          `json:"course_participation_id"`
	CoursePhaseID         uuid.UUID          `json:"course_phase_id"`
	CompletedAt           pgtype.Timestamptz `json:"completed_at"`
	Comment               string             `json:"comment"`
	GradeSuggestion       pgtype.Numeric     `json:"grade_suggestion"`
	Completed             bool               `json:"completed"`
}

func (q *Queries) GetAllAssessmentCompletionsByCourseParticipationIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetAllAssessmentCompletionsByCourseParticipationIDsRow, error) {
	rows, err := q.db.Query(ctx, getAllAssessmentCompletionsByCourseParticipationIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllAssessmentCompletionsByCourseParticipationIDsRow
	for rows.Next() {
		var i GetAllAssessmentCompletionsByCourseParticipationIDsRow
		if err := rows.Scan(
			&i.CourseParticipationID,
			&i.CoursePhaseID,
			&i.CompletedAt,
			&i.Comment,
			&i.GradeSuggestion,
			&i.Completed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllAssessmentsByCourseParticipationIDs = `-- name: GetAllAssessmentsByCourseParticipationIDs :many

SELECT id, course_participation_id, course_phase_id, competency_id, assessed_at, score_level
FROM assessment
WHERE course_participation_id = ANY($1::uuid[])
`

type GetAllAssessmentsByCourseParticipationIDsRow struct {
	ID                    uuid.UUID          `json:"id"`
	CourseParticipationID uuid.UUID          `json:"course_participation_id"`
	CoursePhaseID         uuid.UUID          `json:"course_phase_id"`
	CompetencyID          uuid.UUID          `json:"competency_id"`
	AssessedAt            pgtype.Timestamptz `json:"assessed_at"`
	ScoreLevel            ScoreLevel         `json:"score_level"`
}

// Queries for gdpr export and deletion.
func (q *Queries) GetAllAssessmentsByCourseParticipationIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetAllAssessmentsByCourseParticipationIDsRow, error) {
	rows, err := q.db.Query(ctx, getAllAssessmentsByCourseParticipationIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllAssessmentsByCourseParticipationIDsRow
	for rows.Next() {
		var i GetAllAssessmentsByCourseParticipationIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseParticipationID,
			&i.CoursePhaseID,
			&i.CompetencyID,
			&i.AssessedAt,
			&i.ScoreLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCategoryAssessmentsByCourseParticipationIDs = `-- name: GetAllCategoryAssessmentsByCourseParticipationIDs :many
SELECT id,
       category_id,
       course_phase_id,
       course_participation_id,
       -- This regex simply removes "(by <author>)" in the "## ..." heading; It was added in an older migration and we don't want to leak the author's name.
       COALESCE(regexp_replace(comment, '^(##[^\n]*?)\s*\(by[^)\n]*\)\s*$', '\1', 'ng'), '')::text AS comment,
       created_at,
       updated_at
FROM category_assessment
WHERE course_participation_id = ANY($1::uuid[])
`

type GetAllCategoryAssessmentsByCourseParticipationIDsRow struct {
	ID                    uuid.UUID          `json:"id"`
	CategoryID            uuid.UUID          `json:"category_id"`
	CoursePhaseID         uuid.UUID          `json:"course_phase_id"`
	CourseParticipationID uuid.UUID          `json:"course_participation_id"`
	Comment               string             `json:"comment"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAllCategoryAssessmentsByCourseParticipationIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetAllCategoryAssessmentsByCourseParticipationIDsRow, error) {
	rows, err := q.db.Query(ctx, getAllCategoryAssessmentsByCourseParticipationIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllCategoryAssessmentsByCourseParticipationIDsRow
	for rows.Next() {
		var i GetAllCategoryAssessmentsByCourseParticipationIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.CoursePhaseID,
			&i.CourseParticipationID,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllEvaluationCompletionsByCourseParticipationIDs = `-- name: GetAllEvaluationCompletionsByCourseParticipationIDs :many
SELECT id, course_participation_id, course_phase_id, completed_at, completed, type
FROM evaluation_completion
WHERE course_participation_id = ANY($1::uuid[])
`

type GetAllEvaluationCompletionsByCourseParticipationIDsRow struct {
	ID                    uuid.UUID          `json:"id"`
	CourseParticipationID uuid.UUID          `json:"course_participation_id"`
	CoursePhaseID         uuid.UUID          `json:"course_phase_id"`
	CompletedAt           pgtype.Timestamptz `json:"completed_at"`
	Completed             bool               `json:"completed"`
	Type                  AssessmentType     `json:"type"`
}

func (q *Queries) GetAllEvaluationCompletionsByCourseParticipationIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetAllEvaluationCompletionsByCourseParticipationIDsRow, error) {
	rows, err := q.db.Query(ctx, getAllEvaluationCompletionsByCourseParticipationIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllEvaluationCompletionsByCourseParticipationIDsRow
	for rows.Next() {
		var i GetAllEvaluationCompletionsByCourseParticipationIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseParticipationID,
			&i.CoursePhaseID,
			&i.CompletedAt,
			&i.Completed,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllEvaluationsByCourseParticipationIDs = `-- name: GetAllEvaluationsByCourseParticipationIDs :many
SELECT id, course_participation_id, course_phase_id, competency_id, score_level, evaluated_at, type
FROM evaluation
WHERE course_participation_id = ANY($1::uuid[])
`

type GetAllEvaluationsByCourseParticipationIDsRow struct {
	ID                    uuid.UUID          `json:"id"`
	CourseParticipationID uuid.UUID          `json:"course_participation_id"`
	CoursePhaseID         uuid.UUID          `json:"course_phase_id"`
	CompetencyID          uuid.UUID          `json:"competency_id"`
	ScoreLevel            ScoreLevel         `json:"score_level"`
	EvaluatedAt           pgtype.Timestamptz `json:"evaluated_at"`
	Type                  AssessmentType     `json:"type"`
}

func (q *Queries) GetAllEvaluationsByCourseParticipationIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetAllEvaluationsByCourseParticipationIDsRow, error) {
	rows, err := q.db.Query(ctx, getAllEvaluationsByCourseParticipationIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllEvaluationsByCourseParticipationIDsRow
	for rows.Next() {
		var i GetAllEvaluationsByCourseParticipationIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseParticipationID,
			&i.CoursePhaseID,
			&i.CompetencyID,
			&i.ScoreLevel,
			&i.EvaluatedAt,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllFeedbackItemsByCourseParticipationIDs = `-- name: GetAllFeedbackItemsByCourseParticipationIDs :many
SELECT id, feedback_type, feedback_text, course_participation_id, course_phase_id, created_at, type
FROM feedback_items
WHERE course_participation_id = ANY($1::uuid[])
`

type GetAllFeedbackItemsByCourseParticipationIDsRow struct {
	ID                    uuid.UUID          `json:"id"`
	FeedbackType          FeedbackType       `json:"feedback_type"`
	FeedbackText          string             `json:"feedback_text"`
	CourseParticipationID uuid.UUID          `json:"course_participation_id"`
	CoursePhaseID         uuid.UUID          `json:"course_phase_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	Type                  AssessmentType     `json:"type"`
}

func (q *Queries) GetAllFeedbackItemsByCourseParticipationIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetAllFeedbackItemsByCourseParticipationIDsRow, error) {
	rows, err := q.db.Query(ctx, getAllFeedbackItemsByCourseParticipationIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllFeedbackItemsByCourseParticipationIDsRow
	for rows.Next() {
		var i GetAllFeedbackItemsByCourseParticipationIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedbackType,
			&i.FeedbackText,
			&i.CourseParticipationID,
			&i.CoursePhaseID,
			&i.CreatedAt,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
