// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: announcement.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAnnouncement = `-- name: CreateAnnouncement :one
INSERT INTO announcement (
    severity, title, message, link_url, link_label, starts_at, expires_at, enabled
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, severity, title, message, link_url, link_label, starts_at, expires_at, enabled, created_at, updated_at
`

type CreateAnnouncementParams struct {
	Severity  AnnouncementSeverity `json:"severity"`
	Title     string               `json:"title"`
	Message   string               `json:"message"`
	LinkUrl   string               `json:"link_url"`
	LinkLabel string               `json:"link_label"`
	StartsAt  pgtype.Timestamptz   `json:"starts_at"`
	ExpiresAt pgtype.Timestamptz   `json:"expires_at"`
	Enabled   bool                 `json:"enabled"`
}

func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, createAnnouncement,
		arg.Severity,
		arg.Title,
		arg.Message,
		arg.LinkUrl,
		arg.LinkLabel,
		arg.StartsAt,
		arg.ExpiresAt,
		arg.Enabled,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Severity,
		&i.Title,
		&i.Message,
		&i.LinkUrl,
		&i.LinkLabel,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAnnouncement = `-- name: DeleteAnnouncement :execrows
DELETE FROM announcement WHERE id = $1
`

func (q *Queries) DeleteAnnouncement(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAnnouncement, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActiveAnnouncements = `-- name: ListActiveAnnouncements :many
SELECT id, severity, title, message, link_url, link_label, starts_at, expires_at, enabled, created_at, updated_at FROM announcement
WHERE enabled
  AND (starts_at IS NULL OR starts_at <= now())
  AND (expires_at IS NULL OR expires_at > now())
ORDER BY severity DESC, COALESCE(starts_at, created_at) ASC
`

func (q *Queries) ListActiveAnnouncements(ctx context.Context) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, listActiveAnnouncements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Announcement
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.Severity,
			&i.Title,
			&i.Message,
			&i.LinkUrl,
			&i.LinkLabel,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnnouncements = `-- name: ListAnnouncements :many
SELECT id, severity, title, message, link_url, link_label, starts_at, expires_at, enabled, created_at, updated_at FROM announcement
WHERE $1::boolean OR expires_at IS NULL OR expires_at > now()
ORDER BY created_at DESC
`

func (q *Queries) ListAnnouncements(ctx context.Context, includeExpired bool) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, listAnnouncements, includeExpired)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Announcement
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.Severity,
			&i.Title,
			&i.Message,
			&i.LinkUrl,
			&i.LinkLabel,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnnouncement = `-- name: UpdateAnnouncement :one
UPDATE announcement
SET severity = $2,
    title = $3,
    message = $4,
    link_url = $5,
    link_label = $6,
    starts_at = $7,
    expires_at = $8,
    enabled = $9,
    updated_at = now()
WHERE id = $1
RETURNING id, severity, title, message, link_url, link_label, starts_at, expires_at, enabled, created_at, updated_at
`

type UpdateAnnouncementParams struct {
	ID        uuid.UUID            `json:"id"`
	Severity  AnnouncementSeverity `json:"severity"`
	Title     string               `json:"title"`
	Message   string               `json:"message"`
	LinkUrl   string               `json:"link_url"`
	LinkLabel string               `json:"link_label"`
	StartsAt  pgtype.Timestamptz   `json:"starts_at"`
	ExpiresAt pgtype.Timestamptz   `json:"expires_at"`
	Enabled   bool                 `json:"enabled"`
}

func (q *Queries) UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, updateAnnouncement,
		arg.ID,
		arg.Severity,
		arg.Title,
		arg.Message,
		arg.LinkUrl,
		arg.LinkLabel,
		arg.StartsAt,
		arg.ExpiresAt,
		arg.Enabled,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Severity,
		&i.Title,
		&i.Message,
		&i.LinkUrl,
		&i.LinkLabel,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
