// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditEntry = `-- name: CreateAuditEntry :one
INSERT INTO audit_log (
  actor_id, actor_name, actor_email, actor_roles, actor_role,
  action, action_key, outcome,
  entity_type, entity_id, entity_name,
  course_id, course_phase_id, source_service,
  http_method, http_path, http_status, metadata
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
)
RETURNING id, created_at, actor_id, actor_name, actor_email, actor_roles, actor_role, action, action_key, outcome, entity_type, entity_id, entity_name, course_id, course_phase_id, source_service, http_method, http_path, http_status, metadata
`

type CreateAuditEntryParams struct {
	ActorID       pgtype.UUID `json:"actor_id"`
	ActorName     string      `json:"actor_name"`
	ActorEmail    string      `json:"actor_email"`
	ActorRoles    []string    `json:"actor_roles"`
	ActorRole     string      `json:"actor_role"`
	Action        string      `json:"action"`
	ActionKey     string      `json:"action_key"`
	Outcome       string      `json:"outcome"`
	EntityType    pgtype.Text `json:"entity_type"`
	EntityID      pgtype.Text `json:"entity_id"`
	EntityName    pgtype.Text `json:"entity_name"`
	CourseID      pgtype.UUID `json:"course_id"`
	CoursePhaseID pgtype.UUID `json:"course_phase_id"`
	SourceService string      `json:"source_service"`
	HttpMethod    pgtype.Text `json:"http_method"`
	HttpPath      pgtype.Text `json:"http_path"`
	HttpStatus    pgtype.Int4 `json:"http_status"`
	Metadata      []byte      `json:"metadata"`
}

func (q *Queries) CreateAuditEntry(ctx context.Context, arg CreateAuditEntryParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditEntry,
		arg.ActorID,
		arg.ActorName,
		arg.ActorEmail,
		arg.ActorRoles,
		arg.ActorRole,
		arg.Action,
		arg.ActionKey,
		arg.Outcome,
		arg.EntityType,
		arg.EntityID,
		arg.EntityName,
		arg.CourseID,
		arg.CoursePhaseID,
		arg.SourceService,
		arg.HttpMethod,
		arg.HttpPath,
		arg.HttpStatus,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ActorID,
		&i.ActorName,
		&i.ActorEmail,
		&i.ActorRoles,
		&i.ActorRole,
		&i.Action,
		&i.ActionKey,
		&i.Outcome,
		&i.EntityType,
		&i.EntityID,
		&i.EntityName,
		&i.CourseID,
		&i.CoursePhaseID,
		&i.SourceService,
		&i.HttpMethod,
		&i.HttpPath,
		&i.HttpStatus,
		&i.Metadata,
	)
	return i, err
}

const deleteExpiredAuditEntries = `-- name: DeleteExpiredAuditEntries :exec
DELETE FROM audit_log WHERE created_at < $1
`

func (q *Queries) DeleteExpiredAuditEntries(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteExpiredAuditEntries, createdAt)
	return err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, created_at, actor_id, actor_name, actor_email, actor_roles, actor_role, action, action_key, outcome, entity_type, entity_id, entity_name, course_id, course_phase_id, source_service, http_method, http_path, http_status, metadata FROM audit_log
WHERE ($1::uuid IS NULL OR course_id = $1)
  AND ($2::text IS NULL OR actor_role = $2)
  AND ($3::text IS NULL OR outcome = $3)
  AND ($4::text IS NULL OR action_key = $4)
  AND ($5::text IS NULL OR entity_type = $5)
  AND ($6::text IS NULL OR source_service = $6)
  AND ($7::uuid IS NULL OR course_phase_id = $7)
  AND ($8::timestamptz IS NULL OR created_at >= $8)
  AND ($9::timestamptz IS NULL OR created_at <= $9)
  AND ($10::text IS NULL OR (
        actor_name ILIKE '%' || $10 || '%' OR
        actor_email ILIKE '%' || $10 || '%' OR
        action ILIKE '%' || $10 || '%' OR
        entity_name ILIKE '%' || $10 || '%' OR
        entity_id ILIKE '%' || $10 || '%'))
  AND ($11::timestamptz IS NULL OR
        created_at < $11 OR
        (created_at = $11 AND id < $12))
ORDER BY created_at DESC, id DESC
LIMIT $13
`

type ListAuditLogParams struct {
	CourseID      pgtype.UUID        `json:"course_id"`
	ActorRole     pgtype.Text        `json:"actor_role"`
	Outcome       pgtype.Text        `json:"outcome"`
	ActionKey     pgtype.Text        `json:"action_key"`
	EntityType    pgtype.Text        `json:"entity_type"`
	SourceService pgtype.Text        `json:"source_service"`
	CoursePhaseID pgtype.UUID        `json:"course_phase_id"`
	FromTime      pgtype.Timestamptz `json:"from_time"`
	ToTime        pgtype.Timestamptz `json:"to_time"`
	Search        pgtype.Text        `json:"search"`
	CursorTs      pgtype.Timestamptz `json:"cursor_ts"`
	CursorID      pgtype.UUID        `json:"cursor_id"`
	PageLimit     int32              `json:"page_limit"`
}

func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLog,
		arg.CourseID,
		arg.ActorRole,
		arg.Outcome,
		arg.ActionKey,
		arg.EntityType,
		arg.SourceService,
		arg.CoursePhaseID,
		arg.FromTime,
		arg.ToTime,
		arg.Search,
		arg.CursorTs,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ActorID,
			&i.ActorName,
			&i.ActorEmail,
			&i.ActorRoles,
			&i.ActorRole,
			&i.Action,
			&i.ActionKey,
			&i.Outcome,
			&i.EntityType,
			&i.EntityID,
			&i.EntityName,
			&i.CourseID,
			&i.CoursePhaseID,
			&i.SourceService,
			&i.HttpMethod,
			&i.HttpPath,
			&i.HttpStatus,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
