// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: course_phase.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCoursePhase = `-- name: CreateCoursePhase :one
INSERT INTO course_phase (id, course_id, name, is_initial_phase, restricted_data, student_readable_data, course_phase_type_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, course_id, name, restricted_data, is_initial_phase, course_phase_type_id, student_readable_data
`

type CreateCoursePhaseParams struct {
	ID                  uuid.UUID   `json:"id"`
	CourseID            uuid.UUID   `json:"course_id"`
	Name                pgtype.Text `json:"name"`
	IsInitialPhase      bool        `json:"is_initial_phase"`
	RestrictedData      []byte      `json:"restricted_data"`
	StudentReadableData []byte      `json:"student_readable_data"`
	CoursePhaseTypeID   uuid.UUID   `json:"course_phase_type_id"`
}

func (q *Queries) CreateCoursePhase(ctx context.Context, arg CreateCoursePhaseParams) (CoursePhase, error) {
	row := q.db.QueryRow(ctx, createCoursePhase,
		arg.ID,
		arg.CourseID,
		arg.Name,
		arg.IsInitialPhase,
		arg.RestrictedData,
		arg.StudentReadableData,
		arg.CoursePhaseTypeID,
	)
	var i CoursePhase
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Name,
		&i.RestrictedData,
		&i.IsInitialPhase,
		&i.CoursePhaseTypeID,
		&i.StudentReadableData,
	)
	return i, err
}

const deleteCoursePhase = `-- name: DeleteCoursePhase :exec
DELETE FROM course_phase
WHERE id = $1
`

func (q *Queries) DeleteCoursePhase(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCoursePhase, id)
	return err
}

const getAllCoursePhaseForCourse = `-- name: GetAllCoursePhaseForCourse :many
SELECT cp.id, cp.course_id, cp.name, cp.restricted_data, cp.is_initial_phase, cp.course_phase_type_id, cp.student_readable_data, cpt.name AS course_phase_type_name
FROM course_phase cp
INNER JOIN course_phase_type cpt ON cp.course_phase_type_id = cpt.id
WHERE cp.course_id = $1
`

type GetAllCoursePhaseForCourseRow struct {
	ID                  uuid.UUID   `json:"id"`
	CourseID            uuid.UUID   `json:"course_id"`
	Name                pgtype.Text `json:"name"`
	RestrictedData      []byte      `json:"restricted_data"`
	IsInitialPhase      bool        `json:"is_initial_phase"`
	CoursePhaseTypeID   uuid.UUID   `json:"course_phase_type_id"`
	StudentReadableData []byte      `json:"student_readable_data"`
	CoursePhaseTypeName string      `json:"course_phase_type_name"`
}

func (q *Queries) GetAllCoursePhaseForCourse(ctx context.Context, courseID uuid.UUID) ([]GetAllCoursePhaseForCourseRow, error) {
	rows, err := q.db.Query(ctx, getAllCoursePhaseForCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllCoursePhaseForCourseRow
	for rows.Next() {
		var i GetAllCoursePhaseForCourseRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Name,
			&i.RestrictedData,
			&i.IsInitialPhase,
			&i.CoursePhaseTypeID,
			&i.StudentReadableData,
			&i.CoursePhaseTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourseIDByCoursePhaseID = `-- name: GetCourseIDByCoursePhaseID :one
SELECT course_id
FROM course_phase
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCourseIDByCoursePhaseID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getCourseIDByCoursePhaseID, id)
	var course_id uuid.UUID
	err := row.Scan(&course_id)
	return course_id, err
}

const getCoursePhase = `-- name: GetCoursePhase :one
SELECT cp.id, cp.course_id, cp.name, cp.restricted_data, cp.is_initial_phase, cp.course_phase_type_id, cp.student_readable_data, cpt.name AS course_phase_type_name
FROM course_phase cp
INNER JOIN course_phase_type cpt ON cp.course_phase_type_id = cpt.id
WHERE cp.id = $1
LIMIT 1
`

type GetCoursePhaseRow struct {
	ID                  uuid.UUID   `json:"id"`
	CourseID            uuid.UUID   `json:"course_id"`
	Name                pgtype.Text `json:"name"`
	RestrictedData      []byte      `json:"restricted_data"`
	IsInitialPhase      bool        `json:"is_initial_phase"`
	CoursePhaseTypeID   uuid.UUID   `json:"course_phase_type_id"`
	StudentReadableData []byte      `json:"student_readable_data"`
	CoursePhaseTypeName string      `json:"course_phase_type_name"`
}

func (q *Queries) GetCoursePhase(ctx context.Context, id uuid.UUID) (GetCoursePhaseRow, error) {
	row := q.db.QueryRow(ctx, getCoursePhase, id)
	var i GetCoursePhaseRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Name,
		&i.RestrictedData,
		&i.IsInitialPhase,
		&i.CoursePhaseTypeID,
		&i.StudentReadableData,
		&i.CoursePhaseTypeName,
	)
	return i, err
}

const getPrevCoursePhaseDataFromCore = `-- name: GetPrevCoursePhaseDataFromCore :one
SELECT jsonb_object_agg(sub.dto_name, sub.dto_value) AS incoming_dto_objects
FROM (
  SELECT pod.dto_name,
         COALESCE(cp.student_readable_data -> pod.dto_name,
                  cp.restricted_data -> pod.dto_name) AS dto_value
  FROM phase_data_dependency_graph pdg
  JOIN course_phase cp
    ON cp.id = pdg.from_course_phase_id
  JOIN course_phase_type_phase_provided_output_dto pod
    ON pod.id = pdg.from_course_phase_DTO_id
  WHERE pdg.to_course_phase_id = $1
    AND pod.endpoint_path = 'core'
) sub
`

func (q *Queries) GetPrevCoursePhaseDataFromCore(ctx context.Context, toCoursePhaseID uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getPrevCoursePhaseDataFromCore, toCoursePhaseID)
	var incoming_dto_objects []byte
	err := row.Scan(&incoming_dto_objects)
	return incoming_dto_objects, err
}

const getPrevCoursePhaseDataResolution = `-- name: GetPrevCoursePhaseDataResolution :many
SELECT po.dto_name, cpt.base_url, po.endpoint_path, dg.from_course_phase_id
FROM phase_data_dependency_graph dg
JOIN course_phase_type_phase_provided_output_dto po
  ON po.id = dg.from_course_phase_DTO_id
JOIN course_phase_type cpt
  ON cpt.id = po.course_phase_type_id
WHERE dg.to_course_phase_id = $1
    AND po.endpoint_path <> 'core'
`

type GetPrevCoursePhaseDataResolutionRow struct {
	DtoName           string    `json:"dto_name"`
	BaseUrl           string    `json:"base_url"`
	EndpointPath      string    `json:"endpoint_path"`
	FromCoursePhaseID uuid.UUID `json:"from_course_phase_id"`
}

func (q *Queries) GetPrevCoursePhaseDataResolution(ctx context.Context, toCoursePhaseID uuid.UUID) ([]GetPrevCoursePhaseDataResolutionRow, error) {
	rows, err := q.db.Query(ctx, getPrevCoursePhaseDataResolution, toCoursePhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPrevCoursePhaseDataResolutionRow
	for rows.Next() {
		var i GetPrevCoursePhaseDataResolutionRow
		if err := rows.Scan(
			&i.DtoName,
			&i.BaseUrl,
			&i.EndpointPath,
			&i.FromCoursePhaseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResolutionsForCoursePhase = `-- name: GetResolutionsForCoursePhase :many
SELECT po.dto_name, cpt.base_url, po.endpoint_path, mdg.from_course_phase_id
FROM participation_data_dependency_graph mdg
JOIN course_phase_type_participation_provided_output_dto po 
  ON po.id = mdg.from_course_phase_DTO_id
JOIN course_phase_type cpt
  ON cpt.id = po.course_phase_type_id
WHERE mdg.to_course_phase_id = $1
    AND po.endpoint_path <> 'core'
`

type GetResolutionsForCoursePhaseRow struct {
	DtoName           string    `json:"dto_name"`
	BaseUrl           string    `json:"base_url"`
	EndpointPath      string    `json:"endpoint_path"`
	FromCoursePhaseID uuid.UUID `json:"from_course_phase_id"`
}

func (q *Queries) GetResolutionsForCoursePhase(ctx context.Context, toCoursePhaseID uuid.UUID) ([]GetResolutionsForCoursePhaseRow, error) {
	rows, err := q.db.Query(ctx, getResolutionsForCoursePhase, toCoursePhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResolutionsForCoursePhaseRow
	for rows.Next() {
		var i GetResolutionsForCoursePhaseRow
		if err := rows.Scan(
			&i.DtoName,
			&i.BaseUrl,
			&i.EndpointPath,
			&i.FromCoursePhaseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCoursePhase = `-- name: UpdateCoursePhase :exec
UPDATE course_phase
SET 
    name = COALESCE($2, name), 
    restricted_data = restricted_data || $3,
    student_readable_data = student_readable_data || $4
WHERE id = $1
`

type UpdateCoursePhaseParams struct {
	ID                  uuid.UUID   `json:"id"`
	Name                pgtype.Text `json:"name"`
	RestrictedData      []byte      `json:"restricted_data"`
	StudentReadableData []byte      `json:"student_readable_data"`
}

func (q *Queries) UpdateCoursePhase(ctx context.Context, arg UpdateCoursePhaseParams) error {
	_, err := q.db.Exec(ctx, updateCoursePhase,
		arg.ID,
		arg.Name,
		arg.RestrictedData,
		arg.StudentReadableData,
	)
	return err
}
