// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: course_phase_type.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCoursePhaseType = `-- name: CreateCoursePhaseType :exec
INSERT INTO course_phase_type (id, name, initial_phase, base_url, description)
VALUES ($1, $2, $3, $4, $5)
`

type CreateCoursePhaseTypeParams struct {
	ID           uuid.UUID   `json:"id"`
	Name         string      `json:"name"`
	InitialPhase bool        `json:"initial_phase"`
	BaseUrl      string      `json:"base_url"`
	Description  pgtype.Text `json:"description"`
}

func (q *Queries) CreateCoursePhaseType(ctx context.Context, arg CreateCoursePhaseTypeParams) error {
	_, err := q.db.Exec(ctx, createCoursePhaseType,
		arg.ID,
		arg.Name,
		arg.InitialPhase,
		arg.BaseUrl,
		arg.Description,
	)
	return err
}

const createCoursePhaseTypeProvidedOutput = `-- name: CreateCoursePhaseTypeProvidedOutput :exec
INSERT INTO course_phase_type_participation_provided_output_dto (id, course_phase_type_id, dto_name, version_number,
                                                                 endpoint_path, specification)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateCoursePhaseTypeProvidedOutputParams struct {
	ID                uuid.UUID `json:"id"`
	CoursePhaseTypeID uuid.UUID `json:"course_phase_type_id"`
	DtoName           string    `json:"dto_name"`
	VersionNumber     int32     `json:"version_number"`
	EndpointPath      string    `json:"endpoint_path"`
	Specification     []byte    `json:"specification"`
}

func (q *Queries) CreateCoursePhaseTypeProvidedOutput(ctx context.Context, arg CreateCoursePhaseTypeProvidedOutputParams) error {
	_, err := q.db.Exec(ctx, createCoursePhaseTypeProvidedOutput,
		arg.ID,
		arg.CoursePhaseTypeID,
		arg.DtoName,
		arg.VersionNumber,
		arg.EndpointPath,
		arg.Specification,
	)
	return err
}

const createCoursePhaseTypeRequiredInput = `-- name: CreateCoursePhaseTypeRequiredInput :exec
INSERT INTO course_phase_type_participation_required_input_dto (id, course_phase_type_id, dto_name, specification)
VALUES ($1, $2, $3, $4)
`

type CreateCoursePhaseTypeRequiredInputParams struct {
	ID                uuid.UUID `json:"id"`
	CoursePhaseTypeID uuid.UUID `json:"course_phase_type_id"`
	DtoName           string    `json:"dto_name"`
	Specification     []byte    `json:"specification"`
}

func (q *Queries) CreateCoursePhaseTypeRequiredInput(ctx context.Context, arg CreateCoursePhaseTypeRequiredInputParams) error {
	_, err := q.db.Exec(ctx, createCoursePhaseTypeRequiredInput,
		arg.ID,
		arg.CoursePhaseTypeID,
		arg.DtoName,
		arg.Specification,
	)
	return err
}

const createRequiredApplicationAnswers = `-- name: CreateRequiredApplicationAnswers :exec
INSERT INTO course_phase_type_participation_required_input_dto (id, course_phase_type_id, dto_name, specification)
VALUES (gen_random_uuid(),
        $1,
        'applicationAnswers',
        '{
          "type": "array",
          "items": {
            "oneOf": [
              {
                "type": "object",
                "properties": {
                  "answer": {
                    "type": "string"
                  },
                  "key": {
                    "type": "string"
                  },
                  "order_num": {
                    "type": "integer"
                  },
                  "type": {
                    "type": "string",
                    "enum": [
                      "text"
                    ]
                  }
                },
                "required": [
                  "answer",
                  "key",
                  "order_num",
                  "type"
                ]
              },
              {
                "type": "object",
                "properties": {
                  "answer": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "key": {
                    "type": "string"
                  },
                  "order_num": {
                    "type": "integer"
                  },
                  "type": {
                    "type": "string",
                    "enum": [
                      "multiselect"
                    ]
                  }
                },
                "required": [
                  "answer",
                  "key",
                  "order_num",
                  "type"
                ]
              }
            ]
          }
        }'::jsonb)
`

func (q *Queries) CreateRequiredApplicationAnswers(ctx context.Context, coursePhaseTypeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, createRequiredApplicationAnswers, coursePhaseTypeID)
	return err
}

const createRequiredDevices = `-- name: CreateRequiredDevices :exec
INSERT INTO course_phase_type_participation_required_input_dto (id, course_phase_type_id, dto_name, specification)
VALUES (gen_random_uuid(),
        $1,
        'devices',
        '{
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "IPhone",
              "IPad",
              "MacBook",
              "AppleWatch"
            ]
          }
        }'::jsonb)
`

func (q *Queries) CreateRequiredDevices(ctx context.Context, coursePhaseTypeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, createRequiredDevices, coursePhaseTypeID)
	return err
}

const getAllCoursePhaseTypes = `-- name: GetAllCoursePhaseTypes :many
SELECT id, name, initial_phase, base_url, description
FROM course_phase_type
`

func (q *Queries) GetAllCoursePhaseTypes(ctx context.Context) ([]CoursePhaseType, error) {
	rows, err := q.db.Query(ctx, getAllCoursePhaseTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoursePhaseType
	for rows.Next() {
		var i CoursePhaseType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.InitialPhase,
			&i.BaseUrl,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoursePhaseProvidedParticipationOutputs = `-- name: GetCoursePhaseProvidedParticipationOutputs :many
SELECT id, course_phase_type_id, dto_name, version_number, endpoint_path, specification
FROM course_phase_type_participation_provided_output_dto
WHERE course_phase_type_id = $1
`

func (q *Queries) GetCoursePhaseProvidedParticipationOutputs(ctx context.Context, coursePhaseTypeID uuid.UUID) ([]CoursePhaseTypeParticipationProvidedOutputDto, error) {
	rows, err := q.db.Query(ctx, getCoursePhaseProvidedParticipationOutputs, coursePhaseTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoursePhaseTypeParticipationProvidedOutputDto
	for rows.Next() {
		var i CoursePhaseTypeParticipationProvidedOutputDto
		if err := rows.Scan(
			&i.ID,
			&i.CoursePhaseTypeID,
			&i.DtoName,
			&i.VersionNumber,
			&i.EndpointPath,
			&i.Specification,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoursePhaseProvidedPhaseOutputs = `-- name: GetCoursePhaseProvidedPhaseOutputs :many
SELECT id, course_phase_type_id, dto_name, version_number, endpoint_path, specification
FROM course_phase_type_phase_provided_output_dto
WHERE course_phase_type_id = $1
`

func (q *Queries) GetCoursePhaseProvidedPhaseOutputs(ctx context.Context, coursePhaseTypeID uuid.UUID) ([]CoursePhaseTypePhaseProvidedOutputDto, error) {
	rows, err := q.db.Query(ctx, getCoursePhaseProvidedPhaseOutputs, coursePhaseTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoursePhaseTypePhaseProvidedOutputDto
	for rows.Next() {
		var i CoursePhaseTypePhaseProvidedOutputDto
		if err := rows.Scan(
			&i.ID,
			&i.CoursePhaseTypeID,
			&i.DtoName,
			&i.VersionNumber,
			&i.EndpointPath,
			&i.Specification,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoursePhaseRequiredParticipationInputs = `-- name: GetCoursePhaseRequiredParticipationInputs :many
SELECT id, course_phase_type_id, dto_name, specification
FROM course_phase_type_participation_required_input_dto
WHERE course_phase_type_id = $1
`

func (q *Queries) GetCoursePhaseRequiredParticipationInputs(ctx context.Context, coursePhaseTypeID uuid.UUID) ([]CoursePhaseTypeParticipationRequiredInputDto, error) {
	rows, err := q.db.Query(ctx, getCoursePhaseRequiredParticipationInputs, coursePhaseTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoursePhaseTypeParticipationRequiredInputDto
	for rows.Next() {
		var i CoursePhaseTypeParticipationRequiredInputDto
		if err := rows.Scan(
			&i.ID,
			&i.CoursePhaseTypeID,
			&i.DtoName,
			&i.Specification,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoursePhaseRequiredPhaseInputs = `-- name: GetCoursePhaseRequiredPhaseInputs :many
SELECT id, course_phase_type_id, dto_name, specification
FROM course_phase_type_phase_required_input_dto
WHERE course_phase_type_id = $1
`

func (q *Queries) GetCoursePhaseRequiredPhaseInputs(ctx context.Context, coursePhaseTypeID uuid.UUID) ([]CoursePhaseTypePhaseRequiredInputDto, error) {
	rows, err := q.db.Query(ctx, getCoursePhaseRequiredPhaseInputs, coursePhaseTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoursePhaseTypePhaseRequiredInputDto
	for rows.Next() {
		var i CoursePhaseTypePhaseRequiredInputDto
		if err := rows.Scan(
			&i.ID,
			&i.CoursePhaseTypeID,
			&i.DtoName,
			&i.Specification,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoursePhaseTypeByID = `-- name: GetCoursePhaseTypeByID :one
SELECT id, name, initial_phase, base_url, description
FROM course_phase_type
WHERE id = $1
`

func (q *Queries) GetCoursePhaseTypeByID(ctx context.Context, id uuid.UUID) (CoursePhaseType, error) {
	row := q.db.QueryRow(ctx, getCoursePhaseTypeByID, id)
	var i CoursePhaseType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InitialPhase,
		&i.BaseUrl,
		&i.Description,
	)
	return i, err
}

const insertActionItemsOutput = `-- name: InsertActionItemsOutput :exec
INSERT INTO course_phase_type_participation_provided_output_dto (id, course_phase_type_id, dto_name, version_number,
                                                                 endpoint_path, specification)
VALUES (gen_random_uuid(),
        $1,
        'actionItems',
        1,
        '/student-assessment/action-item/action',
        '{
          "type": "array",
          "items": {
            "type": "string"
          }
        }'::jsonb)
`

func (q *Queries) InsertActionItemsOutput(ctx context.Context, coursePhaseTypeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, insertActionItemsOutput, coursePhaseTypeID)
	return err
}

const insertAssessmentScoreOutput = `-- name: InsertAssessmentScoreOutput :exec
INSERT INTO course_phase_type_participation_provided_output_dto (id, course_phase_type_id, dto_name, version_number,
                                                                 endpoint_path, specification)
VALUES (gen_random_uuid(),
        $1,
        'scoreLevel',
        1,
        '/student-assessment/scoreLevel',
        '{
          "type": "string",
          "enum": [
            "veryBad",
            "Bad",
            "Ok",
            "Good",
            "VeryGood"
          ]
        }'::jsonb)
`

func (q *Queries) InsertAssessmentScoreOutput(ctx context.Context, coursePhaseTypeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, insertAssessmentScoreOutput, coursePhaseTypeID)
	return err
}

const insertAssessmentScoreRequiredInput = `-- name: InsertAssessmentScoreRequiredInput :exec
INSERT INTO course_phase_type_participation_required_input_dto (id, course_phase_type_id, dto_name, specification)
VALUES (gen_random_uuid(),
        $1,
        'scoreLevel',
        '{
          "type": "string",
          "enum": [
            "veryBad",
            "Bad",
            "Ok",
            "Good",
            "VeryGood"
          ]
        }'::jsonb)
`

func (q *Queries) InsertAssessmentScoreRequiredInput(ctx context.Context, coursePhaseTypeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, insertAssessmentScoreRequiredInput, coursePhaseTypeID)
	return err
}

const insertCourseProvidedAdditionalScores = `-- name: InsertCourseProvidedAdditionalScores :exec
INSERT INTO course_phase_type_participation_provided_output_dto (id, course_phase_type_id, dto_name, version_number,
                                                                 endpoint_path, specification)
VALUES (gen_random_uuid(),
        $1,
        'additionalScores',
        1,
        'core',
        '{
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "score": {
                "type": "number"
              },
              "key": {
                "type": "string"
              }
            },
            "required": [
              "score",
              "key"
            ]
          }
        }'::jsonb)
`

func (q *Queries) InsertCourseProvidedAdditionalScores(ctx context.Context, coursePhaseTypeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, insertCourseProvidedAdditionalScores, coursePhaseTypeID)
	return err
}

const insertCourseProvidedApplicationAnswers = `-- name: InsertCourseProvidedApplicationAnswers :exec
INSERT INTO course_phase_type_participation_provided_output_dto (id, course_phase_type_id, dto_name, version_number,
                                                                 endpoint_path, specification)
VALUES (gen_random_uuid(),
        $1,
        'applicationAnswers',
        1,
        'core',
        '{
          "type": "array",
          "items": {
            "oneOf": [
              {
                "type": "object",
                "properties": {
                  "answer": {
                    "type": "string"
                  },
                  "key": {
                    "type": "string"
                  },
                  "order_num": {
                    "type": "integer"
                  },
                  "type": {
                    "type": "string",
                    "enum": [
                      "text"
                    ]
                  }
                },
                "required": [
                  "answer",
                  "key",
                  "order_num",
                  "type"
                ]
              },
              {
                "type": "object",
                "properties": {
                  "answer": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "key": {
                    "type": "string"
                  },
                  "order_num": {
                    "type": "integer"
                  },
                  "type": {
                    "type": "string",
                    "enum": [
                      "multiselect"
                    ]
                  }
                },
                "required": [
                  "answer",
                  "key",
                  "order_num",
                  "type"
                ]
              }
            ]
          }
        }'::jsonb)
`

func (q *Queries) InsertCourseProvidedApplicationAnswers(ctx context.Context, coursePhaseTypeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, insertCourseProvidedApplicationAnswers, coursePhaseTypeID)
	return err
}

const insertGradeOutput = `-- name: InsertGradeOutput :exec
INSERT INTO course_phase_type_participation_provided_output_dto (id, course_phase_type_id, dto_name, version_number,
                                                                 endpoint_path, specification)
VALUES (gen_random_uuid(),
        $1,
        'grade',
        1,
        '/student-assessment/completed/grade',
        '{
          "type": "number"
        }'::jsonb)
`

func (q *Queries) InsertGradeOutput(ctx context.Context, coursePhaseTypeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, insertGradeOutput, coursePhaseTypeID)
	return err
}

const insertProvidedOutputDevices = `-- name: InsertProvidedOutputDevices :exec
INSERT INTO course_phase_type_participation_provided_output_dto (id, course_phase_type_id, dto_name, version_number,
                                                                 endpoint_path, specification)
VALUES (gen_random_uuid(),
        $1,
        'devices',
        1,
        '/devices',
        '{
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "IPhone",
              "IPad",
              "MacBook",
              "AppleWatch"
            ]
          }
        }'::jsonb)
`

func (q *Queries) InsertProvidedOutputDevices(ctx context.Context, coursePhaseTypeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, insertProvidedOutputDevices, coursePhaseTypeID)
	return err
}

const insertTeamAllocationOutput = `-- name: InsertTeamAllocationOutput :exec
INSERT INTO course_phase_type_participation_provided_output_dto (id, course_phase_type_id, dto_name, version_number,
                                                                 endpoint_path, specification)
VALUES (gen_random_uuid(),
        $1,
        'teamAllocation',
        1,
        '/allocation',
        '{
          "type": "string"
        }'::jsonb)
`

// This returns the teamID for a given courseParticipationID, to which the user is assigned
func (q *Queries) InsertTeamAllocationOutput(ctx context.Context, coursePhaseTypeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, insertTeamAllocationOutput, coursePhaseTypeID)
	return err
}

const insertTeamAllocationRequiredInput = `-- name: InsertTeamAllocationRequiredInput :exec
INSERT INTO course_phase_type_participation_required_input_dto(id, course_phase_type_id, dto_name, specification)
VALUES (gen_random_uuid(),
        $1,
        'teamAllocation',
        '{
          "type": "string"
        }'::jsonb)
`

func (q *Queries) InsertTeamAllocationRequiredInput(ctx context.Context, coursePhaseTypeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, insertTeamAllocationRequiredInput, coursePhaseTypeID)
	return err
}

const insertTeamOutput = `-- name: InsertTeamOutput :exec
INSERT INTO course_phase_type_phase_provided_output_dto (id, course_phase_type_id, dto_name, version_number,
                                                         endpoint_path, specification)
VALUES (gen_random_uuid(),
        $1,
        'teams',
        1,
        '/team',
        '{
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "name": {
                "type": "string"
              }
            },
            "required": [
              "id",
              "name"
            ]
          }
        }'::jsonb)
`

func (q *Queries) InsertTeamOutput(ctx context.Context, coursePhaseTypeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, insertTeamOutput, coursePhaseTypeID)
	return err
}

const insertTeamRequiredInput = `-- name: InsertTeamRequiredInput :exec
INSERT INTO course_phase_type_phase_required_input_dto (id, course_phase_type_id, dto_name, specification)
VALUES (gen_random_uuid(),
        $1,
        'teams',
        '{
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "name": {
                "type": "string"
              }
            },
            "required": [
              "id",
              "name"
            ]
          }
        }'::jsonb)
`

func (q *Queries) InsertTeamRequiredInput(ctx context.Context, coursePhaseTypeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, insertTeamRequiredInput, coursePhaseTypeID)
	return err
}

const testApplicationPhaseTypeExists = `-- name: TestApplicationPhaseTypeExists :one
SELECT EXISTS (SELECT 1
               FROM course_phase_type
               WHERE name = 'Application') AS does_exist
`

func (q *Queries) TestApplicationPhaseTypeExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, testApplicationPhaseTypeExists)
	var does_exist bool
	err := row.Scan(&does_exist)
	return does_exist, err
}

const testAssessmentTypeExists = `-- name: TestAssessmentTypeExists :one
SELECT EXISTS (SELECT 1
               FROM course_phase_type
               WHERE name = 'Assessment') AS does_exist
`

func (q *Queries) TestAssessmentTypeExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, testAssessmentTypeExists)
	var does_exist bool
	err := row.Scan(&does_exist)
	return does_exist, err
}

const testCertificateTypeExists = `-- name: TestCertificateTypeExists :one
SELECT EXISTS (SELECT 1
               FROM course_phase_type
               WHERE name = 'Certificate') AS does_exist
`

func (q *Queries) TestCertificateTypeExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, testCertificateTypeExists)
	var does_exist bool
	err := row.Scan(&does_exist)
	return does_exist, err
}

const testDevOpsChallengeTypeExists = `-- name: TestDevOpsChallengeTypeExists :one
SELECT EXISTS (SELECT 1
               FROM course_phase_type
               WHERE name = 'DevOps Challenge') AS does_exist
`

func (q *Queries) TestDevOpsChallengeTypeExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, testDevOpsChallengeTypeExists)
	var does_exist bool
	err := row.Scan(&does_exist)
	return does_exist, err
}

const testInterviewPhaseTypeExists = `-- name: TestInterviewPhaseTypeExists :one
SELECT EXISTS (SELECT 1
               FROM course_phase_type
               WHERE name = 'Interview') AS does_exist
`

func (q *Queries) TestInterviewPhaseTypeExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, testInterviewPhaseTypeExists)
	var does_exist bool
	err := row.Scan(&does_exist)
	return does_exist, err
}

const testIntroCourseDeveloperPhaseTypeExists = `-- name: TestIntroCourseDeveloperPhaseTypeExists :one
SELECT EXISTS (SELECT 1
               FROM course_phase_type
               WHERE name = 'Intro Course Developer') AS does_exist
`

func (q *Queries) TestIntroCourseDeveloperPhaseTypeExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, testIntroCourseDeveloperPhaseTypeExists)
	var does_exist bool
	err := row.Scan(&does_exist)
	return does_exist, err
}

const testIntroCourseTutorPhaseTypeExists = `-- name: TestIntroCourseTutorPhaseTypeExists :one
SELECT EXISTS (SELECT 1
               FROM course_phase_type
               WHERE name = 'IntroCourseTutor') AS does_exist
`

func (q *Queries) TestIntroCourseTutorPhaseTypeExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, testIntroCourseTutorPhaseTypeExists)
	var does_exist bool
	err := row.Scan(&does_exist)
	return does_exist, err
}

const testMatchingPhaseTypeExists = `-- name: TestMatchingPhaseTypeExists :one
SELECT EXISTS (SELECT 1
               FROM course_phase_type
               WHERE name = 'Matching') AS does_exist
`

func (q *Queries) TestMatchingPhaseTypeExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, testMatchingPhaseTypeExists)
	var does_exist bool
	err := row.Scan(&does_exist)
	return does_exist, err
}

const testSelfTeamAllocationTypeExists = `-- name: TestSelfTeamAllocationTypeExists :one
SELECT EXISTS (SELECT 1
               FROM course_phase_type
               WHERE name = 'Self Team Allocation') AS does_exist
`

func (q *Queries) TestSelfTeamAllocationTypeExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, testSelfTeamAllocationTypeExists)
	var does_exist bool
	err := row.Scan(&does_exist)
	return does_exist, err
}

const testTeamAllocationTypeExists = `-- name: TestTeamAllocationTypeExists :one
SELECT EXISTS (SELECT 1
               FROM course_phase_type
               WHERE name = 'Team Allocation') AS does_exist
`

func (q *Queries) TestTeamAllocationTypeExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, testTeamAllocationTypeExists)
	var does_exist bool
	err := row.Scan(&does_exist)
	return does_exist, err
}
