// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: org.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrg = `-- name: CreateOrg :one
INSERT INTO org (id, parent_org_id, name, slug, school, university, website, contact_email)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, parent_org_id, name, slug, school, university, website, contact_email, created_at
`

type CreateOrgParams struct {
	ID           uuid.UUID   `json:"id"`
	ParentOrgID  pgtype.UUID `json:"parent_org_id"`
	Name         string      `json:"name"`
	Slug         string      `json:"slug"`
	School       pgtype.Text `json:"school"`
	University   pgtype.Text `json:"university"`
	Website      pgtype.Text `json:"website"`
	ContactEmail pgtype.Text `json:"contact_email"`
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (Org, error) {
	row := q.db.QueryRow(ctx, createOrg,
		arg.ID,
		arg.ParentOrgID,
		arg.Name,
		arg.Slug,
		arg.School,
		arg.University,
		arg.Website,
		arg.ContactEmail,
	)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.ParentOrgID,
		&i.Name,
		&i.Slug,
		&i.School,
		&i.University,
		&i.Website,
		&i.ContactEmail,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOrg = `-- name: DeleteOrg :one
DELETE FROM org WHERE id = $1 RETURNING slug
`

func (q *Queries) DeleteOrg(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, deleteOrg, id)
	var slug string
	err := row.Scan(&slug)
	return slug, err
}

const getAllOrgs = `-- name: GetAllOrgs :many
SELECT id, parent_org_id, name, slug, school, university, website, contact_email, created_at FROM org ORDER BY name ASC, slug ASC
`

func (q *Queries) GetAllOrgs(ctx context.Context) ([]Org, error) {
	rows, err := q.db.Query(ctx, getAllOrgs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Org
	for rows.Next() {
		var i Org
		if err := rows.Scan(
			&i.ID,
			&i.ParentOrgID,
			&i.Name,
			&i.Slug,
			&i.School,
			&i.University,
			&i.Website,
			&i.ContactEmail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrgAncestorIDs = `-- name: GetOrgAncestorIDs :many
WITH RECURSIVE ancestors (id) AS (
  SELECT o.parent_org_id
  FROM org o
  WHERE o.id = $1 AND o.parent_org_id IS NOT NULL
  UNION
  SELECT o.parent_org_id
  FROM org o
  JOIN ancestors a ON o.id = a.id
  WHERE o.parent_org_id IS NOT NULL
)
SELECT id::uuid AS id FROM ancestors
`

// Walks up the hierarchy from the given org, excluding the org itself. UNION (not
// UNION ALL) discards rows that were already seen, so the walk terminates even if
// the data contains a cycle, and memory stays linear in the depth.
func (q *Queries) GetOrgAncestorIDs(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getOrgAncestorIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrgByID = `-- name: GetOrgByID :one
SELECT id, parent_org_id, name, slug, school, university, website, contact_email, created_at FROM org WHERE id = $1
`

func (q *Queries) GetOrgByID(ctx context.Context, id uuid.UUID) (Org, error) {
	row := q.db.QueryRow(ctx, getOrgByID, id)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.ParentOrgID,
		&i.Name,
		&i.Slug,
		&i.School,
		&i.University,
		&i.Website,
		&i.ContactEmail,
		&i.CreatedAt,
	)
	return i, err
}

const lockOrgHierarchy = `-- name: LockOrgHierarchy :exec
SELECT pg_advisory_xact_lock(hashtext('org_hierarchy'))
`

// Serializes hierarchy changes for the rest of the transaction, so two concurrent
// parent updates cannot each pass the cycle check and together create a cycle.
func (q *Queries) LockOrgHierarchy(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockOrgHierarchy)
	return err
}

const updateOrg = `-- name: UpdateOrg :one
UPDATE org
SET name = $2, school = $3, university = $4, website = $5, contact_email = $6
WHERE id = $1
RETURNING id, parent_org_id, name, slug, school, university, website, contact_email, created_at
`

type UpdateOrgParams struct {
	ID           uuid.UUID   `json:"id"`
	Name         string      `json:"name"`
	School       pgtype.Text `json:"school"`
	University   pgtype.Text `json:"university"`
	Website      pgtype.Text `json:"website"`
	ContactEmail pgtype.Text `json:"contact_email"`
}

func (q *Queries) UpdateOrg(ctx context.Context, arg UpdateOrgParams) (Org, error) {
	row := q.db.QueryRow(ctx, updateOrg,
		arg.ID,
		arg.Name,
		arg.School,
		arg.University,
		arg.Website,
		arg.ContactEmail,
	)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.ParentOrgID,
		&i.Name,
		&i.Slug,
		&i.School,
		&i.University,
		&i.Website,
		&i.ContactEmail,
		&i.CreatedAt,
	)
	return i, err
}

const updateOrgParent = `-- name: UpdateOrgParent :one
UPDATE org SET parent_org_id = $2 WHERE id = $1 RETURNING id, parent_org_id, name, slug, school, university, website, contact_email, created_at
`

type UpdateOrgParentParams struct {
	ID          uuid.UUID   `json:"id"`
	ParentOrgID pgtype.UUID `json:"parent_org_id"`
}

func (q *Queries) UpdateOrgParent(ctx context.Context, arg UpdateOrgParentParams) (Org, error) {
	row := q.db.QueryRow(ctx, updateOrgParent, arg.ID, arg.ParentOrgID)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.ParentOrgID,
		&i.Name,
		&i.Slug,
		&i.School,
		&i.University,
		&i.Website,
		&i.ContactEmail,
		&i.CreatedAt,
	)
	return i, err
}
