// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: privacy_export.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNewExport = `-- name: CreateNewExport :one
INSERT INTO privacy_export ( id, userID, studentID, status, valid_until )
VALUES ($1, $2, $3, $4, $5)
RETURNING id, userid, studentid, status, date_created, valid_until
`

type CreateNewExportParams struct {
	ID         uuid.UUID          `json:"id"`
	Userid     uuid.UUID          `json:"userid"`
	Studentid  pgtype.UUID        `json:"studentid"`
	Status     ExportStatus       `json:"status"`
	ValidUntil pgtype.Timestamptz `json:"valid_until"`
}

func (q *Queries) CreateNewExport(ctx context.Context, arg CreateNewExportParams) (PrivacyExport, error) {
	row := q.db.QueryRow(ctx, createNewExport,
		arg.ID,
		arg.Userid,
		arg.Studentid,
		arg.Status,
		arg.ValidUntil,
	)
	var i PrivacyExport
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Studentid,
		&i.Status,
		&i.DateCreated,
		&i.ValidUntil,
	)
	return i, err
}

const createNewExportDoc = `-- name: CreateNewExportDoc :one
INSERT INTO privacy_export_document ( id, exportID, source_name, object_key, status )
VALUES ($1, $2, $3, $4, $5)
RETURNING id, exportid, date_created, source_name, object_key, status, file_size
`

type CreateNewExportDocParams struct {
	ID         uuid.UUID    `json:"id"`
	Exportid   pgtype.UUID  `json:"exportid"`
	SourceName string       `json:"source_name"`
	ObjectKey  string       `json:"object_key"`
	Status     ExportStatus `json:"status"`
}

func (q *Queries) CreateNewExportDoc(ctx context.Context, arg CreateNewExportDocParams) (PrivacyExportDocument, error) {
	row := q.db.QueryRow(ctx, createNewExportDoc,
		arg.ID,
		arg.Exportid,
		arg.SourceName,
		arg.ObjectKey,
		arg.Status,
	)
	var i PrivacyExportDocument
	err := row.Scan(
		&i.ID,
		&i.Exportid,
		&i.DateCreated,
		&i.SourceName,
		&i.ObjectKey,
		&i.Status,
		&i.FileSize,
	)
	return i, err
}

const getExportRecordByID = `-- name: GetExportRecordByID :one
SELECT id, userid, studentid, status, date_created, valid_until FROM privacy_export WHERE id = $1 LIMIT 1
`

func (q *Queries) GetExportRecordByID(ctx context.Context, id uuid.UUID) (PrivacyExport, error) {
	row := q.db.QueryRow(ctx, getExportRecordByID, id)
	var i PrivacyExport
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Studentid,
		&i.Status,
		&i.DateCreated,
		&i.ValidUntil,
	)
	return i, err
}

const getExportRecordByIDWithDocs = `-- name: GetExportRecordByIDWithDocs :one
SELECT id, userid, studentid, status, date_created, valid_until, documents FROM privacy_export_with_docs WHERE id = $1
`

func (q *Queries) GetExportRecordByIDWithDocs(ctx context.Context, id uuid.UUID) (PrivacyExportWithDoc, error) {
	row := q.db.QueryRow(ctx, getExportRecordByIDWithDocs, id)
	var i PrivacyExportWithDoc
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Studentid,
		&i.Status,
		&i.DateCreated,
		&i.ValidUntil,
		&i.Documents,
	)
	return i, err
}

const getLatestExportForUserWithDocs = `-- name: GetLatestExportForUserWithDocs :one
SELECT id, userid, studentid, status, date_created, valid_until, documents FROM privacy_export_with_docs WHERE userID = $1 ORDER BY date_created DESC LIMIT 1
`

func (q *Queries) GetLatestExportForUserWithDocs(ctx context.Context, userid uuid.UUID) (PrivacyExportWithDoc, error) {
	row := q.db.QueryRow(ctx, getLatestExportForUserWithDocs, userid)
	var i PrivacyExportWithDoc
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Studentid,
		&i.Status,
		&i.DateCreated,
		&i.ValidUntil,
		&i.Documents,
	)
	return i, err
}

const setExportDocStatus = `-- name: SetExportDocStatus :one
UPDATE privacy_export_document SET status = $2 WHERE id = $1 RETURNING id, exportid, date_created, source_name, object_key, status, file_size
`

type SetExportDocStatusParams struct {
	ID     uuid.UUID    `json:"id"`
	Status ExportStatus `json:"status"`
}

func (q *Queries) SetExportDocStatus(ctx context.Context, arg SetExportDocStatusParams) (PrivacyExportDocument, error) {
	row := q.db.QueryRow(ctx, setExportDocStatus, arg.ID, arg.Status)
	var i PrivacyExportDocument
	err := row.Scan(
		&i.ID,
		&i.Exportid,
		&i.DateCreated,
		&i.SourceName,
		&i.ObjectKey,
		&i.Status,
		&i.FileSize,
	)
	return i, err
}

const setExportStatus = `-- name: SetExportStatus :one
UPDATE privacy_export SET status = $2 WHERE id = $1 RETURNING id, userid, studentid, status, date_created, valid_until
`

type SetExportStatusParams struct {
	ID     uuid.UUID    `json:"id"`
	Status ExportStatus `json:"status"`
}

func (q *Queries) SetExportStatus(ctx context.Context, arg SetExportStatusParams) (PrivacyExport, error) {
	row := q.db.QueryRow(ctx, setExportStatus, arg.ID, arg.Status)
	var i PrivacyExport
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Studentid,
		&i.Status,
		&i.DateCreated,
		&i.ValidUntil,
	)
	return i, err
}

const updateExportDocResult = `-- name: UpdateExportDocResult :one
UPDATE privacy_export_document SET status = $2, file_size = $3 WHERE id = $1 RETURNING id, exportid, date_created, source_name, object_key, status, file_size
`

type UpdateExportDocResultParams struct {
	ID       uuid.UUID    `json:"id"`
	Status   ExportStatus `json:"status"`
	FileSize pgtype.Int8  `json:"file_size"`
}

func (q *Queries) UpdateExportDocResult(ctx context.Context, arg UpdateExportDocResultParams) (PrivacyExportDocument, error) {
	row := q.db.QueryRow(ctx, updateExportDocResult, arg.ID, arg.Status, arg.FileSize)
	var i PrivacyExportDocument
	err := row.Scan(
		&i.ID,
		&i.Exportid,
		&i.DateCreated,
		&i.SourceName,
		&i.ObjectKey,
		&i.Status,
		&i.FileSize,
	)
	return i, err
}
