// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: privacy_deletion.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAdminInitiatedDeletionRequest = `-- name: CreateAdminInitiatedDeletionRequest :one
INSERT INTO privacy_deletion_request (
  id, user_id, student_id, status,
  auditor_id, auditor_name, auditor_email, auditor_note, auditor_responded_at
)
VALUES ($1, NULL, $2, 'in_progress', $3, $4, $5, $6, now())
RETURNING id, user_id, student_id, requested_at, status, auditor_id, auditor_name, auditor_email, auditor_responded_at, auditor_note, completed_at
`

type CreateAdminInitiatedDeletionRequestParams struct {
	ID           uuid.UUID   `json:"id"`
	StudentID    pgtype.UUID `json:"student_id"`
	AuditorID    pgtype.UUID `json:"auditor_id"`
	AuditorName  string      `json:"auditor_name"`
	AuditorEmail string      `json:"auditor_email"`
	AuditorNote  string      `json:"auditor_note"`
}

func (q *Queries) CreateAdminInitiatedDeletionRequest(ctx context.Context, arg CreateAdminInitiatedDeletionRequestParams) (PrivacyDeletionRequest, error) {
	row := q.db.QueryRow(ctx, createAdminInitiatedDeletionRequest,
		arg.ID,
		arg.StudentID,
		arg.AuditorID,
		arg.AuditorName,
		arg.AuditorEmail,
		arg.AuditorNote,
	)
	var i PrivacyDeletionRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudentID,
		&i.RequestedAt,
		&i.Status,
		&i.AuditorID,
		&i.AuditorName,
		&i.AuditorEmail,
		&i.AuditorRespondedAt,
		&i.AuditorNote,
		&i.CompletedAt,
	)
	return i, err
}

const createNewDeletionRequest = `-- name: CreateNewDeletionRequest :one
INSERT INTO privacy_deletion_request (id, user_id, student_id, status)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, student_id, requested_at, status, auditor_id, auditor_name, auditor_email, auditor_responded_at, auditor_note, completed_at
`

type CreateNewDeletionRequestParams struct {
	ID        uuid.UUID                    `json:"id"`
	UserID    pgtype.UUID                  `json:"user_id"`
	StudentID pgtype.UUID                  `json:"student_id"`
	Status    PrivacyDeletionRequestStatus `json:"status"`
}

func (q *Queries) CreateNewDeletionRequest(ctx context.Context, arg CreateNewDeletionRequestParams) (PrivacyDeletionRequest, error) {
	row := q.db.QueryRow(ctx, createNewDeletionRequest,
		arg.ID,
		arg.UserID,
		arg.StudentID,
		arg.Status,
	)
	var i PrivacyDeletionRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudentID,
		&i.RequestedAt,
		&i.Status,
		&i.AuditorID,
		&i.AuditorName,
		&i.AuditorEmail,
		&i.AuditorRespondedAt,
		&i.AuditorNote,
		&i.CompletedAt,
	)
	return i, err
}

const createNewDeletionSubrequest = `-- name: CreateNewDeletionSubrequest :one
INSERT INTO privacy_deletion_subrequest (id, deletion_request_id, source_name, status)
VALUES ($1, $2, $3, $4)
RETURNING id, deletion_request_id, source_name, status, created_at, completed_at, error_message
`

type CreateNewDeletionSubrequestParams struct {
	ID                uuid.UUID                       `json:"id"`
	DeletionRequestID uuid.UUID                       `json:"deletion_request_id"`
	SourceName        string                          `json:"source_name"`
	Status            PrivacyDeletionSubrequestStatus `json:"status"`
}

func (q *Queries) CreateNewDeletionSubrequest(ctx context.Context, arg CreateNewDeletionSubrequestParams) (PrivacyDeletionSubrequest, error) {
	row := q.db.QueryRow(ctx, createNewDeletionSubrequest,
		arg.ID,
		arg.DeletionRequestID,
		arg.SourceName,
		arg.Status,
	)
	var i PrivacyDeletionSubrequest
	err := row.Scan(
		&i.ID,
		&i.DeletionRequestID,
		&i.SourceName,
		&i.Status,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
	)
	return i, err
}

const getAllDeletionRequests = `-- name: GetAllDeletionRequests :many
SELECT
  v.id, v.user_id, v.student_id, v.requested_at, v.status, v.auditor_id, v.auditor_name, v.auditor_email, v.auditor_responded_at, v.auditor_note, v.completed_at, v.subrequests,
  s.first_name AS student_first_name,
  s.last_name  AS student_last_name,
  s.email      AS student_email
FROM privacy_deletion_request_with_subrequests v
LEFT JOIN student s ON s.id = v.student_id
ORDER BY v.requested_at DESC
`

type GetAllDeletionRequestsRow struct {
	ID                 uuid.UUID                    `json:"id"`
	UserID             pgtype.UUID                  `json:"user_id"`
	StudentID          pgtype.UUID                  `json:"student_id"`
	RequestedAt        pgtype.Timestamptz           `json:"requested_at"`
	Status             PrivacyDeletionRequestStatus `json:"status"`
	AuditorID          pgtype.UUID                  `json:"auditor_id"`
	AuditorName        string                       `json:"auditor_name"`
	AuditorEmail       string                       `json:"auditor_email"`
	AuditorRespondedAt pgtype.Timestamptz           `json:"auditor_responded_at"`
	AuditorNote        string                       `json:"auditor_note"`
	CompletedAt        pgtype.Timestamptz           `json:"completed_at"`
	Subrequests        []byte                       `json:"subrequests"`
	StudentFirstName   pgtype.Text                  `json:"student_first_name"`
	StudentLastName    pgtype.Text                  `json:"student_last_name"`
	StudentEmail       pgtype.Text                  `json:"student_email"`
}

func (q *Queries) GetAllDeletionRequests(ctx context.Context) ([]GetAllDeletionRequestsRow, error) {
	rows, err := q.db.Query(ctx, getAllDeletionRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllDeletionRequestsRow
	for rows.Next() {
		var i GetAllDeletionRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StudentID,
			&i.RequestedAt,
			&i.Status,
			&i.AuditorID,
			&i.AuditorName,
			&i.AuditorEmail,
			&i.AuditorRespondedAt,
			&i.AuditorNote,
			&i.CompletedAt,
			&i.Subrequests,
			&i.StudentFirstName,
			&i.StudentLastName,
			&i.StudentEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeletionRequestByID = `-- name: GetDeletionRequestByID :one
SELECT id, user_id, student_id, requested_at, status, auditor_id, auditor_name, auditor_email, auditor_responded_at, auditor_note, completed_at FROM privacy_deletion_request WHERE id = $1
`

func (q *Queries) GetDeletionRequestByID(ctx context.Context, id uuid.UUID) (PrivacyDeletionRequest, error) {
	row := q.db.QueryRow(ctx, getDeletionRequestByID, id)
	var i PrivacyDeletionRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudentID,
		&i.RequestedAt,
		&i.Status,
		&i.AuditorID,
		&i.AuditorName,
		&i.AuditorEmail,
		&i.AuditorRespondedAt,
		&i.AuditorNote,
		&i.CompletedAt,
	)
	return i, err
}

const getDeletionRequestByIDWithSubrequests = `-- name: GetDeletionRequestByIDWithSubrequests :one
SELECT id, user_id, student_id, requested_at, status, auditor_id, auditor_name, auditor_email, auditor_responded_at, auditor_note, completed_at, subrequests FROM privacy_deletion_request_with_subrequests WHERE id = $1
`

func (q *Queries) GetDeletionRequestByIDWithSubrequests(ctx context.Context, id uuid.UUID) (PrivacyDeletionRequestWithSubrequest, error) {
	row := q.db.QueryRow(ctx, getDeletionRequestByIDWithSubrequests, id)
	var i PrivacyDeletionRequestWithSubrequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudentID,
		&i.RequestedAt,
		&i.Status,
		&i.AuditorID,
		&i.AuditorName,
		&i.AuditorEmail,
		&i.AuditorRespondedAt,
		&i.AuditorNote,
		&i.CompletedAt,
		&i.Subrequests,
	)
	return i, err
}

const getLatestDeletionRequestForUserWithSubrequests = `-- name: GetLatestDeletionRequestForUserWithSubrequests :one
SELECT id, user_id, student_id, requested_at, status, auditor_id, auditor_name, auditor_email, auditor_responded_at, auditor_note, completed_at, subrequests FROM privacy_deletion_request_with_subrequests
WHERE user_id = $1
ORDER BY requested_at DESC
LIMIT 1
`

func (q *Queries) GetLatestDeletionRequestForUserWithSubrequests(ctx context.Context, userID pgtype.UUID) (PrivacyDeletionRequestWithSubrequest, error) {
	row := q.db.QueryRow(ctx, getLatestDeletionRequestForUserWithSubrequests, userID)
	var i PrivacyDeletionRequestWithSubrequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudentID,
		&i.RequestedAt,
		&i.Status,
		&i.AuditorID,
		&i.AuditorName,
		&i.AuditorEmail,
		&i.AuditorRespondedAt,
		&i.AuditorNote,
		&i.CompletedAt,
		&i.Subrequests,
	)
	return i, err
}

const getOpenDeletionRequestForUser = `-- name: GetOpenDeletionRequestForUser :one
SELECT id, user_id, student_id, requested_at, status, auditor_id, auditor_name, auditor_email, auditor_responded_at, auditor_note, completed_at FROM privacy_deletion_request
WHERE user_id = $1 AND status IN ('pending_approval', 'in_progress')
LIMIT 1
`

func (q *Queries) GetOpenDeletionRequestForUser(ctx context.Context, userID pgtype.UUID) (PrivacyDeletionRequest, error) {
	row := q.db.QueryRow(ctx, getOpenDeletionRequestForUser, userID)
	var i PrivacyDeletionRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudentID,
		&i.RequestedAt,
		&i.Status,
		&i.AuditorID,
		&i.AuditorName,
		&i.AuditorEmail,
		&i.AuditorRespondedAt,
		&i.AuditorNote,
		&i.CompletedAt,
	)
	return i, err
}

const scrubDeletionRequestAuditorByID = `-- name: ScrubDeletionRequestAuditorByID :exec
UPDATE privacy_deletion_request
SET auditor_name  = '',
    auditor_email = ''
WHERE auditor_id = $1
`

func (q *Queries) ScrubDeletionRequestAuditorByID(ctx context.Context, auditorID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, scrubDeletionRequestAuditorByID, auditorID)
	return err
}

const setDeletionRequestAuditor = `-- name: SetDeletionRequestAuditor :exec
UPDATE privacy_deletion_request
SET auditor_id           = $2,
    auditor_name         = $3,
    auditor_email        = $4,
    auditor_note         = $5,
    auditor_responded_at = now()
WHERE id = $1
`

type SetDeletionRequestAuditorParams struct {
	ID           uuid.UUID   `json:"id"`
	AuditorID    pgtype.UUID `json:"auditor_id"`
	AuditorName  string      `json:"auditor_name"`
	AuditorEmail string      `json:"auditor_email"`
	AuditorNote  string      `json:"auditor_note"`
}

func (q *Queries) SetDeletionRequestAuditor(ctx context.Context, arg SetDeletionRequestAuditorParams) error {
	_, err := q.db.Exec(ctx, setDeletionRequestAuditor,
		arg.ID,
		arg.AuditorID,
		arg.AuditorName,
		arg.AuditorEmail,
		arg.AuditorNote,
	)
	return err
}

const setDeletionRequestStatus = `-- name: SetDeletionRequestStatus :one
UPDATE privacy_deletion_request
SET status       = $2,
    completed_at = CASE WHEN $2::privacy_deletion_request_status IN ('rejected', 'succeeded', 'failed') THEN now() ELSE completed_at END
WHERE id = $1
RETURNING id, user_id, student_id, requested_at, status, auditor_id, auditor_name, auditor_email, auditor_responded_at, auditor_note, completed_at
`

type SetDeletionRequestStatusParams struct {
	ID     uuid.UUID                    `json:"id"`
	Status PrivacyDeletionRequestStatus `json:"status"`
}

func (q *Queries) SetDeletionRequestStatus(ctx context.Context, arg SetDeletionRequestStatusParams) (PrivacyDeletionRequest, error) {
	row := q.db.QueryRow(ctx, setDeletionRequestStatus, arg.ID, arg.Status)
	var i PrivacyDeletionRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudentID,
		&i.RequestedAt,
		&i.Status,
		&i.AuditorID,
		&i.AuditorName,
		&i.AuditorEmail,
		&i.AuditorRespondedAt,
		&i.AuditorNote,
		&i.CompletedAt,
	)
	return i, err
}

const setDeletionSubrequestStatus = `-- name: SetDeletionSubrequestStatus :one
UPDATE privacy_deletion_subrequest
SET status        = $2,
    completed_at  = CASE WHEN $2::privacy_deletion_subrequest_status IN ('succeeded', 'failed') THEN now() ELSE completed_at END,
    error_message = $3
WHERE id = $1
RETURNING id, deletion_request_id, source_name, status, created_at, completed_at, error_message
`

type SetDeletionSubrequestStatusParams struct {
	ID           uuid.UUID                       `json:"id"`
	Status       PrivacyDeletionSubrequestStatus `json:"status"`
	ErrorMessage string                          `json:"error_message"`
}

func (q *Queries) SetDeletionSubrequestStatus(ctx context.Context, arg SetDeletionSubrequestStatusParams) (PrivacyDeletionSubrequest, error) {
	row := q.db.QueryRow(ctx, setDeletionSubrequestStatus, arg.ID, arg.Status, arg.ErrorMessage)
	var i PrivacyDeletionSubrequest
	err := row.Scan(
		&i.ID,
		&i.DeletionRequestID,
		&i.SourceName,
		&i.Status,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
	)
	return i, err
}
