// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: privacy_export.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNewExport = `-- name: CreateNewExport :one
INSERT INTO privacy_export ( id, user_id, student_id, status, valid_until )
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, student_id, status, date_created, valid_until
`

type CreateNewExportParams struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	StudentID  pgtype.UUID        `json:"student_id"`
	Status     ExportStatus       `json:"status"`
	ValidUntil pgtype.Timestamptz `json:"valid_until"`
}

func (q *Queries) CreateNewExport(ctx context.Context, arg CreateNewExportParams) (PrivacyExport, error) {
	row := q.db.QueryRow(ctx, createNewExport,
		arg.ID,
		arg.UserID,
		arg.StudentID,
		arg.Status,
		arg.ValidUntil,
	)
	var i PrivacyExport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudentID,
		&i.Status,
		&i.DateCreated,
		&i.ValidUntil,
	)
	return i, err
}

const createNewExportDoc = `-- name: CreateNewExportDoc :one
INSERT INTO privacy_export_document ( id, export_id, source_name, object_key, status )
VALUES ($1, $2, $3, $4, $5)
RETURNING id, export_id, date_created, source_name, object_key, status, file_size, downloaded_at
`

type CreateNewExportDocParams struct {
	ID         uuid.UUID    `json:"id"`
	ExportID   pgtype.UUID  `json:"export_id"`
	SourceName string       `json:"source_name"`
	ObjectKey  string       `json:"object_key"`
	Status     ExportStatus `json:"status"`
}

func (q *Queries) CreateNewExportDoc(ctx context.Context, arg CreateNewExportDocParams) (PrivacyExportDocument, error) {
	row := q.db.QueryRow(ctx, createNewExportDoc,
		arg.ID,
		arg.ExportID,
		arg.SourceName,
		arg.ObjectKey,
		arg.Status,
	)
	var i PrivacyExportDocument
	err := row.Scan(
		&i.ID,
		&i.ExportID,
		&i.DateCreated,
		&i.SourceName,
		&i.ObjectKey,
		&i.Status,
		&i.FileSize,
		&i.DownloadedAt,
	)
	return i, err
}

const getAllExports = `-- name: GetAllExports :many
SELECT
  e.id,
  e.status,
  e.date_created,
  e.valid_until,
  COALESCE(
    JSON_AGG(JSON_BUILD_OBJECT(
      'source_name', ed.source_name,
      'status', ed.status,
      'downloaded', ed.downloaded_at IS NOT NULL
    ) ORDER BY ed.source_name) FILTER (WHERE ed.id IS NOT NULL),
    '[]'::json
  ) AS docs
FROM privacy_export e
LEFT JOIN privacy_export_document ed ON ed.export_id = e.id
GROUP BY e.id
ORDER BY e.date_created DESC
`

type GetAllExportsRow struct {
	ID          uuid.UUID          `json:"id"`
	Status      ExportStatus       `json:"status"`
	DateCreated pgtype.Timestamptz `json:"date_created"`
	ValidUntil  pgtype.Timestamptz `json:"valid_until"`
	Docs        interface{}        `json:"docs"`
}

func (q *Queries) GetAllExports(ctx context.Context) ([]GetAllExportsRow, error) {
	rows, err := q.db.Query(ctx, getAllExports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllExportsRow
	for rows.Next() {
		var i GetAllExportsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.DateCreated,
			&i.ValidUntil,
			&i.Docs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExportDocObjectKey = `-- name: GetExportDocObjectKey :one
SELECT object_key FROM privacy_export_document WHERE id = $1
`

func (q *Queries) GetExportDocObjectKey(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getExportDocObjectKey, id)
	var object_key string
	err := row.Scan(&object_key)
	return object_key, err
}

const getExportDocObjectKeysByExportID = `-- name: GetExportDocObjectKeysByExportID :many
SELECT object_key FROM privacy_export_document WHERE export_id = $1
`

func (q *Queries) GetExportDocObjectKeysByExportID(ctx context.Context, exportID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getExportDocObjectKeysByExportID, exportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var object_key string
		if err := rows.Scan(&object_key); err != nil {
			return nil, err
		}
		items = append(items, object_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExportRecordByID = `-- name: GetExportRecordByID :one
SELECT id, user_id, student_id, status, date_created, valid_until FROM privacy_export WHERE id = $1 LIMIT 1
`

func (q *Queries) GetExportRecordByID(ctx context.Context, id uuid.UUID) (PrivacyExport, error) {
	row := q.db.QueryRow(ctx, getExportRecordByID, id)
	var i PrivacyExport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudentID,
		&i.Status,
		&i.DateCreated,
		&i.ValidUntil,
	)
	return i, err
}

const getExportRecordByIDWithDocs = `-- name: GetExportRecordByIDWithDocs :one
SELECT id, user_id, student_id, status, date_created, valid_until, documents FROM privacy_export_with_docs WHERE id = $1
`

func (q *Queries) GetExportRecordByIDWithDocs(ctx context.Context, id uuid.UUID) (PrivacyExportWithDoc, error) {
	row := q.db.QueryRow(ctx, getExportRecordByIDWithDocs, id)
	var i PrivacyExportWithDoc
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudentID,
		&i.Status,
		&i.DateCreated,
		&i.ValidUntil,
		&i.Documents,
	)
	return i, err
}

const getInvalidExports = `-- name: GetInvalidExports :many
SELECT id, user_id, student_id, status, date_created, valid_until FROM privacy_export WHERE now() >= valid_until AND status != 'archived'
`

func (q *Queries) GetInvalidExports(ctx context.Context) ([]PrivacyExport, error) {
	rows, err := q.db.Query(ctx, getInvalidExports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrivacyExport
	for rows.Next() {
		var i PrivacyExport
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StudentID,
			&i.Status,
			&i.DateCreated,
			&i.ValidUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestExportForUserForUpdate = `-- name: GetLatestExportForUserForUpdate :one
SELECT id, user_id, student_id, status, date_created, valid_until FROM privacy_export WHERE user_id = $1 ORDER BY date_created DESC LIMIT 1 FOR UPDATE
`

func (q *Queries) GetLatestExportForUserForUpdate(ctx context.Context, userID uuid.UUID) (PrivacyExport, error) {
	row := q.db.QueryRow(ctx, getLatestExportForUserForUpdate, userID)
	var i PrivacyExport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudentID,
		&i.Status,
		&i.DateCreated,
		&i.ValidUntil,
	)
	return i, err
}

const getLatestExportForUserWithDocs = `-- name: GetLatestExportForUserWithDocs :one
SELECT id, user_id, student_id, status, date_created, valid_until, documents FROM privacy_export_with_docs WHERE user_id = $1 ORDER BY date_created DESC LIMIT 1
`

func (q *Queries) GetLatestExportForUserWithDocs(ctx context.Context, userID uuid.UUID) (PrivacyExportWithDoc, error) {
	row := q.db.QueryRow(ctx, getLatestExportForUserWithDocs, userID)
	var i PrivacyExportWithDoc
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudentID,
		&i.Status,
		&i.DateCreated,
		&i.ValidUntil,
		&i.Documents,
	)
	return i, err
}

const setExportDocDownloadedAt = `-- name: SetExportDocDownloadedAt :exec
UPDATE privacy_export_document SET downloaded_at = now() WHERE id = $1 AND downloaded_at IS NULL
`

func (q *Queries) SetExportDocDownloadedAt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setExportDocDownloadedAt, id)
	return err
}

const setExportDocFileSize = `-- name: SetExportDocFileSize :one
UPDATE privacy_export_document SET file_size = $2 WHERE id = $1 RETURNING id, export_id, date_created, source_name, object_key, status, file_size, downloaded_at
`

type SetExportDocFileSizeParams struct {
	ID       uuid.UUID   `json:"id"`
	FileSize pgtype.Int8 `json:"file_size"`
}

func (q *Queries) SetExportDocFileSize(ctx context.Context, arg SetExportDocFileSizeParams) (PrivacyExportDocument, error) {
	row := q.db.QueryRow(ctx, setExportDocFileSize, arg.ID, arg.FileSize)
	var i PrivacyExportDocument
	err := row.Scan(
		&i.ID,
		&i.ExportID,
		&i.DateCreated,
		&i.SourceName,
		&i.ObjectKey,
		&i.Status,
		&i.FileSize,
		&i.DownloadedAt,
	)
	return i, err
}

const setExportDocStatus = `-- name: SetExportDocStatus :one
UPDATE privacy_export_document SET status = $2 WHERE id = $1 RETURNING id, export_id, date_created, source_name, object_key, status, file_size, downloaded_at
`

type SetExportDocStatusParams struct {
	ID     uuid.UUID    `json:"id"`
	Status ExportStatus `json:"status"`
}

func (q *Queries) SetExportDocStatus(ctx context.Context, arg SetExportDocStatusParams) (PrivacyExportDocument, error) {
	row := q.db.QueryRow(ctx, setExportDocStatus, arg.ID, arg.Status)
	var i PrivacyExportDocument
	err := row.Scan(
		&i.ID,
		&i.ExportID,
		&i.DateCreated,
		&i.SourceName,
		&i.ObjectKey,
		&i.Status,
		&i.FileSize,
		&i.DownloadedAt,
	)
	return i, err
}

const setExportDocStatusByExportID = `-- name: SetExportDocStatusByExportID :exec
UPDATE privacy_export_document SET status = $2 WHERE export_id = $1
`

type SetExportDocStatusByExportIDParams struct {
	ExportID pgtype.UUID  `json:"export_id"`
	Status   ExportStatus `json:"status"`
}

func (q *Queries) SetExportDocStatusByExportID(ctx context.Context, arg SetExportDocStatusByExportIDParams) error {
	_, err := q.db.Exec(ctx, setExportDocStatusByExportID, arg.ExportID, arg.Status)
	return err
}

const setExportStatus = `-- name: SetExportStatus :one
UPDATE privacy_export SET status = $2 WHERE id = $1 RETURNING id, user_id, student_id, status, date_created, valid_until
`

type SetExportStatusParams struct {
	ID     uuid.UUID    `json:"id"`
	Status ExportStatus `json:"status"`
}

func (q *Queries) SetExportStatus(ctx context.Context, arg SetExportStatusParams) (PrivacyExport, error) {
	row := q.db.QueryRow(ctx, setExportStatus, arg.ID, arg.Status)
	var i PrivacyExport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudentID,
		&i.Status,
		&i.DateCreated,
		&i.ValidUntil,
	)
	return i, err
}
