// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile_picture.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteProfilePictureByUserID = `-- name: DeleteProfilePictureByUserID :exec
DELETE FROM profile_picture
WHERE user_id = $1
`

func (q *Queries) DeleteProfilePictureByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProfilePictureByUserID, userID)
	return err
}

const getProfilePictureByUserID = `-- name: GetProfilePictureByUserID :one
SELECT pp.user_id, pp.university_login, pp.file_id, pp.updated_at, f.storage_key
FROM profile_picture pp
JOIN files f ON f.id = pp.file_id
WHERE pp.user_id = $1
`

type GetProfilePictureByUserIDRow struct {
	UserID          uuid.UUID        `json:"user_id"`
	UniversityLogin pgtype.Text      `json:"university_login"`
	FileID          uuid.UUID        `json:"file_id"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	StorageKey      string           `json:"storage_key"`
}

func (q *Queries) GetProfilePictureByUserID(ctx context.Context, userID uuid.UUID) (GetProfilePictureByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getProfilePictureByUserID, userID)
	var i GetProfilePictureByUserIDRow
	err := row.Scan(
		&i.UserID,
		&i.UniversityLogin,
		&i.FileID,
		&i.UpdatedAt,
		&i.StorageKey,
	)
	return i, err
}

const getProfilePictureFileIDsForStudent = `-- name: GetProfilePictureFileIDsForStudent :many
SELECT pp.file_id
FROM profile_picture pp
JOIN student s ON s.university_login = pp.university_login
WHERE s.id = $1
`

func (q *Queries) GetProfilePictureFileIDsForStudent(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getProfilePictureFileIDsForStudent, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var file_id uuid.UUID
		if err := rows.Scan(&file_id); err != nil {
			return nil, err
		}
		items = append(items, file_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfilePictureStorageKeysByCourseParticipationIDs = `-- name: GetProfilePictureStorageKeysByCourseParticipationIDs :many
SELECT DISTINCT ON (cp.id) cp.id AS course_participation_id, f.storage_key
FROM course_participation cp
JOIN student s ON s.id = cp.student_id
JOIN profile_picture pp ON pp.university_login = s.university_login
JOIN files f ON f.id = pp.file_id
WHERE cp.id = ANY($1::uuid[])
ORDER BY cp.id, pp.updated_at DESC
`

type GetProfilePictureStorageKeysByCourseParticipationIDsRow struct {
	CourseParticipationID uuid.UUID `json:"course_participation_id"`
	StorageKey            string    `json:"storage_key"`
}

func (q *Queries) GetProfilePictureStorageKeysByCourseParticipationIDs(ctx context.Context, courseParticipationIds []uuid.UUID) ([]GetProfilePictureStorageKeysByCourseParticipationIDsRow, error) {
	rows, err := q.db.Query(ctx, getProfilePictureStorageKeysByCourseParticipationIDs, courseParticipationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProfilePictureStorageKeysByCourseParticipationIDsRow
	for rows.Next() {
		var i GetProfilePictureStorageKeysByCourseParticipationIDsRow
		if err := rows.Scan(&i.CourseParticipationID, &i.StorageKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfilePictureStorageKeysByStudentIDs = `-- name: GetProfilePictureStorageKeysByStudentIDs :many
SELECT DISTINCT ON (s.id) s.id AS student_id, f.storage_key
FROM student s
JOIN profile_picture pp ON pp.university_login = s.university_login
JOIN files f ON f.id = pp.file_id
WHERE s.id = ANY($1::uuid[])
ORDER BY s.id, pp.updated_at DESC
`

type GetProfilePictureStorageKeysByStudentIDsRow struct {
	StudentID  uuid.UUID `json:"student_id"`
	StorageKey string    `json:"storage_key"`
}

// If several accounts share a university login, the most recent upload wins.
func (q *Queries) GetProfilePictureStorageKeysByStudentIDs(ctx context.Context, studentIds []uuid.UUID) ([]GetProfilePictureStorageKeysByStudentIDsRow, error) {
	rows, err := q.db.Query(ctx, getProfilePictureStorageKeysByStudentIDs, studentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProfilePictureStorageKeysByStudentIDsRow
	for rows.Next() {
		var i GetProfilePictureStorageKeysByStudentIDsRow
		if err := rows.Scan(&i.StudentID, &i.StorageKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfilePictureStorageKeysByUserIDs = `-- name: GetProfilePictureStorageKeysByUserIDs :many
SELECT pp.user_id, f.storage_key
FROM profile_picture pp
JOIN files f ON f.id = pp.file_id
WHERE pp.user_id = ANY($1::uuid[])
`

type GetProfilePictureStorageKeysByUserIDsRow struct {
	UserID     uuid.UUID `json:"user_id"`
	StorageKey string    `json:"storage_key"`
}

func (q *Queries) GetProfilePictureStorageKeysByUserIDs(ctx context.Context, userIds []uuid.UUID) ([]GetProfilePictureStorageKeysByUserIDsRow, error) {
	rows, err := q.db.Query(ctx, getProfilePictureStorageKeysByUserIDs, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProfilePictureStorageKeysByUserIDsRow
	for rows.Next() {
		var i GetProfilePictureStorageKeysByUserIDsRow
		if err := rows.Scan(&i.UserID, &i.StorageKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProfilePicture = `-- name: UpsertProfilePicture :one
INSERT INTO profile_picture (user_id, university_login, file_id)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE
SET university_login = EXCLUDED.university_login,
    file_id          = EXCLUDED.file_id,
    updated_at       = CURRENT_TIMESTAMP
RETURNING user_id, university_login, file_id, created_at, updated_at
`

type UpsertProfilePictureParams struct {
	UserID          uuid.UUID   `json:"user_id"`
	UniversityLogin pgtype.Text `json:"university_login"`
	FileID          uuid.UUID   `json:"file_id"`
}

func (q *Queries) UpsertProfilePicture(ctx context.Context, arg UpsertProfilePictureParams) (ProfilePicture, error) {
	row := q.db.QueryRow(ctx, upsertProfilePicture, arg.UserID, arg.UniversityLogin, arg.FileID)
	var i ProfilePicture
	err := row.Scan(
		&i.UserID,
		&i.UniversityLogin,
		&i.FileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
