// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: privacy.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getAssignmentsByParticipationIDs = `-- name: GetAssignmentsByParticipationIDs :many
SELECT id, course_participation_id, team_id, course_phase_id, created_at, updated_at, student_first_name, student_last_name
FROM assignments
WHERE course_participation_id = ANY($1::uuid[])
ORDER BY created_at ASC
`

func (q *Queries) GetAssignmentsByParticipationIDs(ctx context.Context, courseParticipationIds []uuid.UUID) ([]Assignment, error) {
	rows, err := q.db.Query(ctx, getAssignmentsByParticipationIDs, courseParticipationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assignment
	for rows.Next() {
		var i Assignment
		if err := rows.Scan(
			&i.ID,
			&i.CourseParticipationID,
			&i.TeamID,
			&i.CoursePhaseID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StudentFirstName,
			&i.StudentLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
