// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: coursePhaseDeletion.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteSkillsByCoursePhase = `-- name: DeleteSkillsByCoursePhase :exec
DELETE
FROM skill
WHERE course_phase_id = $1
`

// Deletes every skill of the course phase. student_skill_response (skill_id) is removed by its
// ON DELETE CASCADE constraint.
func (q *Queries) DeleteSkillsByCoursePhase(ctx context.Context, coursePhaseID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSkillsByCoursePhase, coursePhaseID)
	return err
}

const deleteSurveyTimeframeByCoursePhase = `-- name: DeleteSurveyTimeframeByCoursePhase :exec
DELETE
FROM survey_timeframe
WHERE course_phase_id = $1
`

func (q *Queries) DeleteSurveyTimeframeByCoursePhase(ctx context.Context, coursePhaseID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSurveyTimeframeByCoursePhase, coursePhaseID)
	return err
}

const deleteTeamsByCoursePhase = `-- name: DeleteTeamsByCoursePhase :exec
DELETE
FROM team
WHERE course_phase_id = $1
`

// Deletes every team of the course phase. The ON DELETE CASCADE constraints declared in
// db/migration/ clean up student_team_preference_response (team_id), allocations (team_id and
// (team_id, course_phase_id)) and tutor ((team_id, course_phase_id)) along with it. If a future
// migration drops one of those cascades, delete that table explicitly here.
func (q *Queries) DeleteTeamsByCoursePhase(ctx context.Context, coursePhaseID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeamsByCoursePhase, coursePhaseID)
	return err
}

const deleteTeaseWorkspaceByCoursePhase = `-- name: DeleteTeaseWorkspaceByCoursePhase :exec
DELETE
FROM tease_workspace
WHERE course_phase_id = $1
`

func (q *Queries) DeleteTeaseWorkspaceByCoursePhase(ctx context.Context, coursePhaseID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeaseWorkspaceByCoursePhase, coursePhaseID)
	return err
}
