// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: privacy.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAllocationsByCourseParticipationIDs = `-- name: DeleteAllocationsByCourseParticipationIDs :exec
DELETE FROM allocations
WHERE course_participation_id = ANY($1::uuid[])
`

func (q *Queries) DeleteAllocationsByCourseParticipationIDs(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllocationsByCourseParticipationIDs, dollar_1)
	return err
}

const deleteStudentSkillResponseByCourseParticipationIDs = `-- name: DeleteStudentSkillResponseByCourseParticipationIDs :exec
DELETE FROM student_skill_response
WHERE course_participation_id = ANY($1::uuid[])
`

func (q *Queries) DeleteStudentSkillResponseByCourseParticipationIDs(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStudentSkillResponseByCourseParticipationIDs, dollar_1)
	return err
}

const deleteStudentTeamPreferenceResponseByCourseParticipationIDs = `-- name: DeleteStudentTeamPreferenceResponseByCourseParticipationIDs :exec
DELETE FROM student_team_preference_response
WHERE course_participation_id = ANY($1::uuid[])
`

func (q *Queries) DeleteStudentTeamPreferenceResponseByCourseParticipationIDs(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStudentTeamPreferenceResponseByCourseParticipationIDs, dollar_1)
	return err
}

const deleteTutorByCourseParticipationIDs = `-- name: DeleteTutorByCourseParticipationIDs :exec
DELETE FROM tutor
WHERE course_participation_id = ANY($1::uuid[])
`

func (q *Queries) DeleteTutorByCourseParticipationIDs(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTutorByCourseParticipationIDs, dollar_1)
	return err
}

const getAllocationByCourseParticipationIDs = `-- name: GetAllocationByCourseParticipationIDs :many
SELECT a.id, a.course_participation_id, a.team_id, a.course_phase_id, a.created_at, a.updated_at, a.student_first_name, a.student_last_name, t.id, t.name, t.course_phase_id, t.created_at
FROM allocations a, team t
WHERE a.course_participation_id = ANY($1::uuid[])
AND a.team_id = t.id
`

type GetAllocationByCourseParticipationIDsRow struct {
	ID                    uuid.UUID        `json:"id"`
	CourseParticipationID uuid.UUID        `json:"course_participation_id"`
	TeamID                uuid.UUID        `json:"team_id"`
	CoursePhaseID         uuid.UUID        `json:"course_phase_id"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
	StudentFirstName      string           `json:"student_first_name"`
	StudentLastName       string           `json:"student_last_name"`
	ID_2                  uuid.UUID        `json:"id_2"`
	Name                  string           `json:"name"`
	CoursePhaseID_2       uuid.UUID        `json:"course_phase_id_2"`
	CreatedAt_2           pgtype.Timestamp `json:"created_at_2"`
}

func (q *Queries) GetAllocationByCourseParticipationIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetAllocationByCourseParticipationIDsRow, error) {
	rows, err := q.db.Query(ctx, getAllocationByCourseParticipationIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllocationByCourseParticipationIDsRow
	for rows.Next() {
		var i GetAllocationByCourseParticipationIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseParticipationID,
			&i.TeamID,
			&i.CoursePhaseID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StudentFirstName,
			&i.StudentLastName,
			&i.ID_2,
			&i.Name,
			&i.CoursePhaseID_2,
			&i.CreatedAt_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentSkillResponseByCourseParticipationIDs = `-- name: GetStudentSkillResponseByCourseParticipationIDs :many
SELECT sr.course_participation_id, sr.skill_id, sr.skill_level, s.id, s.course_phase_id, s.name
FROM student_skill_response sr, skill s
WHERE s.id = sr.skill_id
AND sr.course_participation_id = ANY($1::uuid[])
`

type GetStudentSkillResponseByCourseParticipationIDsRow struct {
	CourseParticipationID uuid.UUID  `json:"course_participation_id"`
	SkillID               uuid.UUID  `json:"skill_id"`
	SkillLevel            SkillLevel `json:"skill_level"`
	ID                    uuid.UUID  `json:"id"`
	CoursePhaseID         uuid.UUID  `json:"course_phase_id"`
	Name                  string     `json:"name"`
}

func (q *Queries) GetStudentSkillResponseByCourseParticipationIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetStudentSkillResponseByCourseParticipationIDsRow, error) {
	rows, err := q.db.Query(ctx, getStudentSkillResponseByCourseParticipationIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentSkillResponseByCourseParticipationIDsRow
	for rows.Next() {
		var i GetStudentSkillResponseByCourseParticipationIDsRow
		if err := rows.Scan(
			&i.CourseParticipationID,
			&i.SkillID,
			&i.SkillLevel,
			&i.ID,
			&i.CoursePhaseID,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentTeamPreferenceResponseByCourseParticipationIDs = `-- name: GetStudentTeamPreferenceResponseByCourseParticipationIDs :many
SELECT spr.course_participation_id, spr.team_id, spr.preference, t.id, t.name, t.course_phase_id, t.created_at
FROM student_team_preference_response spr, team t
WHERE course_participation_id = ANY($1::uuid[])
AND spr.team_id = t.id
`

type GetStudentTeamPreferenceResponseByCourseParticipationIDsRow struct {
	CourseParticipationID uuid.UUID        `json:"course_participation_id"`
	TeamID                uuid.UUID        `json:"team_id"`
	Preference            int32            `json:"preference"`
	ID                    uuid.UUID        `json:"id"`
	Name                  string           `json:"name"`
	CoursePhaseID         uuid.UUID        `json:"course_phase_id"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetStudentTeamPreferenceResponseByCourseParticipationIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetStudentTeamPreferenceResponseByCourseParticipationIDsRow, error) {
	rows, err := q.db.Query(ctx, getStudentTeamPreferenceResponseByCourseParticipationIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentTeamPreferenceResponseByCourseParticipationIDsRow
	for rows.Next() {
		var i GetStudentTeamPreferenceResponseByCourseParticipationIDsRow
		if err := rows.Scan(
			&i.CourseParticipationID,
			&i.TeamID,
			&i.Preference,
			&i.ID,
			&i.Name,
			&i.CoursePhaseID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTutorByCourseParticipationIDs = `-- name: GetTutorByCourseParticipationIDs :many
SELECT t.course_phase_id, t.course_participation_id, t.first_name, t.last_name, t.team_id, t.university_login
FROM tutor t
WHERE t.course_participation_id = ANY($1::uuid[])
`

func (q *Queries) GetTutorByCourseParticipationIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Tutor, error) {
	rows, err := q.db.Query(ctx, getTutorByCourseParticipationIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tutor
	for rows.Next() {
		var i Tutor
		if err := rows.Scan(
			&i.CoursePhaseID,
			&i.CourseParticipationID,
			&i.FirstName,
			&i.LastName,
			&i.TeamID,
			&i.UniversityLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
