// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: survey.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteStudentSkillResponses = `-- name: DeleteStudentSkillResponses :exec
DELETE FROM student_skill_response
WHERE course_participation_id = $1
AND skill_id IN (
    SELECT id
    FROM skill
    WHERE course_phase_id = $2
)
`

type DeleteStudentSkillResponsesParams struct {
	CourseParticipationID uuid.UUID `json:"course_participation_id"`
	CoursePhaseID         uuid.UUID `json:"course_phase_id"`
}

// Deletes all student skill responses (for overwriting answers).
func (q *Queries) DeleteStudentSkillResponses(ctx context.Context, arg DeleteStudentSkillResponsesParams) error {
	_, err := q.db.Exec(ctx, deleteStudentSkillResponses, arg.CourseParticipationID, arg.CoursePhaseID)
	return err
}

const deleteStudentTeamPreferences = `-- name: DeleteStudentTeamPreferences :exec
DELETE FROM student_team_preference_response
WHERE course_participation_id = $1
AND team_id IN (
    SELECT id
    FROM team
    WHERE course_phase_id = $2
)
`

type DeleteStudentTeamPreferencesParams struct {
	CourseParticipationID uuid.UUID `json:"course_participation_id"`
	CoursePhaseID         uuid.UUID `json:"course_phase_id"`
}

// Deletes all student team preference responses (for overwriting answers).
func (q *Queries) DeleteStudentTeamPreferences(ctx context.Context, arg DeleteStudentTeamPreferencesParams) error {
	_, err := q.db.Exec(ctx, deleteStudentTeamPreferences, arg.CourseParticipationID, arg.CoursePhaseID)
	return err
}

const getSkillDistributionStatistics = `-- name: GetSkillDistributionStatistics :many
SELECT
    s.id AS skill_id,
    s.name AS skill_name,
    r.skill_level,
    COUNT(r.course_participation_id) AS count
FROM skill s
JOIN student_skill_response r ON r.skill_id = s.id
WHERE s.course_phase_id = $1
GROUP BY s.id, s.name, r.skill_level
ORDER BY s.name, r.skill_level
`

type GetSkillDistributionStatisticsRow struct {
	SkillID    uuid.UUID  `json:"skill_id"`
	SkillName  string     `json:"skill_name"`
	SkillLevel SkillLevel `json:"skill_level"`
	Count      int64      `json:"count"`
}

// Returns skill distribution statistics aggregated by skill and proficiency level.
func (q *Queries) GetSkillDistributionStatistics(ctx context.Context, coursePhaseID uuid.UUID) ([]GetSkillDistributionStatisticsRow, error) {
	rows, err := q.db.Query(ctx, getSkillDistributionStatistics, coursePhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSkillDistributionStatisticsRow
	for rows.Next() {
		var i GetSkillDistributionStatisticsRow
		if err := rows.Scan(
			&i.SkillID,
			&i.SkillName,
			&i.SkillLevel,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentSkillResponses = `-- name: GetStudentSkillResponses :many
SELECT skill_id, skill_level
FROM student_skill_response
JOIN skill ON skill.id = student_skill_response.skill_id
WHERE course_participation_id = $1
AND skill.course_phase_id = $2
`

type GetStudentSkillResponsesParams struct {
	CourseParticipationID uuid.UUID `json:"course_participation_id"`
	CoursePhaseID         uuid.UUID `json:"course_phase_id"`
}

type GetStudentSkillResponsesRow struct {
	SkillID    uuid.UUID  `json:"skill_id"`
	SkillLevel SkillLevel `json:"skill_level"`
}

// Returns the student’s skill responses.
func (q *Queries) GetStudentSkillResponses(ctx context.Context, arg GetStudentSkillResponsesParams) ([]GetStudentSkillResponsesRow, error) {
	rows, err := q.db.Query(ctx, getStudentSkillResponses, arg.CourseParticipationID, arg.CoursePhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentSkillResponsesRow
	for rows.Next() {
		var i GetStudentSkillResponsesRow
		if err := rows.Scan(&i.SkillID, &i.SkillLevel); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentTeamPreferences = `-- name: GetStudentTeamPreferences :many
SELECT team_id, preference
FROM student_team_preference_response
JOIN team ON team.id = student_team_preference_response.team_id
WHERE course_participation_id = $1
AND team.course_phase_id = $2
`

type GetStudentTeamPreferencesParams struct {
	CourseParticipationID uuid.UUID `json:"course_participation_id"`
	CoursePhaseID         uuid.UUID `json:"course_phase_id"`
}

type GetStudentTeamPreferencesRow struct {
	TeamID     uuid.UUID `json:"team_id"`
	Preference int32     `json:"preference"`
}

// Returns the student’s team preference responses.
func (q *Queries) GetStudentTeamPreferences(ctx context.Context, arg GetStudentTeamPreferencesParams) ([]GetStudentTeamPreferencesRow, error) {
	rows, err := q.db.Query(ctx, getStudentTeamPreferences, arg.CourseParticipationID, arg.CoursePhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentTeamPreferencesRow
	for rows.Next() {
		var i GetStudentTeamPreferencesRow
		if err := rows.Scan(&i.TeamID, &i.Preference); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSurveyTimeframe = `-- name: GetSurveyTimeframe :one
SELECT survey_start, survey_deadline
FROM survey_timeframe
WHERE course_phase_id = $1
`

type GetSurveyTimeframeRow struct {
	SurveyStart    pgtype.Timestamp `json:"survey_start"`
	SurveyDeadline pgtype.Timestamp `json:"survey_deadline"`
}

// Returns the survey timeframe (survey_start and survey_deadline) for a course phase.
func (q *Queries) GetSurveyTimeframe(ctx context.Context, coursePhaseID uuid.UUID) (GetSurveyTimeframeRow, error) {
	row := q.db.QueryRow(ctx, getSurveyTimeframe, coursePhaseID)
	var i GetSurveyTimeframeRow
	err := row.Scan(&i.SurveyStart, &i.SurveyDeadline)
	return i, err
}

const getTeamPopularityStatistics = `-- name: GetTeamPopularityStatistics :many
SELECT
    t.id AS team_id,
    t.name AS team_name,
    COALESCE(AVG(r.preference), 0)::float8 AS avg_preference,
    COALESCE(COUNT(r.course_participation_id), 0)::bigint AS response_count
FROM team t
LEFT JOIN student_team_preference_response r ON r.team_id = t.id
WHERE t.course_phase_id = $1
GROUP BY t.id, t.name
ORDER BY avg_preference ASC
`

type GetTeamPopularityStatisticsRow struct {
	TeamID        uuid.UUID `json:"team_id"`
	TeamName      string    `json:"team_name"`
	AvgPreference float64   `json:"avg_preference"`
	ResponseCount int64     `json:"response_count"`
}

// Returns team popularity as average preference rank per team (lower = more popular).
func (q *Queries) GetTeamPopularityStatistics(ctx context.Context, coursePhaseID uuid.UUID) ([]GetTeamPopularityStatisticsRow, error) {
	rows, err := q.db.Query(ctx, getTeamPopularityStatistics, coursePhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamPopularityStatisticsRow
	for rows.Next() {
		var i GetTeamPopularityStatisticsRow
		if err := rows.Scan(
			&i.TeamID,
			&i.TeamName,
			&i.AvgPreference,
			&i.ResponseCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamPreferenceCounts = `-- name: GetTeamPreferenceCounts :many
SELECT
    t.id AS team_id,
    r.preference,
    COUNT(r.course_participation_id)::int AS count
FROM student_team_preference_response r
JOIN team t ON t.id = r.team_id
WHERE t.course_phase_id = $1
GROUP BY t.id, r.preference
ORDER BY t.id, r.preference
`

type GetTeamPreferenceCountsRow struct {
	TeamID     uuid.UUID `json:"team_id"`
	Preference int32     `json:"preference"`
	Count      int32     `json:"count"`
}

// Returns per-rank student counts per team for tooltip breakdown.
func (q *Queries) GetTeamPreferenceCounts(ctx context.Context, coursePhaseID uuid.UUID) ([]GetTeamPreferenceCountsRow, error) {
	rows, err := q.db.Query(ctx, getTeamPreferenceCounts, coursePhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamPreferenceCountsRow
	for rows.Next() {
		var i GetTeamPreferenceCountsRow
		if err := rows.Scan(&i.TeamID, &i.Preference, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertStudentSkillResponse = `-- name: InsertStudentSkillResponse :exec
INSERT INTO student_skill_response (course_participation_id, skill_id, skill_level)
VALUES ($1, $2, $3)
`

type InsertStudentSkillResponseParams struct {
	CourseParticipationID uuid.UUID  `json:"course_participation_id"`
	SkillID               uuid.UUID  `json:"skill_id"`
	SkillLevel            SkillLevel `json:"skill_level"`
}

// Inserts a new student skill response.
func (q *Queries) InsertStudentSkillResponse(ctx context.Context, arg InsertStudentSkillResponseParams) error {
	_, err := q.db.Exec(ctx, insertStudentSkillResponse, arg.CourseParticipationID, arg.SkillID, arg.SkillLevel)
	return err
}

const insertStudentTeamPreference = `-- name: InsertStudentTeamPreference :exec
INSERT INTO student_team_preference_response (course_participation_id, team_id, preference)
VALUES ($1, $2, $3)
`

type InsertStudentTeamPreferenceParams struct {
	CourseParticipationID uuid.UUID `json:"course_participation_id"`
	TeamID                uuid.UUID `json:"team_id"`
	Preference            int32     `json:"preference"`
}

// Inserts a new student team preference.
func (q *Queries) InsertStudentTeamPreference(ctx context.Context, arg InsertStudentTeamPreferenceParams) error {
	_, err := q.db.Exec(ctx, insertStudentTeamPreference, arg.CourseParticipationID, arg.TeamID, arg.Preference)
	return err
}

const setSurveyTimeframe = `-- name: SetSurveyTimeframe :exec
INSERT INTO survey_timeframe (course_phase_id, survey_start, survey_deadline)
VALUES ($1, $2, $3)
ON CONFLICT (course_phase_id)
DO UPDATE SET survey_start = EXCLUDED.survey_start,
              survey_deadline = EXCLUDED.survey_deadline
`

type SetSurveyTimeframeParams struct {
	CoursePhaseID  uuid.UUID        `json:"course_phase_id"`
	SurveyStart    pgtype.Timestamp `json:"survey_start"`
	SurveyDeadline pgtype.Timestamp `json:"survey_deadline"`
}

// Upsert the survey timeframe for a given course phase.
func (q *Queries) SetSurveyTimeframe(ctx context.Context, arg SetSurveyTimeframeParams) error {
	_, err := q.db.Exec(ctx, setSurveyTimeframe, arg.CoursePhaseID, arg.SurveyStart, arg.SurveyDeadline)
	return err
}
