// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tease.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSurveyDeadline = `-- name: GetSurveyDeadline :one
SELECT survey_deadline
FROM survey_timeframe
WHERE course_phase_id = $1
`

func (q *Queries) GetSurveyDeadline(ctx context.Context, coursePhaseID uuid.UUID) (pgtype.Timestamp, error) {
	row := q.db.QueryRow(ctx, getSurveyDeadline, coursePhaseID)
	var survey_deadline pgtype.Timestamp
	err := row.Scan(&survey_deadline)
	return survey_deadline, err
}
