// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: key.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deletePhaseKey = `-- name: DeletePhaseKey :exec
DELETE
FROM ai_phase_key
WHERE course_phase_id = $1
`

func (q *Queries) DeletePhaseKey(ctx context.Context, coursePhaseID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePhaseKey, coursePhaseID)
	return err
}

const getPhaseKey = `-- name: GetPhaseKey :one
SELECT course_phase_id, phase_type, encrypted_key, last4, set_by, set_at
FROM ai_phase_key
WHERE course_phase_id = $1
`

func (q *Queries) GetPhaseKey(ctx context.Context, coursePhaseID uuid.UUID) (AiPhaseKey, error) {
	row := q.db.QueryRow(ctx, getPhaseKey, coursePhaseID)
	var i AiPhaseKey
	err := row.Scan(
		&i.CoursePhaseID,
		&i.PhaseType,
		&i.EncryptedKey,
		&i.Last4,
		&i.SetBy,
		&i.SetAt,
	)
	return i, err
}

const upsertPhaseKey = `-- name: UpsertPhaseKey :one
INSERT INTO ai_phase_key (course_phase_id, phase_type, encrypted_key, last4, set_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (course_phase_id) DO UPDATE
SET phase_type    = EXCLUDED.phase_type,
    encrypted_key = EXCLUDED.encrypted_key,
    last4         = EXCLUDED.last4,
    set_by        = EXCLUDED.set_by,
    set_at        = now()
RETURNING course_phase_id, phase_type, encrypted_key, last4, set_by, set_at
`

type UpsertPhaseKeyParams struct {
	CoursePhaseID uuid.UUID `json:"course_phase_id"`
	PhaseType     string    `json:"phase_type"`
	EncryptedKey  []byte    `json:"encrypted_key"`
	Last4         string    `json:"last4"`
	SetBy         string    `json:"set_by"`
}

func (q *Queries) UpsertPhaseKey(ctx context.Context, arg UpsertPhaseKeyParams) (AiPhaseKey, error) {
	row := q.db.QueryRow(ctx, upsertPhaseKey,
		arg.CoursePhaseID,
		arg.PhaseType,
		arg.EncryptedKey,
		arg.Last4,
		arg.SetBy,
	)
	var i AiPhaseKey
	err := row.Scan(
		&i.CoursePhaseID,
		&i.PhaseType,
		&i.EncryptedKey,
		&i.Last4,
		&i.SetBy,
		&i.SetAt,
	)
	return i, err
}
