// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AiCall struct {
	ID               uuid.UUID          `json:"id"`
	CoursePhaseID    uuid.UUID          `json:"course_phase_id"`
	ActorID          string             `json:"actor_id"`
	ActorRole        string             `json:"actor_role"`
	Feature          string             `json:"feature"`
	Template         pgtype.Text        `json:"template"`
	TemplateVersion  pgtype.Text        `json:"template_version"`
	RequestedModel   pgtype.Text        `json:"requested_model"`
	ServedModel      pgtype.Text        `json:"served_model"`
	Provider         string             `json:"provider"`
	Params           []byte             `json:"params"`
	ContextHash      pgtype.Text        `json:"context_hash"`
	ResponseHash     pgtype.Text        `json:"response_hash"`
	Outcome          string             `json:"outcome"`
	HttpStatus       pgtype.Int4        `json:"http_status"`
	FinishReason     pgtype.Text        `json:"finish_reason"`
	ErrorCode        pgtype.Text        `json:"error_code"`
	PromptTokens     pgtype.Int4        `json:"prompt_tokens"`
	CompletionTokens pgtype.Int4        `json:"completion_tokens"`
	Streamed         bool               `json:"streamed"`
	ServerVersion    string             `json:"server_version"`
	RequestedAt      pgtype.Timestamptz `json:"requested_at"`
	FirstTokenAt     pgtype.Timestamptz `json:"first_token_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
}

type AiCallContent struct {
	CallID   uuid.UUID `json:"call_id"`
	Request  []byte    `json:"request"`
	Response []byte    `json:"response"`
}

type AiCallContentRestriction struct {
	CallID       uuid.UUID          `json:"call_id"`
	RestrictedAt pgtype.Timestamptz `json:"restricted_at"`
}

type AiCallEvent struct {
	ID        uuid.UUID          `json:"id"`
	CallID    uuid.UUID          `json:"call_id"`
	ActorID   string             `json:"actor_id"`
	Type      string             `json:"type"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AiCallSubject struct {
	CallID                uuid.UUID `json:"call_id"`
	CourseParticipationID uuid.UUID `json:"course_participation_id"`
}

type AiPhaseKey struct {
	CoursePhaseID uuid.UUID          `json:"course_phase_id"`
	PhaseType     string             `json:"phase_type"`
	EncryptedKey  []byte             `json:"encrypted_key"`
	Last4         string             `json:"last4"`
	SetBy         string             `json:"set_by"`
	SetAt         pgtype.Timestamptz `json:"set_at"`
}
