// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: privacy.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSubjectCallContents = `-- name: DeleteSubjectCallContents :exec
WITH deleted_subjects AS (DELETE
                          FROM ai_call_subject
                          WHERE call_id = ANY ($1::uuid[])
                            AND course_participation_id = ANY ($2::uuid[])),
     deleted_restrictions AS (DELETE FROM ai_call_content_restriction WHERE call_id = ANY ($1::uuid[]))
DELETE
FROM ai_call_content
WHERE call_id = ANY ($1::uuid[])
`

type DeleteSubjectCallContentsParams struct {
	CallIds                []uuid.UUID `json:"call_ids"`
	CourseParticipationIds []uuid.UUID `json:"course_participation_ids"`
}

func (q *Queries) DeleteSubjectCallContents(ctx context.Context, arg DeleteSubjectCallContentsParams) error {
	_, err := q.db.Exec(ctx, deleteSubjectCallContents, arg.CallIds, arg.CourseParticipationIds)
	return err
}

const listPrivacyCalls = `-- name: ListPrivacyCalls :many
SELECT ai_call.id,
       ai_call.course_phase_id,
       (ai_call.actor_id = $1::text)::boolean AS is_actor,
       ai_call.actor_role,
       ai_call.feature,
       ai_call.template,
       ai_call.template_version,
       ai_call.requested_model,
       ai_call.served_model,
       ai_call.outcome,
       ai_call.finish_reason,
       ai_call.prompt_tokens,
       ai_call.completion_tokens,
       ai_call.streamed,
       ai_call.requested_at,
       ai_call.completed_at,
       content.request,
       content.response,
       (restriction.call_id IS NOT NULL)::boolean AS restricted,
       EXISTS (SELECT 1
               FROM ai_call_subject subject
               WHERE subject.call_id = ai_call.id
                 AND subject.course_participation_id = ANY ($2::uuid[])) AS is_subject,
       EXISTS (SELECT 1
               FROM ai_call_subject subject
               WHERE subject.call_id = ai_call.id
                 AND NOT subject.course_participation_id = ANY ($2::uuid[])) AS has_other_subjects
FROM ai_call
         LEFT JOIN ai_call_content content ON content.call_id = ai_call.id
         LEFT JOIN ai_call_content_restriction restriction ON restriction.call_id = ai_call.id
WHERE ai_call.actor_id = $1::text
   OR ai_call.id IN (SELECT call_id
                     FROM ai_call_subject
                     WHERE course_participation_id = ANY ($2::uuid[]))
ORDER BY ai_call.requested_at, ai_call.id
`

type ListPrivacyCallsParams struct {
	ActorID                string      `json:"actor_id"`
	CourseParticipationIds []uuid.UUID `json:"course_participation_ids"`
}

type ListPrivacyCallsRow struct {
	ID               uuid.UUID          `json:"id"`
	CoursePhaseID    uuid.UUID          `json:"course_phase_id"`
	IsActor          bool               `json:"is_actor"`
	ActorRole        string             `json:"actor_role"`
	Feature          string             `json:"feature"`
	Template         pgtype.Text        `json:"template"`
	TemplateVersion  pgtype.Text        `json:"template_version"`
	RequestedModel   pgtype.Text        `json:"requested_model"`
	ServedModel      pgtype.Text        `json:"served_model"`
	Outcome          string             `json:"outcome"`
	FinishReason     pgtype.Text        `json:"finish_reason"`
	PromptTokens     pgtype.Int4        `json:"prompt_tokens"`
	CompletionTokens pgtype.Int4        `json:"completion_tokens"`
	Streamed         bool               `json:"streamed"`
	RequestedAt      pgtype.Timestamptz `json:"requested_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	Request          []byte             `json:"request"`
	Response         []byte             `json:"response"`
	Restricted       bool               `json:"restricted"`
	IsSubject        bool               `json:"is_subject"`
	HasOtherSubjects bool               `json:"has_other_subjects"`
}

// No actor id: on a call the subject did not make, it identifies the lecturer.
func (q *Queries) ListPrivacyCalls(ctx context.Context, arg ListPrivacyCallsParams) ([]ListPrivacyCallsRow, error) {
	rows, err := q.db.Query(ctx, listPrivacyCalls, arg.ActorID, arg.CourseParticipationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPrivacyCallsRow
	for rows.Next() {
		var i ListPrivacyCallsRow
		if err := rows.Scan(
			&i.ID,
			&i.CoursePhaseID,
			&i.IsActor,
			&i.ActorRole,
			&i.Feature,
			&i.Template,
			&i.TemplateVersion,
			&i.RequestedModel,
			&i.ServedModel,
			&i.Outcome,
			&i.FinishReason,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Streamed,
			&i.RequestedAt,
			&i.CompletedAt,
			&i.Request,
			&i.Response,
			&i.Restricted,
			&i.IsSubject,
			&i.HasOtherSubjects,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrivacyEvents = `-- name: ListPrivacyEvents :many
SELECT id, call_id, type, data, created_at, (actor_id = $1::text)::boolean AS is_actor
FROM ai_call_event
WHERE call_id = ANY ($2::uuid[])
ORDER BY created_at, id
`

type ListPrivacyEventsParams struct {
	ActorID string      `json:"actor_id"`
	CallIds []uuid.UUID `json:"call_ids"`
}

type ListPrivacyEventsRow struct {
	ID        uuid.UUID          `json:"id"`
	CallID    uuid.UUID          `json:"call_id"`
	Type      string             `json:"type"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	IsActor   bool               `json:"is_actor"`
}

func (q *Queries) ListPrivacyEvents(ctx context.Context, arg ListPrivacyEventsParams) ([]ListPrivacyEventsRow, error) {
	rows, err := q.db.Query(ctx, listPrivacyEvents, arg.ActorID, arg.CallIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPrivacyEventsRow
	for rows.Next() {
		var i ListPrivacyEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.CallID,
			&i.Type,
			&i.Data,
			&i.CreatedAt,
			&i.IsActor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubjectCalls = `-- name: ListSubjectCalls :many
SELECT DISTINCT ai_call.id, ai_call.feature
FROM ai_call
         JOIN ai_call_subject subject ON subject.call_id = ai_call.id
WHERE subject.course_participation_id = ANY ($1::uuid[])
`

type ListSubjectCallsRow struct {
	ID      uuid.UUID `json:"id"`
	Feature string    `json:"feature"`
}

func (q *Queries) ListSubjectCalls(ctx context.Context, courseParticipationIds []uuid.UUID) ([]ListSubjectCallsRow, error) {
	rows, err := q.db.Query(ctx, listSubjectCalls, courseParticipationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubjectCallsRow
	for rows.Next() {
		var i ListSubjectCallsRow
		if err := rows.Scan(&i.ID, &i.Feature); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restrictCallContents = `-- name: RestrictCallContents :exec
INSERT INTO ai_call_content_restriction (call_id)
SELECT unnest($1::uuid[])
ON CONFLICT (call_id) DO NOTHING
`

func (q *Queries) RestrictCallContents(ctx context.Context, callIds []uuid.UUID) error {
	_, err := q.db.Exec(ctx, restrictCallContents, callIds)
	return err
}
