// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: coursePhaseDeletion.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteCoursePhaseConfigByCoursePhase = `-- name: DeleteCoursePhaseConfigByCoursePhase :exec
DELETE FROM course_phase_config
WHERE course_phase_id = $1
`

func (q *Queries) DeleteCoursePhaseConfigByCoursePhase(ctx context.Context, coursePhaseID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCoursePhaseConfigByCoursePhase, coursePhaseID)
	return err
}

const deleteProviderConfigsByCoursePhase = `-- name: DeleteProviderConfigsByCoursePhase :exec
DELETE FROM provider_config
WHERE course_phase_id = $1
`

func (q *Queries) DeleteProviderConfigsByCoursePhase(ctx context.Context, coursePhaseID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProviderConfigsByCoursePhase, coursePhaseID)
	return err
}

const deleteResourceConfigsByCoursePhase = `-- name: DeleteResourceConfigsByCoursePhase :exec
DELETE FROM resource_config
WHERE course_phase_id = $1
`

func (q *Queries) DeleteResourceConfigsByCoursePhase(ctx context.Context, coursePhaseID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteResourceConfigsByCoursePhase, coursePhaseID)
	return err
}

const deleteResourceInstancesByCoursePhase = `-- name: DeleteResourceInstancesByCoursePhase :exec

DELETE FROM resource_instance
WHERE course_phase_id = $1
`

// Deletes every row this service stores for one course phase, called when the phase is
// permanently removed in core.
//
// The tables are deleted from the leaves up even though the schema cascades
// (resource_instance -> resource_config -> provider_config): an explicit delete per root
// table keeps the handler correct if a migration ever weakens one of those cascades, and
// the tests count the raw tables so a weakened cascade fails loudly.
func (q *Queries) DeleteResourceInstancesByCoursePhase(ctx context.Context, coursePhaseID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteResourceInstancesByCoursePhase, coursePhaseID)
	return err
}
