// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: course_phase_config.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getCoursePhaseConfig = `-- name: GetCoursePhaseConfig :one
SELECT course_phase_id, team_source_course_phase_id, student_source_course_phase_id, semester_tag
FROM course_phase_config
WHERE course_phase_id = $1
`

func (q *Queries) GetCoursePhaseConfig(ctx context.Context, coursePhaseID uuid.UUID) (CoursePhaseConfig, error) {
	row := q.db.QueryRow(ctx, getCoursePhaseConfig, coursePhaseID)
	var i CoursePhaseConfig
	err := row.Scan(
		&i.CoursePhaseID,
		&i.TeamSourceCoursePhaseID,
		&i.StudentSourceCoursePhaseID,
		&i.SemesterTag,
	)
	return i, err
}

const upsertCoursePhaseConfig = `-- name: UpsertCoursePhaseConfig :one
INSERT INTO course_phase_config (
    course_phase_id,
    team_source_course_phase_id,
    student_source_course_phase_id,
    semester_tag
)
VALUES ($1, $2, $3, $4)
ON CONFLICT (course_phase_id)
DO UPDATE SET
    team_source_course_phase_id = EXCLUDED.team_source_course_phase_id,
    student_source_course_phase_id = EXCLUDED.student_source_course_phase_id,
    semester_tag = EXCLUDED.semester_tag
RETURNING course_phase_id, team_source_course_phase_id, student_source_course_phase_id, semester_tag
`

type UpsertCoursePhaseConfigParams struct {
	CoursePhaseID              uuid.UUID  `json:"coursePhaseId"`
	TeamSourceCoursePhaseID    *uuid.UUID `json:"teamSourceCoursePhaseId"`
	StudentSourceCoursePhaseID *uuid.UUID `json:"studentSourceCoursePhaseId"`
	SemesterTag                string     `json:"semesterTag"`
}

func (q *Queries) UpsertCoursePhaseConfig(ctx context.Context, arg UpsertCoursePhaseConfigParams) (CoursePhaseConfig, error) {
	row := q.db.QueryRow(ctx, upsertCoursePhaseConfig,
		arg.CoursePhaseID,
		arg.TeamSourceCoursePhaseID,
		arg.StudentSourceCoursePhaseID,
		arg.SemesterTag,
	)
	var i CoursePhaseConfig
	err := row.Scan(
		&i.CoursePhaseID,
		&i.TeamSourceCoursePhaseID,
		&i.StudentSourceCoursePhaseID,
		&i.SemesterTag,
	)
	return i, err
}
