// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: course_phase_config.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const copyCoursePhaseConfig = `-- name: CopyCoursePhaseConfig :exec
INSERT INTO course_phase_config (course_phase_id, semester_tag)
VALUES (
    $1,
    COALESCE((
        SELECT src.semester_tag FROM course_phase_config AS src
        WHERE src.course_phase_id = $2
    ), '')
)
ON CONFLICT (course_phase_id) DO NOTHING
`

type CopyCoursePhaseConfigParams struct {
	TargetCoursePhaseID uuid.UUID `json:"targetCoursePhaseId"`
	SourceCoursePhaseID uuid.UUID `json:"sourceCoursePhaseId"`
}

// Creates the target phase's config row, carrying the source semester tag when there is
// one and falling back to ”. Never overwrites a config already edited on the target.
func (q *Queries) CopyCoursePhaseConfig(ctx context.Context, arg CopyCoursePhaseConfigParams) error {
	_, err := q.db.Exec(ctx, copyCoursePhaseConfig, arg.TargetCoursePhaseID, arg.SourceCoursePhaseID)
	return err
}

const getCoursePhaseConfig = `-- name: GetCoursePhaseConfig :one
SELECT course_phase_id, semester_tag
FROM course_phase_config
WHERE course_phase_id = $1
`

func (q *Queries) GetCoursePhaseConfig(ctx context.Context, coursePhaseID uuid.UUID) (CoursePhaseConfig, error) {
	row := q.db.QueryRow(ctx, getCoursePhaseConfig, coursePhaseID)
	var i CoursePhaseConfig
	err := row.Scan(&i.CoursePhaseID, &i.SemesterTag)
	return i, err
}

const upsertCoursePhaseConfig = `-- name: UpsertCoursePhaseConfig :one
INSERT INTO course_phase_config (
    course_phase_id,
    semester_tag
)
VALUES ($1, $2)
ON CONFLICT (course_phase_id)
DO UPDATE SET
    semester_tag = EXCLUDED.semester_tag
RETURNING course_phase_id, semester_tag
`

type UpsertCoursePhaseConfigParams struct {
	CoursePhaseID uuid.UUID `json:"coursePhaseId"`
	SemesterTag   string    `json:"semesterTag"`
}

func (q *Queries) UpsertCoursePhaseConfig(ctx context.Context, arg UpsertCoursePhaseConfigParams) (CoursePhaseConfig, error) {
	row := q.db.QueryRow(ctx, upsertCoursePhaseConfig, arg.CoursePhaseID, arg.SemesterTag)
	var i CoursePhaseConfig
	err := row.Scan(&i.CoursePhaseID, &i.SemesterTag)
	return i, err
}
