// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type ProviderType string

const (
	ProviderTypeGitlab   ProviderType = "gitlab"
	ProviderTypeSlack    ProviderType = "slack"
	ProviderTypeOutline  ProviderType = "outline"
	ProviderTypeRancher  ProviderType = "rancher"
	ProviderTypeKeycloak ProviderType = "keycloak"
)

func (e *ProviderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProviderType(s)
	case string:
		*e = ProviderType(s)
	default:
		return fmt.Errorf("unsupported scan type for ProviderType: %T", src)
	}
	return nil
}

type NullProviderType struct {
	ProviderType ProviderType `json:"providerType"`
	Valid        bool         `json:"valid"` // Valid is true if ProviderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProviderType) Scan(value interface{}) error {
	if value == nil {
		ns.ProviderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProviderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProviderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProviderType), nil
}

type ResourceScope string

const (
	ResourceScopePerTeam    ResourceScope = "per_team"
	ResourceScopePerStudent ResourceScope = "per_student"
)

func (e *ResourceScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ResourceScope(s)
	case string:
		*e = ResourceScope(s)
	default:
		return fmt.Errorf("unsupported scan type for ResourceScope: %T", src)
	}
	return nil
}

type NullResourceScope struct {
	ResourceScope ResourceScope `json:"resourceScope"`
	Valid         bool          `json:"valid"` // Valid is true if ResourceScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResourceScope) Scan(value interface{}) error {
	if value == nil {
		ns.ResourceScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ResourceScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResourceScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ResourceScope), nil
}

type ResourceStatus string

const (
	ResourceStatusPending    ResourceStatus = "pending"
	ResourceStatusInProgress ResourceStatus = "in_progress"
	ResourceStatusCreated    ResourceStatus = "created"
	ResourceStatusFailed     ResourceStatus = "failed"
)

func (e *ResourceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ResourceStatus(s)
	case string:
		*e = ResourceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ResourceStatus: %T", src)
	}
	return nil
}

type NullResourceStatus struct {
	ResourceStatus ResourceStatus `json:"resourceStatus"`
	Valid          bool           `json:"valid"` // Valid is true if ResourceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResourceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ResourceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ResourceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResourceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ResourceStatus), nil
}

type CoursePhaseConfig struct {
	CoursePhaseID              uuid.UUID  `json:"coursePhaseId"`
	TeamSourceCoursePhaseID    *uuid.UUID `json:"teamSourceCoursePhaseId"`
	StudentSourceCoursePhaseID *uuid.UUID `json:"studentSourceCoursePhaseId"`
	SemesterTag                string     `json:"semesterTag"`
}

type ProviderConfig struct {
	ID            uuid.UUID    `json:"id"`
	CoursePhaseID uuid.UUID    `json:"coursePhaseId"`
	ProviderType  ProviderType `json:"providerType"`
	Credentials   []byte       `json:"credentials"`
}

type ResourceConfig struct {
	ID                  uuid.UUID       `json:"id"`
	CoursePhaseID       uuid.UUID       `json:"coursePhaseId"`
	ProviderType        ProviderType    `json:"providerType"`
	ResourceType        string          `json:"resourceType"`
	Scope               ResourceScope   `json:"scope"`
	NameTemplate        string          `json:"nameTemplate"`
	PermissionMapping   json.RawMessage `json:"permissionMapping"`
	ResourceExtraConfig json.RawMessage `json:"resourceExtraConfig"`
	CreatedAt           time.Time       `json:"createdAt"`
}

type ResourceInstance struct {
	ID                    uuid.UUID      `json:"id"`
	ResourceConfigID      uuid.UUID      `json:"resourceConfigId"`
	CoursePhaseID         uuid.UUID      `json:"coursePhaseId"`
	TeamID                *uuid.UUID     `json:"teamId"`
	CourseParticipationID *uuid.UUID     `json:"courseParticipationId"`
	Status                ResourceStatus `json:"status"`
	ExternalID            *string        `json:"externalId"`
	ExternalUrl           *string        `json:"externalUrl"`
	ErrorMessage          *string        `json:"errorMessage"`
	CreatedAt             time.Time      `json:"createdAt"`
	UpdatedAt             time.Time      `json:"updatedAt"`
}
