// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resource_config.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const copyResourceConfigs = `-- name: CopyResourceConfigs :exec
INSERT INTO resource_config (
    id,
    course_phase_id,
    provider_type,
    resource_type,
    scope,
    name_template,
    permission_mapping,
    resource_extra_config
)
SELECT gen_random_uuid(), $1, rc.provider_type, rc.resource_type, rc.scope, rc.name_template, rc.permission_mapping, rc.resource_extra_config
FROM resource_config AS rc
WHERE rc.course_phase_id = $2
`

type CopyResourceConfigsParams struct {
	TargetCoursePhaseID uuid.UUID `json:"targetCoursePhaseId"`
	SourceCoursePhaseID uuid.UUID `json:"sourceCoursePhaseId"`
}

func (q *Queries) CopyResourceConfigs(ctx context.Context, arg CopyResourceConfigsParams) error {
	_, err := q.db.Exec(ctx, copyResourceConfigs, arg.TargetCoursePhaseID, arg.SourceCoursePhaseID)
	return err
}

const createResourceConfig = `-- name: CreateResourceConfig :one
INSERT INTO resource_config (
    id,
    course_phase_id,
    provider_type,
    resource_type,
    scope,
    name_template,
    permission_mapping,
    resource_extra_config
)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7)
RETURNING id, course_phase_id, provider_type, resource_type, scope, name_template, permission_mapping, resource_extra_config, created_at
`

type CreateResourceConfigParams struct {
	CoursePhaseID       uuid.UUID       `json:"coursePhaseId"`
	ProviderType        ProviderType    `json:"providerType"`
	ResourceType        string          `json:"resourceType"`
	Scope               ResourceScope   `json:"scope"`
	NameTemplate        string          `json:"nameTemplate"`
	PermissionMapping   json.RawMessage `json:"permissionMapping"`
	ResourceExtraConfig json.RawMessage `json:"resourceExtraConfig"`
}

func (q *Queries) CreateResourceConfig(ctx context.Context, arg CreateResourceConfigParams) (ResourceConfig, error) {
	row := q.db.QueryRow(ctx, createResourceConfig,
		arg.CoursePhaseID,
		arg.ProviderType,
		arg.ResourceType,
		arg.Scope,
		arg.NameTemplate,
		arg.PermissionMapping,
		arg.ResourceExtraConfig,
	)
	var i ResourceConfig
	err := row.Scan(
		&i.ID,
		&i.CoursePhaseID,
		&i.ProviderType,
		&i.ResourceType,
		&i.Scope,
		&i.NameTemplate,
		&i.PermissionMapping,
		&i.ResourceExtraConfig,
		&i.CreatedAt,
	)
	return i, err
}

const deleteResourceConfig = `-- name: DeleteResourceConfig :exec
DELETE FROM resource_config
WHERE id = $1 AND course_phase_id = $2
`

type DeleteResourceConfigParams struct {
	ID            uuid.UUID `json:"id"`
	CoursePhaseID uuid.UUID `json:"coursePhaseId"`
}

func (q *Queries) DeleteResourceConfig(ctx context.Context, arg DeleteResourceConfigParams) error {
	_, err := q.db.Exec(ctx, deleteResourceConfig, arg.ID, arg.CoursePhaseID)
	return err
}

const getResourceConfig = `-- name: GetResourceConfig :one
SELECT id, course_phase_id, provider_type, resource_type, scope, name_template, permission_mapping, resource_extra_config, created_at
FROM resource_config
WHERE id = $1 AND course_phase_id = $2
`

type GetResourceConfigParams struct {
	ID            uuid.UUID `json:"id"`
	CoursePhaseID uuid.UUID `json:"coursePhaseId"`
}

func (q *Queries) GetResourceConfig(ctx context.Context, arg GetResourceConfigParams) (ResourceConfig, error) {
	row := q.db.QueryRow(ctx, getResourceConfig, arg.ID, arg.CoursePhaseID)
	var i ResourceConfig
	err := row.Scan(
		&i.ID,
		&i.CoursePhaseID,
		&i.ProviderType,
		&i.ResourceType,
		&i.Scope,
		&i.NameTemplate,
		&i.PermissionMapping,
		&i.ResourceExtraConfig,
		&i.CreatedAt,
	)
	return i, err
}

const listResourceConfigs = `-- name: ListResourceConfigs :many
SELECT id, course_phase_id, provider_type, resource_type, scope, name_template, permission_mapping, resource_extra_config, created_at
FROM resource_config
WHERE course_phase_id = $1
ORDER BY created_at
`

func (q *Queries) ListResourceConfigs(ctx context.Context, coursePhaseID uuid.UUID) ([]ResourceConfig, error) {
	rows, err := q.db.Query(ctx, listResourceConfigs, coursePhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceConfig
	for rows.Next() {
		var i ResourceConfig
		if err := rows.Scan(
			&i.ID,
			&i.CoursePhaseID,
			&i.ProviderType,
			&i.ResourceType,
			&i.Scope,
			&i.NameTemplate,
			&i.PermissionMapping,
			&i.ResourceExtraConfig,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResourceConfig = `-- name: UpdateResourceConfig :one
UPDATE resource_config
SET resource_type = $3,
    scope = $4,
    name_template = $5,
    permission_mapping = $6,
    resource_extra_config = $7
WHERE id = $1 AND course_phase_id = $2
RETURNING id, course_phase_id, provider_type, resource_type, scope, name_template, permission_mapping, resource_extra_config, created_at
`

type UpdateResourceConfigParams struct {
	ID                  uuid.UUID       `json:"id"`
	CoursePhaseID       uuid.UUID       `json:"coursePhaseId"`
	ResourceType        string          `json:"resourceType"`
	Scope               ResourceScope   `json:"scope"`
	NameTemplate        string          `json:"nameTemplate"`
	PermissionMapping   json.RawMessage `json:"permissionMapping"`
	ResourceExtraConfig json.RawMessage `json:"resourceExtraConfig"`
}

func (q *Queries) UpdateResourceConfig(ctx context.Context, arg UpdateResourceConfigParams) (ResourceConfig, error) {
	row := q.db.QueryRow(ctx, updateResourceConfig,
		arg.ID,
		arg.CoursePhaseID,
		arg.ResourceType,
		arg.Scope,
		arg.NameTemplate,
		arg.PermissionMapping,
		arg.ResourceExtraConfig,
	)
	var i ResourceConfig
	err := row.Scan(
		&i.ID,
		&i.CoursePhaseID,
		&i.ProviderType,
		&i.ResourceType,
		&i.Scope,
		&i.NameTemplate,
		&i.PermissionMapping,
		&i.ResourceExtraConfig,
		&i.CreatedAt,
	)
	return i, err
}
