// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resource_instance.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const claimPendingInstances = `-- name: ClaimPendingInstances :many
UPDATE resource_instance
SET status = 'in_progress',
    updated_at = NOW()
WHERE id IN (
    SELECT pending.id FROM resource_instance AS pending
    WHERE pending.course_phase_id = $1 AND pending.status = 'pending'
    FOR UPDATE SKIP LOCKED
)
RETURNING id, resource_config_id, course_phase_id, team_id, course_participation_id, status, external_id, external_url, error_message, created_at, updated_at
`

// Atomically takes ownership of every pending instance in one statement, so two
// overlapping runs can never process the same row.
func (q *Queries) ClaimPendingInstances(ctx context.Context, coursePhaseID uuid.UUID) ([]ResourceInstance, error) {
	rows, err := q.db.Query(ctx, claimPendingInstances, coursePhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceInstance
	for rows.Next() {
		var i ResourceInstance
		if err := rows.Scan(
			&i.ID,
			&i.ResourceConfigID,
			&i.CoursePhaseID,
			&i.TeamID,
			&i.CourseParticipationID,
			&i.Status,
			&i.ExternalID,
			&i.ExternalUrl,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countLiveInstancesForConfig = `-- name: CountLiveInstancesForConfig :one
SELECT COUNT(*)
FROM resource_instance
WHERE resource_config_id = $1 AND status != 'failed'
`

// Counts the instances of one config that still describe a live external resource.
// A failed instance never created anything, so it does not pin the config's identity.
func (q *Queries) CountLiveInstancesForConfig(ctx context.Context, resourceConfigID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveInstancesForConfig, resourceConfigID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNonTerminalInstances = `-- name: CountNonTerminalInstances :one
SELECT COUNT(*)
FROM resource_instance
WHERE course_phase_id = $1 AND status IN ('pending', 'in_progress')
`

func (q *Queries) CountNonTerminalInstances(ctx context.Context, coursePhaseID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNonTerminalInstances, coursePhaseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createResourceInstance = `-- name: CreateResourceInstance :one
INSERT INTO resource_instance (
    id,
    resource_config_id,
    course_phase_id,
    team_id,
    course_participation_id
)
VALUES (gen_random_uuid(), $1, $2, $3, $4)
ON CONFLICT DO NOTHING
RETURNING id, resource_config_id, course_phase_id, team_id, course_participation_id, status, external_id, external_url, error_message, created_at, updated_at
`

type CreateResourceInstanceParams struct {
	ResourceConfigID      uuid.UUID  `json:"resourceConfigId"`
	CoursePhaseID         uuid.UUID  `json:"coursePhaseId"`
	TeamID                *uuid.UUID `json:"teamId"`
	CourseParticipationID *uuid.UUID `json:"courseParticipationId"`
}

func (q *Queries) CreateResourceInstance(ctx context.Context, arg CreateResourceInstanceParams) (ResourceInstance, error) {
	row := q.db.QueryRow(ctx, createResourceInstance,
		arg.ResourceConfigID,
		arg.CoursePhaseID,
		arg.TeamID,
		arg.CourseParticipationID,
	)
	var i ResourceInstance
	err := row.Scan(
		&i.ID,
		&i.ResourceConfigID,
		&i.CoursePhaseID,
		&i.TeamID,
		&i.CourseParticipationID,
		&i.Status,
		&i.ExternalID,
		&i.ExternalUrl,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteResourceInstance = `-- name: DeleteResourceInstance :exec
DELETE FROM resource_instance
WHERE id = $1 AND course_phase_id = $2
`

type DeleteResourceInstanceParams struct {
	ID            uuid.UUID `json:"id"`
	CoursePhaseID uuid.UUID `json:"coursePhaseId"`
}

func (q *Queries) DeleteResourceInstance(ctx context.Context, arg DeleteResourceInstanceParams) error {
	_, err := q.db.Exec(ctx, deleteResourceInstance, arg.ID, arg.CoursePhaseID)
	return err
}

const failStaleInProgressInstances = `-- name: FailStaleInProgressInstances :execrows
UPDATE resource_instance
SET status = 'failed',
    error_message = $1,
    updated_at = NOW()
WHERE status = 'in_progress'
  AND updated_at < CURRENT_TIMESTAMP - make_interval(secs => $2::double precision)
`

type FailStaleInProgressInstancesParams struct {
	ErrorMessage       *string `json:"errorMessage"`
	MaxClaimAgeSeconds float64 `json:"maxClaimAgeSeconds"`
}

// Recovers instances a crashed process left claimed. They are marked failed rather
// than pending: nothing picks a pending row up on its own (the worker needs the
// lecturer's auth header to resolve targets), while a failed one is terminal, visible
// in the UI and retryable. The cutoff keeps the sweep off work another replica is
// still doing - a worker's context is capped well below it.
// The cutoff is computed from the database clock, not the caller's: updated_at is a
// timestamp without a time zone, so a client-side cutoff would be off by the server's
// UTC offset.
func (q *Queries) FailStaleInProgressInstances(ctx context.Context, arg FailStaleInProgressInstancesParams) (int64, error) {
	result, err := q.db.Exec(ctx, failStaleInProgressInstances, arg.ErrorMessage, arg.MaxClaimAgeSeconds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getResourceInstance = `-- name: GetResourceInstance :one
SELECT id, resource_config_id, course_phase_id, team_id, course_participation_id, status, external_id, external_url, error_message, created_at, updated_at
FROM resource_instance
WHERE id = $1 AND course_phase_id = $2
`

type GetResourceInstanceParams struct {
	ID            uuid.UUID `json:"id"`
	CoursePhaseID uuid.UUID `json:"coursePhaseId"`
}

func (q *Queries) GetResourceInstance(ctx context.Context, arg GetResourceInstanceParams) (ResourceInstance, error) {
	row := q.db.QueryRow(ctx, getResourceInstance, arg.ID, arg.CoursePhaseID)
	var i ResourceInstance
	err := row.Scan(
		&i.ID,
		&i.ResourceConfigID,
		&i.CoursePhaseID,
		&i.TeamID,
		&i.CourseParticipationID,
		&i.Status,
		&i.ExternalID,
		&i.ExternalUrl,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listResourceInstances = `-- name: ListResourceInstances :many
SELECT id, resource_config_id, course_phase_id, team_id, course_participation_id, status, external_id, external_url, error_message, created_at, updated_at
FROM resource_instance
WHERE course_phase_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListResourceInstances(ctx context.Context, coursePhaseID uuid.UUID) ([]ResourceInstance, error) {
	rows, err := q.db.Query(ctx, listResourceInstances, coursePhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceInstance
	for rows.Next() {
		var i ResourceInstance
		if err := rows.Scan(
			&i.ID,
			&i.ResourceConfigID,
			&i.CoursePhaseID,
			&i.TeamID,
			&i.CourseParticipationID,
			&i.Status,
			&i.ExternalID,
			&i.ExternalUrl,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInstanceCreated = `-- name: MarkInstanceCreated :exec
UPDATE resource_instance
SET status = 'created',
    external_id = $2,
    external_url = $3,
    error_message = NULL,
    updated_at = NOW()
WHERE id = $1
`

type MarkInstanceCreatedParams struct {
	ID          uuid.UUID `json:"id"`
	ExternalID  *string   `json:"externalId"`
	ExternalUrl *string   `json:"externalUrl"`
}

func (q *Queries) MarkInstanceCreated(ctx context.Context, arg MarkInstanceCreatedParams) error {
	_, err := q.db.Exec(ctx, markInstanceCreated, arg.ID, arg.ExternalID, arg.ExternalUrl)
	return err
}

const markInstanceFailed = `-- name: MarkInstanceFailed :exec
UPDATE resource_instance
SET status = 'failed',
    error_message = $2,
    updated_at = NOW()
WHERE id = $1
`

type MarkInstanceFailedParams struct {
	ID           uuid.UUID `json:"id"`
	ErrorMessage *string   `json:"errorMessage"`
}

func (q *Queries) MarkInstanceFailed(ctx context.Context, arg MarkInstanceFailedParams) error {
	_, err := q.db.Exec(ctx, markInstanceFailed, arg.ID, arg.ErrorMessage)
	return err
}

const markInstancePartial = `-- name: MarkInstancePartial :exec
UPDATE resource_instance
SET status = 'partial',
    external_id = $2,
    external_url = $3,
    error_message = $4,
    updated_at = NOW()
WHERE id = $1
`

type MarkInstancePartialParams struct {
	ID           uuid.UUID `json:"id"`
	ExternalID   *string   `json:"externalId"`
	ExternalUrl  *string   `json:"externalUrl"`
	ErrorMessage *string   `json:"errorMessage"`
}

func (q *Queries) MarkInstancePartial(ctx context.Context, arg MarkInstancePartialParams) error {
	_, err := q.db.Exec(ctx, markInstancePartial,
		arg.ID,
		arg.ExternalID,
		arg.ExternalUrl,
		arg.ErrorMessage,
	)
	return err
}

const resetInstanceToPending = `-- name: ResetInstanceToPending :one
UPDATE resource_instance
SET status = 'pending',
    error_message = NULL,
    updated_at = NOW()
WHERE id = $1 AND course_phase_id = $2 AND status IN ('failed', 'partial')
RETURNING id, resource_config_id, course_phase_id, team_id, course_participation_id, status, external_id, external_url, error_message, created_at, updated_at
`

type ResetInstanceToPendingParams struct {
	ID            uuid.UUID `json:"id"`
	CoursePhaseID uuid.UUID `json:"coursePhaseId"`
}

func (q *Queries) ResetInstanceToPending(ctx context.Context, arg ResetInstanceToPendingParams) (ResourceInstance, error) {
	row := q.db.QueryRow(ctx, resetInstanceToPending, arg.ID, arg.CoursePhaseID)
	var i ResourceInstance
	err := row.Scan(
		&i.ID,
		&i.ResourceConfigID,
		&i.CoursePhaseID,
		&i.TeamID,
		&i.CourseParticipationID,
		&i.Status,
		&i.ExternalID,
		&i.ExternalUrl,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const tryLockPhaseExecution = `-- name: TryLockPhaseExecution :one
SELECT pg_try_advisory_xact_lock(hashtextextended($1::text, 0))
`

// Transaction-scoped advisory lock keyed on the course phase. Held only while the
// trigger counts and inserts instances, never across provider calls.
func (q *Queries) TryLockPhaseExecution(ctx context.Context, coursePhaseID string) (bool, error) {
	row := q.db.QueryRow(ctx, tryLockPhaseExecution, coursePhaseID)
	var pg_try_advisory_xact_lock bool
	err := row.Scan(&pg_try_advisory_xact_lock)
	return pg_try_advisory_xact_lock, err
}
