// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resource_instance.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countNonTerminalInstances = `-- name: CountNonTerminalInstances :one
SELECT COUNT(*)
FROM resource_instance
WHERE course_phase_id = $1 AND status IN ('pending', 'in_progress')
`

func (q *Queries) CountNonTerminalInstances(ctx context.Context, coursePhaseID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNonTerminalInstances, coursePhaseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createResourceInstance = `-- name: CreateResourceInstance :one
INSERT INTO resource_instance (
    id,
    resource_config_id,
    course_phase_id,
    team_id,
    course_participation_id
)
VALUES (gen_random_uuid(), $1, $2, $3, $4)
ON CONFLICT DO NOTHING
RETURNING id, resource_config_id, course_phase_id, team_id, course_participation_id, status, external_id, external_url, error_message, created_at, updated_at
`

type CreateResourceInstanceParams struct {
	ResourceConfigID      uuid.UUID  `json:"resourceConfigId"`
	CoursePhaseID         uuid.UUID  `json:"coursePhaseId"`
	TeamID                *uuid.UUID `json:"teamId"`
	CourseParticipationID *uuid.UUID `json:"courseParticipationId"`
}

func (q *Queries) CreateResourceInstance(ctx context.Context, arg CreateResourceInstanceParams) (ResourceInstance, error) {
	row := q.db.QueryRow(ctx, createResourceInstance,
		arg.ResourceConfigID,
		arg.CoursePhaseID,
		arg.TeamID,
		arg.CourseParticipationID,
	)
	var i ResourceInstance
	err := row.Scan(
		&i.ID,
		&i.ResourceConfigID,
		&i.CoursePhaseID,
		&i.TeamID,
		&i.CourseParticipationID,
		&i.Status,
		&i.ExternalID,
		&i.ExternalUrl,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteResourceInstance = `-- name: DeleteResourceInstance :exec
DELETE FROM resource_instance
WHERE id = $1 AND course_phase_id = $2
`

type DeleteResourceInstanceParams struct {
	ID            uuid.UUID `json:"id"`
	CoursePhaseID uuid.UUID `json:"coursePhaseId"`
}

func (q *Queries) DeleteResourceInstance(ctx context.Context, arg DeleteResourceInstanceParams) error {
	_, err := q.db.Exec(ctx, deleteResourceInstance, arg.ID, arg.CoursePhaseID)
	return err
}

const getResourceInstance = `-- name: GetResourceInstance :one
SELECT id, resource_config_id, course_phase_id, team_id, course_participation_id, status, external_id, external_url, error_message, created_at, updated_at
FROM resource_instance
WHERE id = $1 AND course_phase_id = $2
`

type GetResourceInstanceParams struct {
	ID            uuid.UUID `json:"id"`
	CoursePhaseID uuid.UUID `json:"coursePhaseId"`
}

func (q *Queries) GetResourceInstance(ctx context.Context, arg GetResourceInstanceParams) (ResourceInstance, error) {
	row := q.db.QueryRow(ctx, getResourceInstance, arg.ID, arg.CoursePhaseID)
	var i ResourceInstance
	err := row.Scan(
		&i.ID,
		&i.ResourceConfigID,
		&i.CoursePhaseID,
		&i.TeamID,
		&i.CourseParticipationID,
		&i.Status,
		&i.ExternalID,
		&i.ExternalUrl,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingInstances = `-- name: ListPendingInstances :many
SELECT id, resource_config_id, course_phase_id, team_id, course_participation_id, status, external_id, external_url, error_message, created_at, updated_at
FROM resource_instance
WHERE course_phase_id = $1 AND status = 'pending'
`

func (q *Queries) ListPendingInstances(ctx context.Context, coursePhaseID uuid.UUID) ([]ResourceInstance, error) {
	rows, err := q.db.Query(ctx, listPendingInstances, coursePhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceInstance
	for rows.Next() {
		var i ResourceInstance
		if err := rows.Scan(
			&i.ID,
			&i.ResourceConfigID,
			&i.CoursePhaseID,
			&i.TeamID,
			&i.CourseParticipationID,
			&i.Status,
			&i.ExternalID,
			&i.ExternalUrl,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourceInstances = `-- name: ListResourceInstances :many
SELECT id, resource_config_id, course_phase_id, team_id, course_participation_id, status, external_id, external_url, error_message, created_at, updated_at
FROM resource_instance
WHERE course_phase_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListResourceInstances(ctx context.Context, coursePhaseID uuid.UUID) ([]ResourceInstance, error) {
	rows, err := q.db.Query(ctx, listResourceInstances, coursePhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceInstance
	for rows.Next() {
		var i ResourceInstance
		if err := rows.Scan(
			&i.ID,
			&i.ResourceConfigID,
			&i.CoursePhaseID,
			&i.TeamID,
			&i.CourseParticipationID,
			&i.Status,
			&i.ExternalID,
			&i.ExternalUrl,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetFailedInstanceToPending = `-- name: ResetFailedInstanceToPending :exec
UPDATE resource_instance
SET status = 'pending',
    error_message = NULL,
    updated_at = NOW()
WHERE id = $1 AND course_phase_id = $2 AND status = 'failed'
`

type ResetFailedInstanceToPendingParams struct {
	ID            uuid.UUID `json:"id"`
	CoursePhaseID uuid.UUID `json:"coursePhaseId"`
}

func (q *Queries) ResetFailedInstanceToPending(ctx context.Context, arg ResetFailedInstanceToPendingParams) error {
	_, err := q.db.Exec(ctx, resetFailedInstanceToPending, arg.ID, arg.CoursePhaseID)
	return err
}

const resetInProgressToPending = `-- name: ResetInProgressToPending :exec
UPDATE resource_instance
SET status = 'pending',
    updated_at = NOW()
WHERE status = 'in_progress'
`

func (q *Queries) ResetInProgressToPending(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetInProgressToPending)
	return err
}

const updateResourceInstanceStatus = `-- name: UpdateResourceInstanceStatus :exec
UPDATE resource_instance
SET status = $2,
    external_id = $3,
    external_url = $4,
    error_message = $5,
    updated_at = NOW()
WHERE id = $1
`

type UpdateResourceInstanceStatusParams struct {
	ID           uuid.UUID      `json:"id"`
	Status       ResourceStatus `json:"status"`
	ExternalID   *string        `json:"externalId"`
	ExternalUrl  *string        `json:"externalUrl"`
	ErrorMessage *string        `json:"errorMessage"`
}

func (q *Queries) UpdateResourceInstanceStatus(ctx context.Context, arg UpdateResourceInstanceStatusParams) error {
	_, err := q.db.Exec(ctx, updateResourceInstanceStatus,
		arg.ID,
		arg.Status,
		arg.ExternalID,
		arg.ExternalUrl,
		arg.ErrorMessage,
	)
	return err
}
