// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CoursePhaseConfig struct {
	CoursePhaseID uuid.UUID          `json:"course_phase_id"`
	TargetMode    string             `json:"target_mode"`
	FeedbackMode  string             `json:"feedback_mode"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type FeedbackAnswer struct {
	FeedbackFormID  uuid.UUID          `json:"feedback_form_id"`
	CategoryID      uuid.UUID          `json:"category_id"`
	Value           string             `json:"value"`
	Revision        int64              `json:"revision"`
	UpdatedByUserID string             `json:"updated_by_user_id"`
	UpdatedByName   string             `json:"updated_by_name"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type FeedbackCategory struct {
	ID            uuid.UUID          `json:"id"`
	CoursePhaseID uuid.UUID          `json:"course_phase_id"`
	Name          string             `json:"name"`
	Description   string             `json:"description"`
	Position      int32              `json:"position"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type FeedbackContributor struct {
	FeedbackFormID     uuid.UUID          `json:"feedback_form_id"`
	UserID             string             `json:"user_id"`
	Name               string             `json:"name"`
	Email              string             `json:"email"`
	FirstContributedAt pgtype.Timestamptz `json:"first_contributed_at"`
	LastContributedAt  pgtype.Timestamptz `json:"last_contributed_at"`
}

type FeedbackForm struct {
	ID              uuid.UUID          `json:"id"`
	PresentationID  uuid.UUID          `json:"presentation_id"`
	ScopeKey        string             `json:"scope_key"`
	EvaluatorUserID pgtype.Text        `json:"evaluator_user_id"`
	EvaluatorName   string             `json:"evaluator_name"`
	EvaluatorEmail  string             `json:"evaluator_email"`
	Status          string             `json:"status"`
	SubmittedAt     pgtype.Timestamptz `json:"submitted_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type FeedbackPresence struct {
	PresentationID uuid.UUID          `json:"presentation_id"`
	ConnectionID   uuid.UUID          `json:"connection_id"`
	UserID         string             `json:"user_id"`
	Name           string             `json:"name"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

type Presentation struct {
	ID                       uuid.UUID          `json:"id"`
	CoursePhaseID            uuid.UUID          `json:"course_phase_id"`
	SlotID                   uuid.UUID          `json:"slot_id"`
	TargetType               string             `json:"target_type"`
	TargetID                 uuid.UUID          `json:"target_id"`
	TargetName               string             `json:"target_name"`
	FeedbackReleaseName      pgtype.Text        `json:"feedback_release_name"`
	FeedbackReleasedAt       pgtype.Timestamptz `json:"feedback_released_at"`
	FeedbackReleasedByUserID pgtype.Text        `json:"feedback_released_by_user_id"`
	FeedbackReleasedByName   pgtype.Text        `json:"feedback_released_by_name"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type PresentationMaterial struct {
	ID               uuid.UUID          `json:"id"`
	PresentationID   uuid.UUID          `json:"presentation_id"`
	OriginalFilename string             `json:"original_filename"`
	ContentType      string             `json:"content_type"`
	SizeBytes        int64              `json:"size_bytes"`
	StorageKey       string             `json:"storage_key"`
	State            string             `json:"state"`
	UploaderUserID   string             `json:"uploader_user_id"`
	UploaderName     string             `json:"uploader_name"`
	UploaderEmail    string             `json:"uploader_email"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type PresentationSlot struct {
	ID            uuid.UUID          `json:"id"`
	CoursePhaseID uuid.UUID          `json:"course_phase_id"`
	StartTime     pgtype.Timestamptz `json:"start_time"`
	EndTime       pgtype.Timestamptz `json:"end_time"`
	Location      pgtype.Text        `json:"location"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
