// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: coursePhaseCopy.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const copyCoursePhaseConfig = `-- name: CopyCoursePhaseConfig :exec
INSERT INTO
    course_phase_config (
        course_phase_id,
        template_content,
        student_page_text
    )
SELECT
    $1::uuid,
    template_content,
    student_page_text
FROM course_phase_config
WHERE
    course_phase_id = $2::uuid
ON CONFLICT (course_phase_id) DO
UPDATE
SET
    template_content = EXCLUDED.template_content,
    student_page_text = EXCLUDED.student_page_text,
    updated_at = NOW(),
    updated_by = NULL
`

type CopyCoursePhaseConfigParams struct {
	TargetCoursePhaseID uuid.UUID `json:"target_course_phase_id"`
	SourceCoursePhaseID uuid.UUID `json:"source_course_phase_id"`
}

// Copies the template and the student page text of a certificate phase into another phase. The
// release date is deliberately left out: it is printed as the certificate date, and without one
// the copied phase stays unreleased until a lecturer sets it. Download records belong to the
// source phase's students and are never copied. A source phase without a config row copies
// nothing. On an existing target row the copied template replaces the target's, so its updater is
// cleared.
func (q *Queries) CopyCoursePhaseConfig(ctx context.Context, arg CopyCoursePhaseConfigParams) error {
	_, err := q.db.Exec(ctx, copyCoursePhaseConfig, arg.TargetCoursePhaseID, arg.SourceCoursePhaseID)
	return err
}
