// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CertificateDownload struct {
	ID            int32              `json:"id"`
	StudentID     uuid.UUID          `json:"student_id"`
	CoursePhaseID uuid.UUID          `json:"course_phase_id"`
	FirstDownload pgtype.Timestamptz `json:"first_download"`
	LastDownload  pgtype.Timestamptz `json:"last_download"`
	DownloadCount int32              `json:"download_count"`
}

type CoursePhaseConfig struct {
	CoursePhaseID   uuid.UUID          `json:"course_phase_id"`
	TemplateContent pgtype.Text        `json:"template_content"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy       pgtype.Text        `json:"updated_by"`
	ReleaseDate     pgtype.Timestamptz `json:"release_date"`
}
